[package]
name = "sdk_test_nodejs_typescript"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
sdk_test_harness_setup = { path = "../../harness_setup" }

[dev-dependencies]
sdk_test_harness_runner = { path = "../../harness_runner" }

[package.metadata.ci]
wasm_support = false
