//! BAML Runtime for Rust
//!
//! This crate provides the runtime support for BAML-generated Rust code.
//! Users should not import from this crate directly - instead, use the
//! generated `baml_client` crate which re-exports necessary types.
//!
//! # Derive Macros
//!
//! Use `#[derive(BamlEncode)]` and `#[derive(BamlDecode)]` to automatically
//! implement serialization for your types:
//!
//! ```ignore
//! use baml::{BamlEncode, BamlDecode};
//!
//! #[derive(BamlEncode, BamlDecode)]
//! #[baml(name = "Person")]
//! struct Person {
//!     name: String,
//!     #[baml(name = "years_old")]
//!     age: i64,
//! }
//! ```

mod args;
mod codec;
mod error;
mod ffi;
mod known_types;
mod raw_objects;
mod runtime;
mod stream;
mod types;

// Proto module generated by prost-build
mod proto {
    pub mod baml_cffi_v1 {
        include!(concat!(env!("OUT_DIR"), "/baml.cffi.v1.rs"));
    }
}

use std::ffi::CString;

// Public API - re-exported through baml_client
pub use args::FunctionArgs;
pub use codec::{
    decode_enum, decode_field, decode_optional_field, encode_class, encode_enum, BamlClass,
    BamlDecode, BamlEncode, BamlEnum,
};
// New dynamic type exports
pub use codec::{
    BamlValue, DynamicClass, DynamicEnum, DynamicUnion, FromBamlValue, FromBamlValueRef,
    KnownTypes,
};
pub use error::BamlError;
pub use raw_objects::{
    // Collector types
    Collector, FunctionLog, LogType, Usage,
    // Media types
    Audio, Image, Pdf, Video,
    // TypeBuilder types
    ClassBuilder, ClassPropertyBuilder, EnumBuilder, EnumValueBuilder, TypeBuilder, TypeDef,
};
pub use runtime::BamlRuntime;
pub use stream::{StreamEvent, StreamResult};
pub use types::{Check, CheckStatus, Checked, StreamState, StreamingState};

// Re-export derive macros
pub use baml_macros::{BamlDecode, BamlEncode};

/// Internal module for derive macro support.
///
/// This module exposes proto types needed by the generated derive macro code.
/// Do not use directly - use the derive macros instead.
#[doc(hidden)]
pub mod __internal {
    pub use crate::ffi::callbacks;
    pub use crate::proto::baml_cffi_v1::*;
}

/// Call baml-cli with the given arguments
/// Returns the exit code
pub fn invoke_cli(args: &[&str]) -> i32 {
    // Convert args to C strings
    let c_args: Vec<CString> = args
        .iter()
        .map(|s| CString::new(*s).expect("invalid arg"))
        .collect();

    // Create array of pointers
    let c_arg_ptrs: Vec<*const libc::c_char> = c_args
        .iter()
        .map(|s| s.as_ptr())
        .chain(std::iter::once(std::ptr::null())) // null terminator
        .collect();

    unsafe { ffi::invoke_runtime_cli(c_arg_ptrs.as_ptr()) }
}

/// Get the BAML library version
pub fn version() -> String {
    let ptr = unsafe { ffi::version() };
    if ptr.is_null() {
        return "unknown".to_string();
    }
    unsafe {
        std::ffi::CStr::from_ptr(ptr)
            .to_string_lossy()
            .into_owned()
    }
}
