[package]
edition = "2021"
name = "baml-schema-build"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.87"
wasm-logger = { version = "0.2.0" }
baml-fmt = { path = "../baml-fmt" }
