[package]
name = "baml-schema-build"
version = "0.1.1-canary.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.87"
wasm-logger = { version = "0.2.0", optional = true }
baml-fmt = { path = "../baml-fmt" }