[toolchain]
# If you set this > 1.81 you may run into this webassembly issue:
# https://github.com/rustwasm/rust-webpack-template/issues/191
# If you really want > 1.81 you can try using wasm-bindgen-cli 2.92.2 instead
# channel = "1.81.0" # Update: reverting this to 2.92 and not pinning the rustc version since the update to 2.100 broke the build
components = []
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"