[toolchain]
# If you set this > 1.81 you may run into this webassembly issue:
# https://github.com/rustwasm/rust-webpack-template/issues/191
# If you really want > 1.81 you can try using wasm-bindgen-cli 2.92.2 instead
channel = "1.81.0"
components = []
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"