// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"primitive_types/baml_client/stream_types"
	"primitive_types/baml_client/types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() TFinal {
	return *s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() TStream {
	return *s.as_stream
}

// / Streaming version of TestEmptyCollections
func (*stream) TestEmptyCollections(ctx context.Context, input string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestEmptyCollections: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "TestEmptyCollections", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.PrimitiveArrays)
					channel <- StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.PrimitiveArrays)
					channel <- StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}

// / Streaming version of TestMixedPrimitives
func (*stream) TestMixedPrimitives(ctx context.Context, input string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.MixedPrimitives, types.MixedPrimitives], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestMixedPrimitives: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "TestMixedPrimitives", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.MixedPrimitives, types.MixedPrimitives])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.MixedPrimitives)
					channel <- StreamValue[stream_types.MixedPrimitives, types.MixedPrimitives]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.MixedPrimitives)
					channel <- StreamValue[stream_types.MixedPrimitives, types.MixedPrimitives]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}

// / Streaming version of TestPrimitiveArrays
func (*stream) TestPrimitiveArrays(ctx context.Context, input string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveArrays: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "TestPrimitiveArrays", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.PrimitiveArrays)
					channel <- StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.PrimitiveArrays)
					channel <- StreamValue[stream_types.PrimitiveArrays, types.PrimitiveArrays]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}

// / Streaming version of TestPrimitiveMaps
func (*stream) TestPrimitiveMaps(ctx context.Context, input string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.PrimitiveMaps, types.PrimitiveMaps], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveMaps: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "TestPrimitiveMaps", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.PrimitiveMaps, types.PrimitiveMaps])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.PrimitiveMaps)
					channel <- StreamValue[stream_types.PrimitiveMaps, types.PrimitiveMaps]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.PrimitiveMaps)
					channel <- StreamValue[stream_types.PrimitiveMaps, types.PrimitiveMaps]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}

// / Streaming version of TestPrimitiveTypes
func (*stream) TestPrimitiveTypes(ctx context.Context, input string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.PrimitiveTypes, types.PrimitiveTypes], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"input": input},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	encoded, err := baml.EncodeArgs(args)
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: TestPrimitiveTypes: %w", err)
		panic(wrapped_err)
	}

	internal_ctx := context.Background()
	internal_channel, err := bamlRuntime.CallFunctionStream(internal_ctx, "TestPrimitiveTypes", encoded)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.PrimitiveTypes, types.PrimitiveTypes])
	go func() {
		defer func() {
			internal_ctx.Done()
		}()
		for {
			select {
			case <-ctx.Done():
				close(channel)
				return
			case result, ok := <-internal_channel:
				if !ok {
					close(channel)
					return
				}
				if result.Error != nil {
					close(channel)
					return
				}
				if result.HasData {
					data := *(result.Data).(*types.PrimitiveTypes)
					channel <- StreamValue[stream_types.PrimitiveTypes, types.PrimitiveTypes]{
						IsFinal:  true,
						as_final: &data,
					}
				} else {
					data := *(result.StreamData).(*stream_types.PrimitiveTypes)
					channel <- StreamValue[stream_types.PrimitiveTypes, types.PrimitiveTypes]{
						IsFinal:   false,
						as_stream: &data,
					}
				}
			}
		}
	}()
	return channel, nil
}
