openapi: 3.1.0
info:
  title: PyBackend API
  version: 0.1.0
paths:
  /api/extract:
    post:
      tags:
        - Extraction
      summary: Extract Files
      description: Upload one or more files to receive their JSON representations along with metadata and usage information.
      operationId: extract
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ExtractRequest"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtractResponse"
        "400":
          description: Invalid Request Parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ExtractRequest:
      type: object
      title: Extract Request
      required:
        - files
      properties:
        files:
          type: array
          title: Files
          description: The files to be uploaded.
          items:
            type: string
            format: binary
        prompt:
          type: string
          title: Prompt
          description: Optional prompt to guide the processing.
          nullable: true
        stream:
          type: boolean
          title: Stream
          description: Enable streaming of the response.
          default: false
          nullable: true
    ErrorResponse:
      type: object
      title: Error Response
      required:
        - error
        - code
      properties:
        error:
          type: string
          title: Error Message
        code:
          type: integer
          title: Error Code
    ExtractResponse:
      type: object
      title: Extract Response
      required:
        - extracted_files
        - input_char_count
        - output_char_count
        - input_megapixels
      properties:
        extracted_files:
          type: array
          title: Extracted Files
          items:
            $ref: "#/components/schemas/ExtractedContent"
        input_char_count:
          type: integer
          title: Input Character Count
        output_char_count:
          type: integer
          title: Output Character Count
        input_megapixels:
          type: number
          title: Input Megapixels
    ExtractedContent:
      type: object
      title: Extracted Content
      required:
        - file_name
        - extracted_content
      properties:
        file_name:
          type: string
          title: File Name
        extracted_content:
          title: Extracted Content
          anyOf:
            - type: object
            - type: array
              items:
                type: object
    HTTPValidationError:
      type: object
      title: HTTP Validation Error
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: "#/components/schemas/ValidationError"
    ValidationError:
      type: object
      title: Validation Error
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
