version: 2
updates:
  # npm packages
  - package-ecosystem: "npm"
    directory: "/" # root directory or adjust if packages are located elsewhere
    schedule:
      interval: "monthly" # Perform updates once a month
    open-pull-requests-limit: 1 # Only one PR at a time
    commit-message:
      prefix: "chore" # Set the commit prefix to "chore"
    rebase-strategy: auto # Automatically rebases PRs if needed
    target-branch: "canary" # Target the 'canary' branch for PRs
    groups:
      all-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # root directory or location of the workflows
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
    rebase-strategy: auto
    target-branch: "canary"
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # adjust if your Python code is in a different folder
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
    rebase-strategy: auto
    target-branch: "canary"
    groups:
      all-dependencies:
        patterns:
          - "*"
  # Docker
  - package-ecosystem: "docker"
    directory: "/" # adjust if your Dockerfile is in a subdirectory
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
    rebase-strategy: auto
    target-branch: "canary"
    groups:
      all-dependencies:
        patterns:
          - "*"
