packages:
  - typescript/apps/*
  - typescript/packages/*
  - typescript/workspace-tools/*
  - integ-tests/*
  - engine
  - engine/*
  - engine/baml-lib/baml/tests/validation_files/headers/mermaid-sandbox/
  - engine/baml-runtime/src/control_flow/mermaid-sandbox/
  - engine/baml-schema-wasm/*
  - fern
  - engine/baml-runtime/tests/viz-runtime/web
  - examples/internal/vaibhav/*
  - examples/internal/aaron/*
  - examples/internal/sam/*
  - examples/internal/greg/*
  - examples/internal/antonio/*
  # - engine/language_client_typescript/npm/darwin-arm64
  # - engine/language_client_typescript/npm/darwin-x64
  # - engine/language_client_typescript/npm/linux-arm64-gmu
  # - engine/language_client_typescript/npm/linux-arm64-musl
  # - engine/language_client_typescript/npm/linux-x64-gnu
  # - engine/language_client_typescript/npm/linux-x64-musl
  # - engine/language_client_typescript/npm/win32-x64-msvc
