[toolchain]
channel = "1.92.0"
components = [
  "rustfmt",
  "clippy",
  "rust-analyzer",
  "rust-src",
  "llvm-tools-preview",
]
profile = "default"
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-musl"]
