# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from baml_lib._impl.deserializer import register_deserializer
from pydantic import BaseModel
from typing import Optional


@register_deserializer({  })
class ZenfetchBotDocumentBase(BaseModel):
    title: Optional[str] = None
    topic: Optional[str] = None
    @property
    def display(self) -> str:
        return f""" 
        #### Document:
            - Title: {self.title}
            - Topic: {self.topic}
            - Text: {self.text}
            - Author: {self.author}
            - URL: {self.raw_url}
            - Date Created: {self.date_created}
        """.strip()
