# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.enums.enm_intent import Intent
from baml_lib._impl.functions import BaseBAMLFunction
from typing import Protocol, runtime_checkable


IClassifyIntentOutput = Intent

@runtime_checkable
class IClassifyIntent(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        Intent
    """

    async def __call__(self, arg: str, /) -> Intent:
        ...


class IBAMLClassifyIntent(BaseBAMLFunction[Intent]):
    def __init__(self) -> None:
        super().__init__(
            "ClassifyIntent",
            IClassifyIntent,
            ["version1", "version2", "version3"],
        )

    async def __call__(self, *args, **kwargs) -> Intent:
        return await self.get_impl("version2").run(*args, **kwargs)

BAMLClassifyIntent = IBAMLClassifyIntent()

__all__ = [ "BAMLClassifyIntent" ]
