name: "Setup Ruby"
description: "Setup Ruby with optional version selection"

inputs:
  ruby-version:
    description: "Ruby version to install"
    required: false
    default: "3.4"

runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
