use std::{
    collections::BTreeSet,
    fmt::Write as _,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use clap::Parser;
use thiserror::Error;
use ungrammar::{Grammar, Rule};

type Result<T> = std::result::Result<T, CodegenError>;

#[derive(Debug, Error)]
enum CodegenError {
    #[error("failed to read {path}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to parse {path}: {message}")]
    Parse { path: PathBuf, message: String },
    #[error("failed to write {path}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("codegen crate must live under `baml_language/crates`")]
    InvalidWorkspaceLayout,
    #[error("{0} is stale; run `cargo run -p baml_compiler_codegen`")]
    Stale(PathBuf),
    #[error("failed to start rustfmt")]
    StartRustfmt(#[source] std::io::Error),
    #[error("failed to open rustfmt stdin")]
    OpenRustfmtStdin,
    #[error("failed to write generated source to rustfmt")]
    WriteRustfmtStdin(#[source] std::io::Error),
    #[error("failed to wait for rustfmt")]
    WaitForRustfmt(#[source] std::io::Error),
    #[error("rustfmt rejected generated source:\n{0}")]
    RustfmtRejected(String),
    #[error("rustfmt returned non-UTF-8 output")]
    RustfmtUtf8(#[source] std::string::FromUtf8Error),
    #[error("unknown grammar token `{0}`")]
    UnknownToken(String),
    #[error(transparent)]
    Format(#[from] std::fmt::Error),
}

#[derive(Parser)]
struct Args {
    /// Verify that checked-in generated files are current.
    #[arg(long)]
    check: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Cardinality {
    Required,
    Optional,
    Many,
}

struct NodeField {
    name: String,
    ty: String,
    cardinality: Cardinality,
}

struct TokenField {
    name: String,
    kinds: Vec<String>,
    cardinality: Cardinality,
}

enum Field {
    Node(NodeField),
    Token(TokenField),
}

struct NodeDef {
    name: String,
    fields: Vec<Field>,
}

struct EnumDef {
    name: String,
    variants: Vec<String>,
}

fn main() -> Result<()> {
    let args = Args::parse();
    let root = workspace_root()?;
    let grammar_path = root.join("crates/baml_compiler_syntax/baml.ungram");
    let grammar_source =
        fs::read_to_string(&grammar_path).map_err(|source| CodegenError::Read {
            path: grammar_path.clone(),
            source,
        })?;
    let grammar: Grammar =
        grammar_source
            .parse::<Grammar>()
            .map_err(|error| CodegenError::Parse {
                path: grammar_path.clone(),
                message: error.to_string(),
            })?;
    let files = [
        (
            root.join("crates/baml_compiler_syntax/src/ast/generated.rs"),
            generate(&grammar)?,
        ),
        (
            root.join("crates/baml_compiler_syntax/src/validated/generated_tokens.rs"),
            generate_tokens(&grammar)?,
        ),
        (
            root.join("crates/baml_compiler_syntax/src/validated/generated_schema.rs"),
            generate_schema(&grammar)?,
        ),
    ];

    for (output, generated) in files {
        update_file(&output, &generated, args.check)?;
    }

    Ok(())
}

fn update_file(path: &Path, generated: &str, check: bool) -> Result<()> {
    if check {
        if fs::read_to_string(path).unwrap_or_default() != generated {
            return Err(CodegenError::Stale(path.to_path_buf()));
        }
    } else {
        fs::write(path, generated).map_err(|source| CodegenError::Write {
            path: path.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .ok_or(CodegenError::InvalidWorkspaceLayout)
}

fn generate(grammar: &Grammar) -> Result<String> {
    let mut nodes = Vec::new();
    let mut enums = Vec::new();

    for node in grammar.iter() {
        let name = grammar[node].name.clone();
        if is_transparent_node(&name) {
            continue;
        }
        if let Some(variants) = enum_variants(grammar, &grammar[node].rule) {
            enums.push(EnumDef { name, variants });
        } else {
            let mut fields = Vec::new();
            lower_rule(
                grammar,
                &grammar[node].rule,
                None,
                Cardinality::Required,
                &mut fields,
            )?;
            deduplicate_fields(&mut fields);
            nodes.push(NodeDef { name, fields });
        }
    }

    let mut source = String::from(
        "// Generated by `cargo run -p baml_compiler_codegen`. Do not edit.\n\n\
         use rowan::ast::{support, AstChildren, AstNode};\n\n\
         use crate::{BamlLanguage, SyntaxElement, SyntaxKind, SyntaxNode, SyntaxToken};\n\n\
         use super::BamlAstNode;\n\n",
    );

    for node in &nodes {
        generate_node(node, &mut source)?;
    }
    for item in &enums {
        generate_enum(item, &mut source)?;
    }

    format_generated(&source)
}

fn generate_tokens(grammar: &Grammar) -> Result<String> {
    let mut source = String::from(
        "// Generated by `cargo run -p baml_compiler_codegen`. Do not edit.\n\n\
         use crate::{FromCST, KnownKind, StrongAstError, SyntaxElement, SyntaxKind, TextRange};\n\n\
         use super::ValidatedToken;\n\n",
    );
    let mut seen = BTreeSet::new();
    for token in grammar.tokens() {
        let text = &grammar[token].name;
        let name = token_type_name(text)?;
        if !seen.insert(name.clone()) {
            continue;
        }
        let kind = token_kind(text)?;
        writeln!(
            source,
            "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\npub struct {name} {{\n    pub token_span: TextRange,\n}}"
        )?;
        writeln!(
            source,
            "impl {name} {{\n    #[must_use]\n    pub const fn new(token_span: TextRange) -> Self {{ Self {{ token_span }} }}\n    #[must_use]\n    pub const fn new_from_span(token_span: TextRange) -> Self {{ Self::new(token_span) }}\n}}"
        )?;
        writeln!(
            source,
            "impl ValidatedToken for {name} {{\n    fn span(&self) -> TextRange {{ self.token_span }}\n}}"
        )?;
        writeln!(
            source,
            "impl KnownKind for {name} {{\n    fn kind() -> SyntaxKind {{ SyntaxKind::{kind} }}\n}}"
        )?;
        let kind_check = if name == "Word" {
            "if !super::is_word_like(token.kind()) {\n            return Err(StrongAstError::UnexpectedKind {\n                expected: SyntaxKind::WORD,\n                found: token.kind(),\n                at: token.text_range(),\n            });\n        }"
                .to_owned()
        } else {
            format!("StrongAstError::assert_kind_token(&token, SyntaxKind::{kind})?;")
        };
        writeln!(
            source,
            "impl FromCST for {name} {{\n    fn from_cst(element: SyntaxElement) -> Result<Self, StrongAstError> {{\n        let token = StrongAstError::assert_is_token(element)?;\n        {kind_check}\n        Ok(Self::new(token.text_range()))\n    }}\n}}"
        )?;
        if !text.starts_with('#') {
            writeln!(
                source,
                "impl std::fmt::Display for {name} {{\n    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str({text:?}) }}\n}}"
            )?;
        }
    }

    format_generated(&source)
}

fn generate_schema(grammar: &Grammar) -> Result<String> {
    let mut nodes = Vec::new();
    let mut enum_names = BTreeSet::new();
    for node in grammar.iter() {
        if is_transparent_node(&grammar[node].name) {
            continue;
        }
        if enum_variants(grammar, &grammar[node].rule).is_some() {
            enum_names.insert(grammar[node].name.clone());
            continue;
        }
        let mut fields = Vec::new();
        lower_rule(
            grammar,
            &grammar[node].rule,
            None,
            Cardinality::Required,
            &mut fields,
        )?;
        deduplicate_fields(&mut fields);
        nodes.push(NodeDef {
            name: grammar[node].name.clone(),
            fields,
        });
    }

    let mut source = String::from(
        "// Generated by `cargo run -p baml_compiler_codegen`. Do not edit.\n\n\
         #![allow(clippy::elidable_lifetime_names)]\n\n\
         use crate::{SyntaxKind, SyntaxNode, ast};\n\n\
         use super::{\n\
             StrongAstError,\n\
             arena::{ElementId, ElementRecord, Validated, ValidatedChildren, ValidatedSyntaxToken, element_is_node, element_kind},\n\
         };\n\n\
         #[derive(Debug)]\n\
         enum SchemaRule {\n\
             Any,\n\
             Node(&'static [SyntaxKind]),\n\
             Token(SyntaxKind),\n\
             Seq(&'static [SchemaRule]),\n\
             Alt(&'static [SchemaRule]),\n\
             Optional(&'static SchemaRule),\n\
             Repeated(&'static SchemaRule),\n\
             Capture { slot: usize, rule: &'static SchemaRule },\n\
         }\n\n\
         struct NodeSchema {\n\
             kind: SyntaxKind,\n\
             field_count: usize,\n\
             rule: &'static SchemaRule,\n\
         }\n\n",
    );

    for node in &nodes {
        let grammar_node = grammar
            .iter()
            .find(|candidate| grammar[*candidate].name == node.name)
            .expect("collected grammar node must still exist");
        let slots = node
            .fields
            .iter()
            .enumerate()
            .map(|(slot, field)| (field_name(field).to_owned(), slot))
            .collect::<std::collections::BTreeMap<_, _>>();
        let rule = schema_rule(
            grammar,
            &grammar[grammar_node].rule,
            None,
            &slots,
            &enum_names,
        )?;
        writeln!(
            source,
            "#[rustfmt::skip]\nconst RULE_{}: SchemaRule = {rule};",
            upper_snake_case(&node.name)
        )?;
    }

    writeln!(source, "\nconst SCHEMAS: &[NodeSchema] = &[")?;
    for node in &nodes {
        writeln!(
            source,
            "    NodeSchema {{ kind: SyntaxKind::{}, field_count: {}, rule: &RULE_{} }},",
            upper_snake_case(&node.name),
            node.fields.len(),
            upper_snake_case(&node.name)
        )?;
    }
    writeln!(source, "];\n")?;

    source.push_str(
        "#[derive(Clone)]\n\
         struct MatchState {\n\
             position: usize,\n\
             captures: Vec<Vec<ElementId>>,\n\
             matched: Vec<ElementId>,\n\
         }\n\n\
         fn apply_rule(\n\
             rule: &SchemaRule,\n\
             input: &[ElementId],\n\
             elements: &[ElementRecord],\n\
             state: MatchState,\n\
         ) -> Vec<MatchState> {\n\
             match rule {\n\
                 SchemaRule::Any => {\n\
                     let Some(element) = input.get(state.position) else { return Vec::new() };\n\
                     let mut state = state;\n\
                     state.position += 1;\n\
                     state.matched.push(*element);\n\
                     vec![state]\n\
                 }\n\
                 SchemaRule::Node(kinds) => {\n\
                     let Some(element) = input.get(state.position).filter(|element| {\n\
                         element_is_node(elements, **element) && kinds.contains(&element_kind(elements, **element))\n\
                     }) else { return Vec::new() };\n\
                     let mut state = state;\n\
                     state.position += 1;\n\
                     state.matched.push(*element);\n\
                     vec![state]\n\
                 }\n\
                 SchemaRule::Token(kind) => {\n\
                     let Some(element) = input.get(state.position).filter(|element| {\n\
                         !element_is_node(elements, **element) && element_kind(elements, **element) == *kind\n\
                     }) else { return Vec::new() };\n\
                     let mut state = state;\n\
                     state.position += 1;\n\
                     state.matched.push(*element);\n\
                     vec![state]\n\
                 }\n\
                 SchemaRule::Seq(rules) => rules.iter().fold(vec![state], |states, rule| {\n\
                     states\n\
                         .into_iter()\n\
                         .flat_map(|state| apply_rule(rule, input, elements, state))\n\
                         .collect()\n\
                 }),\n\
                 SchemaRule::Alt(rules) => rules\n\
                     .iter()\n\
                     .flat_map(|rule| apply_rule(rule, input, elements, state.clone()))\n\
                     .collect(),\n\
                 SchemaRule::Optional(rule) => {\n\
                     let mut states = apply_rule(rule, input, elements, state.clone());\n\
                     states.push(state);\n\
                     states\n\
                 }\n\
                 SchemaRule::Repeated(rule) => {\n\
                     let mut results = vec![state.clone()];\n\
                     let mut frontier = vec![state];\n\
                     while !frontier.is_empty() {\n\
                         let mut next = Vec::new();\n\
                         for state in frontier {\n\
                             for matched in apply_rule(rule, input, elements, state.clone()) {\n\
                                 if matched.position > state.position {\n\
                                     next.push(matched);\n\
                                 }\n\
                             }\n\
                         }\n\
                         results.extend(next.iter().cloned());\n\
                         frontier = next;\n\
                     }\n\
                     results.reverse();\n\
                     results\n\
                 }\n\
                 SchemaRule::Capture { slot, rule } => {\n\
                     let matched_start = state.matched.len();\n\
                     apply_rule(rule, input, elements, state)\n\
                         .into_iter()\n\
                         .map(|mut state| {\n\
                             state.captures[*slot].extend_from_slice(&state.matched[matched_start..]);\n\
                             state\n\
                         })\n\
                         .collect()\n\
                 }\n\
             }\n\
         }\n\n\
         pub(super) fn validate_node(\n\
             syntax: &SyntaxNode,\n\
             input: &[ElementId],\n\
             elements: &[ElementRecord],\n\
         ) -> Result<Vec<Vec<ElementId>>, StrongAstError> {\n\
             let Some(schema) = SCHEMAS.iter().find(|schema| schema.kind == syntax.kind()) else {\n\
                 return Ok(Vec::new());\n\
             };\n\
             let initial = MatchState {\n\
                 position: 0,\n\
                 captures: vec![Vec::new(); schema.field_count],\n\
                 matched: Vec::new(),\n\
             };\n\
             apply_rule(schema.rule, input, elements, initial)\n\
                 .into_iter()\n\
             .find(|state| state.position == input.len())\n\
                 .map(|state| state.captures)\n\
                 .ok_or(StrongAstError::InvalidStructure {\n\
                     kind: syntax.kind(),\n\
                     at: syntax.text_range(),\n\
                 })\n\
         }\n\n",
    );

    for node in &nodes {
        if node.fields.is_empty() {
            continue;
        }
        writeln!(
            source,
            "impl<'tree> Validated<'tree, ast::{}> {{",
            node.name
        )?;
        for (slot, field) in node.fields.iter().enumerate() {
            match field {
                Field::Node(field)
                    if field.ty == "AnyElement"
                        && matches!(field.cardinality, Cardinality::Many) =>
                {
                    writeln!(
                        source,
                        "    pub fn {}(&self) -> super::arena::ValidatedElements<'tree> {{ self.elements({slot}) }}",
                        field.name
                    )?;
                }
                Field::Node(field) if field.ty == "AnyElement" => {
                    writeln!(
                        source,
                        "    pub fn {}(&self) -> Option<super::arena::ValidatedElement<'tree>> {{ self.elements({slot}).next() }}",
                        field.name
                    )?;
                }
                Field::Node(field) if matches!(field.cardinality, Cardinality::Many) => writeln!(
                    source,
                    "    pub fn {}(&self) -> ValidatedChildren<'tree, ast::{}> {{ self.children({slot}) }}",
                    field.name, field.ty
                )?,
                Field::Node(field) if matches!(field.cardinality, Cardinality::Required) => {
                    writeln!(
                        source,
                        "    pub fn {}(&self) -> Validated<'tree, ast::{}> {{ self.child({slot}).expect(\"validated required field\") }}",
                        field.name, field.ty
                    )?;
                }
                Field::Node(field) => writeln!(
                    source,
                    "    pub fn {}(&self) -> Option<Validated<'tree, ast::{}>> {{ self.child({slot}) }}",
                    field.name, field.ty
                )?,
                Field::Token(field) if matches!(field.cardinality, Cardinality::Many) => {
                    let method = field.name.replace("_token", "_tokens");
                    writeln!(
                        source,
                        "    pub fn {method}(&self) -> impl Iterator<Item = ValidatedSyntaxToken> + 'tree {{ self.elements({slot}).filter_map(|element| element.token()) }}"
                    )?;
                }
                Field::Token(field) if matches!(field.cardinality, Cardinality::Required) => {
                    writeln!(
                        source,
                        "    pub fn {}(&self) -> ValidatedSyntaxToken {{ self.token({slot}).expect(\"validated required token\") }}",
                        field.name
                    )?;
                }
                Field::Token(field) => writeln!(
                    source,
                    "    pub fn {}(&self) -> Option<ValidatedSyntaxToken> {{ self.token({slot}) }}",
                    field.name
                )?,
            }
        }
        writeln!(source, "}}\n")?;
    }

    for item in grammar.iter().filter_map(|node| {
        let name = grammar[node].name.clone();
        enum_variants(grammar, &grammar[node].rule).map(|variants| EnumDef { name, variants })
    }) {
        writeln!(
            source,
            "#[derive(Debug, Clone, Copy)]\npub enum Validated{}<'tree> {{",
            item.name
        )?;
        for variant in &item.variants {
            writeln!(source, "    {variant}(Validated<'tree, ast::{variant}>),")?;
        }
        writeln!(source, "}}\n")?;
        writeln!(
            source,
            "impl<'tree> Validated<'tree, ast::{}> {{",
            item.name
        )?;
        writeln!(
            source,
            "    pub fn as_variant(self) -> Validated{}<'tree> {{",
            item.name
        )?;
        writeln!(source, "        match self.syntax().kind() {{")?;
        for variant in &item.variants {
            writeln!(
                source,
                "            SyntaxKind::{} => Validated{}::{variant}(self.cast().expect(\"validated enum variant\")),",
                upper_snake_case(variant),
                item.name
            )?;
        }
        writeln!(
            source,
            "            _ => unreachable!(\"validated enum kind\"),"
        )?;
        writeln!(source, "        }}\n    }}\n}}\n")?;
    }

    format_generated(&source)
}

fn field_name(field: &Field) -> &str {
    match field {
        Field::Node(field) => &field.name,
        Field::Token(field) => &field.name,
    }
}

fn is_transparent_node(name: &str) -> bool {
    name == "AnyElement"
}

fn schema_rule(
    grammar: &Grammar,
    rule: &Rule,
    label: Option<&str>,
    slots: &std::collections::BTreeMap<String, usize>,
    enum_names: &BTreeSet<String>,
) -> Result<String> {
    let (inner, field) = match rule {
        Rule::Node(node) => {
            let name = &grammar[*node].name;
            if is_transparent_node(name) {
                let field = label.map(str::to_owned).unwrap_or_else(|| snake_case(name));
                return Ok(slots.get(&field).map_or_else(
                    || "SchemaRule::Any".to_owned(),
                    |slot| {
                        format!("SchemaRule::Capture {{ slot: {slot}, rule: &SchemaRule::Any }}")
                    },
                ));
            }
            let kinds = if enum_names.contains(name) {
                enum_variants(grammar, &grammar[*node].rule)
                    .expect("enum name must have variants")
                    .into_iter()
                    .map(|variant| format!("SyntaxKind::{}", upper_snake_case(&variant)))
                    .collect::<Vec<_>>()
            } else {
                vec![format!("SyntaxKind::{}", upper_snake_case(name))]
            };
            (
                format!("SchemaRule::Node(&[{}])", kinds.join(", ")),
                Some(label.map(str::to_owned).unwrap_or_else(|| snake_case(name))),
            )
        }
        Rule::Token(token) => {
            let text = &grammar[*token].name;
            (
                format!("SchemaRule::Token(SyntaxKind::{})", token_kind(text)?),
                Some(
                    label
                        .map(str::to_owned)
                        .unwrap_or_else(|| token_method_name(text)),
                ),
            )
        }
        Rule::Seq(rules) => (
            format!(
                "SchemaRule::Seq(&[{}])",
                rules
                    .iter()
                    .map(|rule| schema_rule(grammar, rule, label, slots, enum_names))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ")
            ),
            None,
        ),
        Rule::Alt(rules) => (
            format!(
                "SchemaRule::Alt(&[{}])",
                rules
                    .iter()
                    .map(|rule| schema_rule(grammar, rule, label, slots, enum_names))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ")
            ),
            None,
        ),
        Rule::Opt(inner) => (
            format!(
                "SchemaRule::Optional(&{})",
                schema_rule(grammar, inner, label, slots, enum_names)?
            ),
            None,
        ),
        Rule::Rep(inner) => (
            format!(
                "SchemaRule::Repeated(&{})",
                schema_rule(grammar, inner, label, slots, enum_names)?
            ),
            None,
        ),
        Rule::Labeled { label, rule } => {
            return schema_rule(grammar, rule, Some(label), slots, enum_names);
        }
    };
    Ok(match field.and_then(|field| slots.get(&field).copied()) {
        Some(slot) => format!("SchemaRule::Capture {{ slot: {slot}, rule: &{inner} }}"),
        None => inner,
    })
}

fn format_generated(source: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args([
            "--edition",
            "2024",
            "--emit",
            "stdout",
            "--config",
            "imports_granularity=Crate,group_imports=StdExternalCrate",
        ])
        .current_dir(workspace_root()?)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(CodegenError::StartRustfmt)?;
    child
        .stdin
        .take()
        .ok_or(CodegenError::OpenRustfmtStdin)?
        .write_all(source.as_bytes())
        .map_err(CodegenError::WriteRustfmtStdin)?;
    let output = child
        .wait_with_output()
        .map_err(CodegenError::WaitForRustfmt)?;
    if !output.status.success() {
        return Err(CodegenError::RustfmtRejected(
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ));
    }
    String::from_utf8(output.stdout).map_err(CodegenError::RustfmtUtf8)
}

fn enum_variants(grammar: &Grammar, rule: &Rule) -> Option<Vec<String>> {
    let Rule::Alt(alternatives) = rule else {
        return None;
    };
    let mut variants = Vec::new();
    for alternative in alternatives {
        let Rule::Node(node) = alternative else {
            return None;
        };
        if let Some(nested) = enum_variants(grammar, &grammar[*node].rule) {
            variants.extend(nested);
        } else {
            variants.push(grammar[*node].name.clone());
        }
    }
    Some(variants)
}

fn lower_rule(
    grammar: &Grammar,
    rule: &Rule,
    label: Option<&str>,
    cardinality: Cardinality,
    fields: &mut Vec<Field>,
) -> Result<()> {
    match rule {
        Rule::Node(node) => {
            let ty = grammar[*node].name.clone();
            fields.push(Field::Node(NodeField {
                name: label.map(str::to_owned).unwrap_or_else(|| snake_case(&ty)),
                ty,
                cardinality,
            }));
        }
        Rule::Token(token) => {
            let text = &grammar[*token].name;
            fields.push(Field::Token(TokenField {
                name: label
                    .map(str::to_owned)
                    .unwrap_or_else(|| token_method_name(text)),
                kinds: vec![token_kind(text)?],
                cardinality,
            }));
        }
        Rule::Rep(inner) => {
            lower_rule(grammar, inner, label, Cardinality::Many, fields)?;
        }
        Rule::Labeled { label, rule } => {
            lower_rule(grammar, rule, Some(label), cardinality, fields)?;
        }
        Rule::Seq(rules) => {
            for rule in rules {
                lower_rule(grammar, rule, label, cardinality, fields)?;
            }
        }
        Rule::Alt(rules) => {
            if let Some(label) = label
                && rules.iter().all(|rule| matches!(rule, Rule::Token(_)))
            {
                let kinds = rules
                    .iter()
                    .map(|rule| match rule {
                        Rule::Token(token) => token_kind(&grammar[*token].name),
                        _ => unreachable!("checked token alternative"),
                    })
                    .collect::<Result<Vec<_>>>()?;
                fields.push(Field::Token(TokenField {
                    name: label.to_owned(),
                    kinds,
                    cardinality,
                }));
                return Ok(());
            }
            for rule in rules {
                lower_rule(
                    grammar,
                    rule,
                    label,
                    optional_cardinality(cardinality),
                    fields,
                )?;
            }
        }
        Rule::Opt(inner) => lower_rule(
            grammar,
            inner,
            label,
            optional_cardinality(cardinality),
            fields,
        )?,
    }
    Ok(())
}

fn optional_cardinality(cardinality: Cardinality) -> Cardinality {
    match cardinality {
        Cardinality::Many => Cardinality::Many,
        Cardinality::Required | Cardinality::Optional => Cardinality::Optional,
    }
}

fn deduplicate_fields(fields: &mut Vec<Field>) {
    let mut deduplicated = Vec::<Field>::new();
    for field in fields.drain(..) {
        let duplicate = deduplicated
            .iter_mut()
            .find(|existing| match (existing, &field) {
                (Field::Node(existing), Field::Node(field)) => {
                    existing.name == field.name && existing.ty == field.ty
                }
                (Field::Token(existing), Field::Token(field)) => {
                    existing.name == field.name && existing.kinds == field.kinds
                }
                _ => false,
            });
        if let Some(existing) = duplicate {
            let existing_cardinality = match existing {
                Field::Node(field) => &mut field.cardinality,
                Field::Token(field) => &mut field.cardinality,
            };
            let duplicate_cardinality = match &field {
                Field::Node(field) => field.cardinality,
                Field::Token(field) => field.cardinality,
            };
            *existing_cardinality = merge_cardinality(*existing_cardinality, duplicate_cardinality);
        } else {
            let name = match &field {
                Field::Node(field) => &field.name,
                Field::Token(field) => &field.name,
            };
            if !deduplicated.iter().any(|existing| match existing {
                Field::Node(existing) => existing.name == *name,
                Field::Token(existing) => existing.name == *name,
            }) {
                deduplicated.push(field);
            }
        }
    }
    *fields = deduplicated;
}

const fn merge_cardinality(left: Cardinality, right: Cardinality) -> Cardinality {
    match (left, right) {
        (Cardinality::Many, _) | (_, Cardinality::Many) => Cardinality::Many,
        (Cardinality::Required, Cardinality::Required) => Cardinality::Many,
        (Cardinality::Required, _) | (_, Cardinality::Required) => Cardinality::Required,
        (Cardinality::Optional, Cardinality::Optional) => Cardinality::Optional,
    }
}

fn generate_node(node: &NodeDef, source: &mut String) -> Result<()> {
    let kind = upper_snake_case(&node.name);
    writeln!(
        source,
        "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\npub struct {} {{\n    pub(super) syntax: SyntaxNode,\n}}",
        node.name
    )?;
    writeln!(source, "\nimpl BamlAstNode for {} {{}}", node.name)?;
    writeln!(source, "\nimpl AstNode for {} {{", node.name)?;
    writeln!(source, "    type Language = BamlLanguage;")?;
    writeln!(
        source,
        "    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{kind} }}"
    )?;
    writeln!(
        source,
        "    fn cast(syntax: SyntaxNode) -> Option<Self> {{ Self::can_cast(syntax.kind()).then_some(Self {{ syntax }}) }}"
    )?;
    writeln!(
        source,
        "    fn syntax(&self) -> &SyntaxNode {{ &self.syntax }}\n}}"
    )?;

    if !node.fields.is_empty() {
        writeln!(source, "\nimpl {} {{", node.name)?;
        for field in &node.fields {
            let field_name = match field {
                Field::Node(field) => &field.name,
                Field::Token(field) => &field.name,
            };
            if is_handwritten_accessor(&node.name, field_name) {
                continue;
            }
            match field {
                Field::Node(field) if field.ty == "AnyElement" => {
                    if matches!(field.cardinality, Cardinality::Many) {
                        writeln!(
                            source,
                            "    pub fn {}(&self) -> impl Iterator<Item = SyntaxElement> + '_ {{ self.syntax.children_with_tokens().filter(|element| !element.kind().is_trivia()) }}",
                            field.name
                        )?;
                    } else {
                        writeln!(
                            source,
                            "    pub fn {}(&self) -> Option<SyntaxElement> {{ self.syntax.children_with_tokens().find(|element| !element.kind().is_trivia()) }}",
                            field.name
                        )?;
                    }
                }
                Field::Node(field) => {
                    if matches!(field.cardinality, Cardinality::Many) {
                        writeln!(
                            source,
                            "    pub fn {}(&self) -> AstChildren<{}> {{ support::children(&self.syntax) }}",
                            field.name, field.ty
                        )?;
                    } else {
                        writeln!(
                            source,
                            "    pub fn {}(&self) -> Option<{}> {{ support::child(&self.syntax) }}",
                            field.name, field.ty
                        )?;
                    }
                }
                Field::Token(field) if matches!(field.cardinality, Cardinality::Many) => {
                    let method = field.name.replace("_token", "_tokens");
                    writeln!(
                        source,
                        "    pub fn {method}(&self) -> impl Iterator<Item = SyntaxToken> + '_ {{ self.syntax.children_with_tokens().filter_map(rowan::NodeOrToken::into_token).filter(|token| matches!(token.kind(), {})) }}",
                        field
                            .kinds
                            .iter()
                            .map(|kind| format!("SyntaxKind::{kind}"))
                            .collect::<Vec<_>>()
                            .join(" | ")
                    )?;
                }
                Field::Token(field) => writeln!(
                    source,
                    "    pub fn {}(&self) -> Option<SyntaxToken> {{ self.syntax.children_with_tokens().filter_map(rowan::NodeOrToken::into_token).find(|token| matches!(token.kind(), {})) }}",
                    field.name,
                    field
                        .kinds
                        .iter()
                        .map(|kind| format!("SyntaxKind::{kind}"))
                        .collect::<Vec<_>>()
                        .join(" | ")
                )?,
            }
        }
        writeln!(source, "}}")?;
    }
    writeln!(source)?;
    Ok(())
}

fn is_handwritten_accessor(node: &str, field: &str) -> bool {
    matches!(
        (node, field),
        ("FunctionDef" | "MethodSig", "throws_clause")
            | ("InterfaceDef", "requires_clause")
            | ("ClientDef" | "TestDef" | "RetryPolicyDef", "config_block")
            | ("TypeExpr", "type_args" | "string_literal")
            | (
                "ThrowsClause" | "ImplementsTarget" | "ImplementsForTarget",
                "type_expr"
            )
            | (
                "LlmFunctionBody",
                "client_field" | "prompt_field" | "tools_field"
            )
            | ("ClientField" | "PromptField", "value")
            | ("SpecExpr", "base")
            | ("AssociatedTypeDecl", "bound")
            | ("InterfaceFieldLink", "interface_field" | "class_field")
            | ("ConfigItem", "config_value")
    )
}

fn generate_enum(item: &EnumDef, source: &mut String) -> Result<()> {
    writeln!(
        source,
        "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\npub enum {} {{",
        item.name
    )?;
    for variant in &item.variants {
        writeln!(source, "    {variant}({variant}),")?;
    }
    writeln!(source, "}}")?;
    writeln!(source, "\nimpl AstNode for {} {{", item.name)?;
    writeln!(source, "    type Language = BamlLanguage;")?;
    write!(
        source,
        "    fn can_cast(kind: SyntaxKind) -> bool {{ matches!(kind, "
    )?;
    for (index, variant) in item.variants.iter().enumerate() {
        if index > 0 {
            write!(source, " | ")?;
        }
        write!(source, "SyntaxKind::{}", upper_snake_case(variant))?;
    }
    writeln!(source, ") }}")?;
    writeln!(source, "    fn cast(syntax: SyntaxNode) -> Option<Self> {{")?;
    writeln!(source, "        match syntax.kind() {{")?;
    for variant in &item.variants {
        writeln!(
            source,
            "            SyntaxKind::{} => Some(Self::{variant}({variant} {{ syntax }})),",
            upper_snake_case(variant)
        )?;
    }
    writeln!(source, "            _ => None,\n        }}\n    }}")?;
    writeln!(source, "    fn syntax(&self) -> &SyntaxNode {{")?;
    writeln!(source, "        match self {{")?;
    for variant in &item.variants {
        writeln!(
            source,
            "            Self::{variant}(node) => node.syntax(),"
        )?;
    }
    writeln!(source, "        }}\n    }}\n}}")?;
    for variant in &item.variants {
        writeln!(
            source,
            "\nimpl From<{variant}> for {} {{\n    fn from(node: {variant}) -> Self {{ Self::{variant}(node) }}\n}}",
            item.name
        )?;
    }
    writeln!(source)?;
    Ok(())
}

fn token_kind(token: &str) -> Result<String> {
    let kind = match token {
        "#word" => "WORD",
        "#integer" => "INTEGER_LITERAL",
        "#float" => "FLOAT_LITERAL",
        "#bigint" => "BIGINT_LITERAL",
        "#error" => "ERROR_TOKEN",
        "\"" => "QUOTE",
        "#" => "HASH",
        "`" => "BACKTICK",
        "{" => "L_BRACE",
        "}" => "R_BRACE",
        "(" => "L_PAREN",
        ")" => "R_PAREN",
        "[" => "L_BRACKET",
        "]" => "R_BRACKET",
        ":" => "COLON",
        "::" => "DOUBLE_COLON",
        "," => "COMMA",
        ";" => "SEMICOLON",
        "..." => "DOT_DOT_DOT",
        ".." => "DOT_DOT",
        "." => "DOT",
        "$" => "DOLLAR",
        "->" => "ARROW",
        "=>" => "FAT_ARROW",
        "@" => "AT",
        "@@" => "AT_AT",
        "|" => "PIPE",
        "?." => "QUESTION_DOT",
        "??" => "QUESTION_QUESTION",
        "?" => "QUESTION",
        "=" => "EQUALS",
        "+=" => "PLUS_EQUALS",
        "-=" => "MINUS_EQUALS",
        "*=" => "STAR_EQUALS",
        "/=" => "SLASH_EQUALS",
        "%=" => "PERCENT_EQUALS",
        "&=" => "AND_EQUALS",
        "|=" => "PIPE_EQUALS",
        "^=" => "CARET_EQUALS",
        "<<=" => "LESS_LESS_EQUALS",
        ">>=" => "GREATER_GREATER_EQUALS",
        "==" => "EQUALS_EQUALS",
        "!=" => "NOT_EQUALS",
        "<" => "LESS",
        ">" => "GREATER",
        "<=" => "LESS_EQUALS",
        ">=" => "GREATER_EQUALS",
        "&&" => "AND_AND",
        "||" => "OR_OR",
        "!" => "NOT",
        "&" => "AND",
        "^" => "CARET",
        "~" => "TILDE",
        "<<" => "LESS_LESS",
        ">>" => "GREATER_GREATER",
        "+" => "PLUS",
        "-" => "MINUS",
        "*" => "STAR",
        "/" => "SLASH",
        "%" => "PERCENT",
        "++" => "PLUS_PLUS",
        "--" => "MINUS_MINUS",
        "\\" => "BACKSLASH",
        keyword
            if keyword
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '_') =>
        {
            return Ok(format!("KW_{}", keyword.to_ascii_uppercase()));
        }
        _ => return Err(CodegenError::UnknownToken(token.to_owned())),
    };
    Ok(kind.to_owned())
}

fn token_type_name(token: &str) -> Result<String> {
    let name = match token {
        "#word" => "Word",
        "#integer" => "IntegerLiteral",
        "#float" => "FloatLiteral",
        "#bigint" => "BigintLiteral",
        "#error" => "ErrorToken",
        "\"" => "Quote",
        "#" => "Hash",
        "`" => "Backtick",
        "{" => "LBrace",
        "}" => "RBrace",
        "(" => "LParen",
        ")" => "RParen",
        "[" => "LBracket",
        "]" => "RBracket",
        ":" => "Colon",
        "::" => "DoubleColon",
        "," => "Comma",
        ";" => "Semicolon",
        "..." => "DotDotDot",
        ".." => "DotDot",
        "." => "Dot",
        "$" => "Dollar",
        "->" => "Arrow",
        "=>" => "FatArrow",
        "@" => "At",
        "@@" => "AtAt",
        "|" => "Pipe",
        "?." => "QuestionDot",
        "??" => "QuestionQuestion",
        "?" => "Question",
        "=" => "Equals",
        "+=" => "PlusEquals",
        "-=" => "MinusEquals",
        "*=" => "StarEquals",
        "/=" => "SlashEquals",
        "%=" => "PercentEquals",
        "&=" => "AndEquals",
        "|=" => "PipeEquals",
        "^=" => "CaretEquals",
        "<<=" => "LessLessEquals",
        ">>=" => "GreaterGreaterEquals",
        "==" => "EqualsEquals",
        "!=" => "NotEquals",
        "<" => "Less",
        ">" => "Greater",
        "<=" => "LessEquals",
        ">=" => "GreaterEquals",
        "&&" => "AndAnd",
        "||" => "OrOr",
        "!" => "Not",
        "&" => "And",
        "^" => "Caret",
        "~" => "Tilde",
        "<<" => "LessLess",
        ">>" => "GreaterGreater",
        "+" => "Plus",
        "-" => "Minus",
        "*" => "Star",
        "/" => "Slash",
        "%" => "Percent",
        "++" => "PlusPlus",
        "--" => "MinusMinus",
        "\\" => "Backslash",
        "type" => "TypeKw",
        "testset" => "TestSet",
        keyword
            if keyword
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '_') =>
        {
            return Ok(pascal_case(keyword));
        }
        _ => return Err(CodegenError::UnknownToken(token.to_owned())),
    };
    Ok(name.to_owned())
}

fn token_method_name(token: &str) -> String {
    let name = match token {
        "#word" => "word",
        "#integer" => "integer",
        "#float" => "float",
        "#bigint" => "bigint",
        "#error" => "error",
        "\"" => "quote",
        "#" => "hash",
        "`" => "backtick",
        "{" => "l_brace",
        "}" => "r_brace",
        "(" => "l_paren",
        ")" => "r_paren",
        "[" => "l_bracket",
        "]" => "r_bracket",
        ":" => "colon",
        "::" => "double_colon",
        "," => "comma",
        ";" => "semicolon",
        "..." => "dot_dot_dot",
        ".." => "dot_dot",
        "." => "dot",
        "$" => "dollar",
        "->" => "arrow",
        "=>" => "fat_arrow",
        "@" => "at",
        "@@" => "at_at",
        "|" => "pipe",
        "?." => "question_dot",
        "??" => "question_question",
        "?" => "question",
        "=" => "equals",
        "+=" => "plus_equals",
        "-=" => "minus_equals",
        "*=" => "star_equals",
        "/=" => "slash_equals",
        "%=" => "percent_equals",
        "&=" => "and_equals",
        "|=" => "pipe_equals",
        "^=" => "caret_equals",
        "<<=" => "less_less_equals",
        ">>=" => "greater_greater_equals",
        "==" => "equals_equals",
        "!=" => "not_equals",
        "<" => "less",
        ">" => "greater",
        "<=" => "less_equals",
        ">=" => "greater_equals",
        "&&" => "and_and",
        "||" => "or_or",
        "!" => "not",
        "&" => "and",
        "^" => "caret",
        "~" => "tilde",
        "<<" => "less_less",
        ">>" => "greater_greater",
        "+" => "plus",
        "-" => "minus",
        "*" => "star",
        "/" => "slash",
        "%" => "percent",
        "++" => "plus_plus",
        "--" => "minus_minus",
        "\\" => "backslash",
        keyword => keyword,
    };
    format!("{name}_token")
}

fn snake_case(name: &str) -> String {
    let mut result = String::new();
    let chars = name.chars().collect::<Vec<_>>();
    for (index, character) in chars.iter().copied().enumerate() {
        let previous_is_lower = index > 0 && chars[index - 1].is_ascii_lowercase();
        let next_is_lower = chars.get(index + 1).is_some_and(char::is_ascii_lowercase);
        if character.is_ascii_uppercase() && index > 0 && (previous_is_lower || next_is_lower) {
            result.push('_');
        }
        result.push(character.to_ascii_lowercase());
    }
    result
}

fn upper_snake_case(name: &str) -> String {
    snake_case(name).to_ascii_uppercase()
}

fn pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            match characters.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + characters.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn case_conversion_preserves_acronyms() {
        assert_eq!(upper_snake_case("LlmFunctionBody"), "LLM_FUNCTION_BODY");
        assert_eq!(upper_snake_case("IfExpr"), "IF_EXPR");
    }

    #[test]
    fn optional_rules_preserve_repetition() {
        assert_eq!(optional_cardinality(Cardinality::Many), Cardinality::Many);
        assert_eq!(
            optional_cardinality(Cardinality::Required),
            Cardinality::Optional
        );
    }

    #[test]
    fn duplicate_fields_preserve_repetition() {
        assert_eq!(
            merge_cardinality(Cardinality::Required, Cardinality::Many),
            Cardinality::Many
        );
        assert_eq!(
            merge_cardinality(Cardinality::Required, Cardinality::Required),
            Cardinality::Many
        );
    }
}
