[package]
name = "baml_artifact"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
build = "build.rs"

[lints]
workspace = true

[dependencies]
baml_base = { workspace = true }
baml_package_interface = { workspace = true }
bex_vm_types = { workspace = true }
borsh = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
sha2 = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
rustc-hash = { workspace = true }
