[package]
name = "baml_stdlib_artifacts"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
build = "build.rs"

[lints]
workspace = true

[dependencies]
baml_artifact = { workspace = true }
baml_base = { workspace = true }
baml_package_interface = { workspace = true }
bex_vm_types = { workspace = true }

[build-dependencies]
baml_artifact = { workspace = true }
baml_base = { workspace = true }
baml_builtins2 = { workspace = true }
baml_compiler2_emit = { workspace = true }
baml_compiler2_hir = { workspace = true }
baml_compiler2_hir_ty = { workspace = true }
baml_package_interface = { workspace = true }
baml_project = { workspace = true }
borsh = { workspace = true }
