# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from __future__ import annotations

import typing
import pydantic

from ... import baml

if typing.TYPE_CHECKING:
    from ... import lorem


class Address(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    street: typing.Union[str, None]
    city: typing.Union[str, None]
    zip: typing.Union[str, None]


class Bar(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    their_pdf: baml.media.Pdf
    their_image: baml.media.Image
    name: typing.Literal["bar"]


class Box(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    item: typing.Union[None, None]


class Foo(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: typing.Literal["foo"]
    my_pdf: baml.media.Pdf
    my_image: baml.media.Image


class PhoneNumber(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    country_code: typing.Union[int, None]
    digits: typing.Union[str, None]


class Resume(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="forbid")
    name: typing.Union[str, None]
    email: typing.Union[str, None]
    addresses: typing.List[Address]
    scores: typing.Dict[str, int]
    sentiment: typing.Union[lorem.Sentiment, None]
    contact: typing.Union[PhoneNumber, None]


__all__ = [
    "Address",
    "Bar",
    "Box",
    "Foo",
    "PhoneNumber",
    "Resume",
]
