[project]
name = "baml_core_ffi"
version = "0.1.0"
description = "BAML python bindings (pyproject.toml)"
readme = "README.md"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]
