# Can't use these in a stable toolchain, only through CLI:

# cargo fmt -- --config imports_granularity="Crate" --config group_imports="StdExternalCrate" --config overflow_delimited_expr=true

# unstable_features = true

# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# overflow_delimited_expr = true
