// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ClassWithBlockDoneClassView struct {
	inner baml.ClassBuilder
}

func (t *ClassWithBlockDoneClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ClassWithBlockDoneClassView) I_16_digits() (ClassPropertyView, error) {
	return t.inner.Property("i_16_digits")
}

func (t *ClassWithBlockDoneClassView) S_20_words() (ClassPropertyView, error) {
	return t.inner.Property("s_20_words")
}

func (t *TypeBuilder) ClassWithBlockDone() (*ClassWithBlockDoneClassView, error) {
	bld, err := t.inner.Class("ClassWithBlockDone")
	if err != nil {
		return nil, err
	}
	return &ClassWithBlockDoneClassView{inner: bld}, nil
}

type ClassWithoutDoneClassView struct {
	inner baml.ClassBuilder
}

func (t *ClassWithoutDoneClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ClassWithoutDoneClassView) I_16_digits() (ClassPropertyView, error) {
	return t.inner.Property("i_16_digits")
}

func (t *ClassWithoutDoneClassView) S_20_words() (ClassPropertyView, error) {
	return t.inner.Property("s_20_words")
}

func (t *TypeBuilder) ClassWithoutDone() (*ClassWithoutDoneClassView, error) {
	bld, err := t.inner.Class("ClassWithoutDone")
	if err != nil {
		return nil, err
	}
	return &ClassWithoutDoneClassView{inner: bld}, nil
}

type SemanticContainerClassView struct {
	inner baml.ClassBuilder
}

func (t *SemanticContainerClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SemanticContainerClassView) Sixteen_digit_number() (ClassPropertyView, error) {
	return t.inner.Property("sixteen_digit_number")
}

func (t *SemanticContainerClassView) String_with_twenty_words() (ClassPropertyView, error) {
	return t.inner.Property("string_with_twenty_words")
}

func (t *SemanticContainerClassView) Class_1() (ClassPropertyView, error) {
	return t.inner.Property("class_1")
}

func (t *SemanticContainerClassView) Class_2() (ClassPropertyView, error) {
	return t.inner.Property("class_2")
}

func (t *SemanticContainerClassView) Class_done_needed() (ClassPropertyView, error) {
	return t.inner.Property("class_done_needed")
}

func (t *SemanticContainerClassView) Class_needed() (ClassPropertyView, error) {
	return t.inner.Property("class_needed")
}

func (t *SemanticContainerClassView) Three_small_things() (ClassPropertyView, error) {
	return t.inner.Property("three_small_things")
}

func (t *SemanticContainerClassView) Final_string() (ClassPropertyView, error) {
	return t.inner.Property("final_string")
}

func (t *TypeBuilder) SemanticContainer() (*SemanticContainerClassView, error) {
	bld, err := t.inner.Class("SemanticContainer")
	if err != nil {
		return nil, err
	}
	return &SemanticContainerClassView{inner: bld}, nil
}

type SmallThingClassView struct {
	inner baml.ClassBuilder
}

func (t *SmallThingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SmallThingClassView) I_16_digits() (ClassPropertyView, error) {
	return t.inner.Property("i_16_digits")
}

func (t *SmallThingClassView) I_8_digits() (ClassPropertyView, error) {
	return t.inner.Property("i_8_digits")
}

func (t *TypeBuilder) SmallThing() (*SmallThingClassView, error) {
	bld, err := t.inner.Class("SmallThing")
	if err != nil {
		return nil, err
	}
	return &SmallThingClassView{inner: bld}, nil
}
