// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use super::*;
use crate::baml_client::types;
use baml::{BamlDecode, __internal::serde::Serialize};

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Admin {
    pub id: Option<i64>,

    pub name: Option<String>,

    pub permissions: Vec<String>,

    #[baml(name = "type")]
    pub r#type: Option<String>,
}

impl ::std::convert::AsRef<Admin> for Admin {
    fn as_ref(&self) -> &Admin {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ApiError {
    pub status: Option<String>,

    pub message: Option<String>,

    pub code: Option<i64>,
}

impl ::std::convert::AsRef<ApiError> for ApiError {
    fn as_ref(&self) -> &ApiError {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ApiPending {
    pub status: Option<String>,

    pub progress: Option<f64>,

    pub eta: Option<i64>,
}

impl ::std::convert::AsRef<ApiPending> for ApiPending {
    fn as_ref(&self) -> &ApiPending {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ApiSuccess {
    pub status: Option<String>,

    pub data: std::collections::HashMap<String, String>,
}

impl ::std::convert::AsRef<ApiSuccess> for ApiSuccess {
    fn as_ref(&self) -> &ApiSuccess {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Bird {
    pub species: Option<String>,

    pub canFly: Option<bool>,

    pub wingspan: Option<f64>,
}

impl ::std::convert::AsRef<Bird> for Bird {
    fn as_ref(&self) -> &Bird {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Cat {
    pub species: Option<String>,

    pub color: Option<String>,

    pub lives: Option<i64>,
}

impl ::std::convert::AsRef<Cat> for Cat {
    fn as_ref(&self) -> &Cat {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Circle {
    pub shape: Option<String>,

    pub radius: Option<f64>,
}

impl ::std::convert::AsRef<Circle> for Circle {
    fn as_ref(&self) -> &Circle {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ComplexUnions {
    pub userOrProduct: Option<Union2ProductOrUser>,

    pub userOrProductOrAdmin: Option<Union3AdminOrProductOrUser>,

    pub dataOrError: Option<Union2DataResponseOrErrorResponse>,

    pub resultOrNull: Option<Result>,

    pub multiTypeResult: Option<Union3ErrorOrSuccessOrWarning>,
}

impl ::std::convert::AsRef<ComplexUnions> for ComplexUnions {
    fn as_ref(&self) -> &ComplexUnions {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DataResponse {
    pub data: Option<String>,

    pub timestamp: Option<i64>,

    pub status: Option<String>,
}

impl ::std::convert::AsRef<DataResponse> for DataResponse {
    fn as_ref(&self) -> &DataResponse {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DiscriminatedUnions {
    pub shape: Option<Union3CircleOrRectangleOrTriangle>,

    pub animal: Option<Union3BirdOrCatOrDog>,

    pub response: Option<Union3ApiErrorOrApiPendingOrApiSuccess>,
}

impl ::std::convert::AsRef<DiscriminatedUnions> for DiscriminatedUnions {
    fn as_ref(&self) -> &DiscriminatedUnions {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Dog {
    pub species: Option<String>,

    pub breed: Option<String>,

    pub goodBoy: Option<bool>,
}

impl ::std::convert::AsRef<Dog> for Dog {
    fn as_ref(&self) -> &Dog {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Error {
    #[baml(name = "type")]
    pub r#type: Option<String>,

    pub message: Option<String>,

    pub code: Option<i64>,

    pub details: Option<String>,
}

impl ::std::convert::AsRef<Error> for Error {
    fn as_ref(&self) -> &Error {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ErrorResponse {
    pub error: Option<String>,

    pub code: Option<i64>,

    pub status: Option<String>,
}

impl ::std::convert::AsRef<ErrorResponse> for ErrorResponse {
    fn as_ref(&self) -> &ErrorResponse {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PrimitiveUnions {
    pub stringOrInt: Option<types::Union2IntOrString>,

    pub stringOrFloat: Option<types::Union2FloatOrString>,

    pub intOrFloat: Option<types::Union2FloatOrInt>,

    pub boolOrString: Option<types::Union2BoolOrString>,

    pub anyPrimitive: Option<types::Union4BoolOrFloatOrIntOrString>,
}

impl ::std::convert::AsRef<PrimitiveUnions> for PrimitiveUnions {
    fn as_ref(&self) -> &PrimitiveUnions {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Product {
    pub id: Option<i64>,

    pub name: Option<String>,

    pub price: Option<f64>,

    #[baml(name = "type")]
    pub r#type: Option<String>,
}

impl ::std::convert::AsRef<Product> for Product {
    fn as_ref(&self) -> &Product {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Rectangle {
    pub shape: Option<String>,

    pub width: Option<f64>,

    pub height: Option<f64>,
}

impl ::std::convert::AsRef<Rectangle> for Rectangle {
    fn as_ref(&self) -> &Rectangle {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RecursiveUnion {
    pub value: Option<Union3IntOrRecursiveUnionOrString>,

    pub children: Vec<Union2RecursiveUnionOrString>,
}

impl ::std::convert::AsRef<RecursiveUnion> for RecursiveUnion {
    fn as_ref(&self) -> &RecursiveUnion {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Result {
    pub value: Option<types::Union3FloatOrIntOrString>,

    pub metadata: std::collections::HashMap<String, String>,
}

impl ::std::convert::AsRef<Result> for Result {
    fn as_ref(&self) -> &Result {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Success {
    #[baml(name = "type")]
    pub r#type: Option<String>,

    pub message: Option<String>,

    pub data: std::collections::HashMap<String, String>,
}

impl ::std::convert::AsRef<Success> for Success {
    fn as_ref(&self) -> &Success {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Triangle {
    pub shape: Option<String>,

    pub base: Option<f64>,

    pub height: Option<f64>,
}

impl ::std::convert::AsRef<Triangle> for Triangle {
    fn as_ref(&self) -> &Triangle {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct UnionArrays {
    pub mixedArray: Vec<types::Union2IntOrString>,

    pub nullableItems: Vec<Option<String>>,

    pub objectArray: Vec<Union2ProductOrUser>,

    pub nestedUnionArray: Vec<types::Union2ListIntOrString>,
}

impl ::std::convert::AsRef<UnionArrays> for UnionArrays {
    fn as_ref(&self) -> &UnionArrays {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct User {
    pub id: Option<i64>,

    pub name: Option<String>,

    #[baml(name = "type")]
    pub r#type: Option<String>,
}

impl ::std::convert::AsRef<User> for User {
    fn as_ref(&self) -> &User {
        self
    }
}

#[derive(Debug, Clone, Default, BamlDecode, Serialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct Warning {
    #[baml(name = "type")]
    pub r#type: Option<String>,

    pub message: Option<String>,

    pub level: Option<i64>,
}

impl ::std::convert::AsRef<Warning> for Warning {
    fn as_ref(&self) -> &Warning {
        self
    }
}
