[package]
name = "bex_sap"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
baml_type = { workspace = true }
bex_external_types = { workspace = true }
bex_vm_types = { workspace = true }
sys_types = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
ouroboros = { workspace = true }
regex = { workspace = true }
rowan = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strsim = { workspace = true }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }

[features]
## Enables manual `TypeRefDb` construction. Otherwise, we should construct from [`sys_types::SysOpContext`] via `TypeCtx`.
manual_db = [  ]
