//! Swift SDK generator for BAML.
//!
//! Mirrors `sdkgen_python_pydantic2`'s public entry point: consumes a
//! [`baml_codegen_types::SymbolPool`] plus borsh-serialized bytecode and
//! returns generated Swift sources as `(relative_path, content)` pairs.
//! The paths are relative to the generated package's `Sources/Baml/`
//! output root (the harness / CLI decides where that root lives).
//!
//! Phase 0 stub: emits only the runtime payload (`_InlinedBaml.swift`)
//! and an empty `Baml` namespace root. Type translation, routing, and
//! per-symbol emission land in Phase 1+ (`translate_ty.rs`,
//! `routing.rs`, `leaf.rs`, `emit/`).

use std::{collections::HashMap, path::PathBuf};

use base64::Engine as _;

pub use baml_codegen_types::{NamingConvention, OutputType};
use baml_codegen_types::SymbolPool;

/// Build the Swift SDK output tree using precompiled BAML bytecode as
/// the runtime payload. Returned paths are relative to the generated
/// `Sources/Baml/` root.
pub fn to_source_code_with_bytecode(
    pool: &SymbolPool,
    baml_bytecode: &[u8],
    _naming_convention: NamingConvention,
) -> HashMap<PathBuf, String> {
    let mut out: HashMap<PathBuf, String> = HashMap::new();

    out.insert(
        PathBuf::from("_InlinedBaml.swift"),
        render_inlined_baml(baml_bytecode),
    );

    // Phase 0: symbols are not yet emitted; record the count so the
    // stub output is visibly wired to the pool.
    let symbol_count = pool.into_iter().count();
    out.insert(PathBuf::from("Baml.swift"), render_root(symbol_count));

    out
}

/// The borsh bytecode payload, base64-encoded. Base64 keeps the Swift
/// source literal compact (vs. a `[UInt8]` literal, which swiftc
/// type-checks element-by-element and chokes on at engine sizes).
fn render_inlined_baml(baml_bytecode: &[u8]) -> String {
    let b64 = base64::engine::general_purpose::STANDARD.encode(baml_bytecode);
    let mut out = String::from(
        "// Generated by BAML. DO NOT EDIT.\n\
         import Foundation\n\n\
         enum _BamlInlined {\n    static let bytecodeBase64: String =\n",
    );
    // Split into fixed-width chunks joined by `+` so no single source
    // line is megabytes long (editor/diff friendliness).
    const CHUNK: usize = 96;
    let bytes = b64.as_bytes();
    let mut first = true;
    for chunk in bytes.chunks(CHUNK) {
        out.push_str(if first { "        \"" } else { "        + \"" });
        first = false;
        out.push_str(std::str::from_utf8(chunk).expect("base64 is ascii"));
        out.push_str("\"\n");
    }
    if first {
        out.push_str("        \"\"\n");
    }
    out.push_str(
        "\n    static var bytecode: Data {\n        \
         Data(base64Encoded: bytecodeBase64)!\n    }\n}\n",
    );
    out
}

fn render_root(symbol_count: usize) -> String {
    format!(
        "// Generated by BAML. DO NOT EDIT.\n\
         import BamlBridge\n\n\
         /// Root namespace of the generated BAML SDK.\n\
         /// Phase 0 stub — {symbol_count} pool symbol(s) not yet emitted.\n\
         public enum Baml {{}}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bytecode_payload_round_trips_via_base64() {
        let pool = SymbolPool::default();
        let bytecode = vec![0u8, 1, 2, 250, 251, 252];
        let files = to_source_code_with_bytecode(&pool, &bytecode, NamingConvention::PreserveCase);

        let inlined = &files[&PathBuf::from("_InlinedBaml.swift")];
        // Extract the quoted chunks and reassemble the payload.
        let b64: String = inlined
            .lines()
            .filter_map(|l| {
                let l = l.trim().trim_start_matches("+ ");
                l.strip_prefix('"')?.strip_suffix('"').map(str::to_string)
            })
            .collect();
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(b64)
            .expect("valid base64");
        assert_eq!(decoded, bytecode);

        assert!(files[&PathBuf::from("Baml.swift")].contains("public enum Baml"));
    }
}
