[package]
name = "btel_recorder"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = "Owned protobuf conversion for Btel recording data"

[lints]
workspace = true

[dependencies]
btel_clock = { workspace = true }
btel_processor = { workspace = true }
btel_records = { workspace = true }
btel_settings = { workspace = true }
btel_snapshot = { workspace = true }
btel_types = { workspace = true }
prost = { workspace = true }
rustc-hash = { workspace = true }
web-time = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[dev-dependencies]
bex_chunkedringbuffer = { workspace = true }
