[package]
name = "bex_llm_types"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = "BAML Execution Engine - LLM Types"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
baml_base = { workspace = true }
baml_compiler_tir = { workspace = true }
bex_vm_types = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
baml_compiler_hir = { workspace = true }

[features]
test-utils = []
