[package]
name = "baml_jsonish"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints.rust]
dead_code = "allow"

[dependencies]
baml_types = { path = "../baml_types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
indexmap.workspace = true

[dev-dependencies]

[features]
default = []
