[package]
name = "openai"
# Implicitly available to every package (no `[dependencies]` entry needed).
prelude = true

[dependencies]
baml = { path = "../baml" }
log = { path = "../log" }
ai = { path = "../ai" }
