// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ComplexMapsClassView struct {
	inner baml.ClassBuilder
}

func (t *ComplexMapsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComplexMapsClassView) UserMap() (ClassPropertyView, error) {
	return t.inner.Property("userMap")
}

func (t *ComplexMapsClassView) ProductMap() (ClassPropertyView, error) {
	return t.inner.Property("productMap")
}

func (t *ComplexMapsClassView) NestedMap() (ClassPropertyView, error) {
	return t.inner.Property("nestedMap")
}

func (t *ComplexMapsClassView) ArrayMap() (ClassPropertyView, error) {
	return t.inner.Property("arrayMap")
}

func (t *ComplexMapsClassView) MapArray() (ClassPropertyView, error) {
	return t.inner.Property("mapArray")
}

func (t *TypeBuilder) ComplexMaps() (*ComplexMapsClassView, error) {
	bld, err := t.inner.Class("ComplexMaps")
	if err != nil {
		return nil, err
	}
	return &ComplexMapsClassView{inner: bld}, nil
}

type ConfigClassView struct {
	inner baml.ClassBuilder
}

func (t *ConfigClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ConfigClassView) Url() (ClassPropertyView, error) {
	return t.inner.Property("url")
}

func (t *ConfigClassView) Port() (ClassPropertyView, error) {
	return t.inner.Property("port")
}

func (t *ConfigClassView) Debug() (ClassPropertyView, error) {
	return t.inner.Property("debug")
}

func (t *TypeBuilder) Config() (*ConfigClassView, error) {
	bld, err := t.inner.Class("Config")
	if err != nil {
		return nil, err
	}
	return &ConfigClassView{inner: bld}, nil
}

type EdgeCaseMapsClassView struct {
	inner baml.ClassBuilder
}

func (t *EdgeCaseMapsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EdgeCaseMapsClassView) EmptyMap() (ClassPropertyView, error) {
	return t.inner.Property("emptyMap")
}

func (t *EdgeCaseMapsClassView) NullableValues() (ClassPropertyView, error) {
	return t.inner.Property("nullableValues")
}

func (t *EdgeCaseMapsClassView) OptionalValues() (ClassPropertyView, error) {
	return t.inner.Property("optionalValues")
}

func (t *EdgeCaseMapsClassView) UnionValues() (ClassPropertyView, error) {
	return t.inner.Property("unionValues")
}

func (t *TypeBuilder) EdgeCaseMaps() (*EdgeCaseMapsClassView, error) {
	bld, err := t.inner.Class("EdgeCaseMaps")
	if err != nil {
		return nil, err
	}
	return &EdgeCaseMapsClassView{inner: bld}, nil
}

type MixedKeyMapsClassView struct {
	inner baml.ClassBuilder
}

func (t *MixedKeyMapsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MixedKeyMapsClassView) StringIntMap() (ClassPropertyView, error) {
	return t.inner.Property("stringIntMap")
}

func (t *MixedKeyMapsClassView) IntStringMap() (ClassPropertyView, error) {
	return t.inner.Property("intStringMap")
}

func (t *MixedKeyMapsClassView) EnumMap() (ClassPropertyView, error) {
	return t.inner.Property("enumMap")
}

func (t *MixedKeyMapsClassView) LiteralMap() (ClassPropertyView, error) {
	return t.inner.Property("literalMap")
}

func (t *TypeBuilder) MixedKeyMaps() (*MixedKeyMapsClassView, error) {
	bld, err := t.inner.Class("MixedKeyMaps")
	if err != nil {
		return nil, err
	}
	return &MixedKeyMapsClassView{inner: bld}, nil
}

type NestedMapsClassView struct {
	inner baml.ClassBuilder
}

func (t *NestedMapsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *NestedMapsClassView) Simple() (ClassPropertyView, error) {
	return t.inner.Property("simple")
}

func (t *NestedMapsClassView) OneLevelNested() (ClassPropertyView, error) {
	return t.inner.Property("oneLevelNested")
}

func (t *NestedMapsClassView) TwoLevelNested() (ClassPropertyView, error) {
	return t.inner.Property("twoLevelNested")
}

func (t *NestedMapsClassView) MapOfArrays() (ClassPropertyView, error) {
	return t.inner.Property("mapOfArrays")
}

func (t *NestedMapsClassView) MapOfMaps() (ClassPropertyView, error) {
	return t.inner.Property("mapOfMaps")
}

func (t *TypeBuilder) NestedMaps() (*NestedMapsClassView, error) {
	bld, err := t.inner.Class("NestedMaps")
	if err != nil {
		return nil, err
	}
	return &NestedMapsClassView{inner: bld}, nil
}

type ProductClassView struct {
	inner baml.ClassBuilder
}

func (t *ProductClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ProductClassView) Id() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *ProductClassView) Name() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ProductClassView) Price() (ClassPropertyView, error) {
	return t.inner.Property("price")
}

func (t *ProductClassView) Tags() (ClassPropertyView, error) {
	return t.inner.Property("tags")
}

func (t *TypeBuilder) Product() (*ProductClassView, error) {
	bld, err := t.inner.Class("Product")
	if err != nil {
		return nil, err
	}
	return &ProductClassView{inner: bld}, nil
}

type SimpleMapsClassView struct {
	inner baml.ClassBuilder
}

func (t *SimpleMapsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SimpleMapsClassView) StringToString() (ClassPropertyView, error) {
	return t.inner.Property("stringToString")
}

func (t *SimpleMapsClassView) StringToInt() (ClassPropertyView, error) {
	return t.inner.Property("stringToInt")
}

func (t *SimpleMapsClassView) StringToFloat() (ClassPropertyView, error) {
	return t.inner.Property("stringToFloat")
}

func (t *SimpleMapsClassView) StringToBool() (ClassPropertyView, error) {
	return t.inner.Property("stringToBool")
}

func (t *SimpleMapsClassView) IntToString() (ClassPropertyView, error) {
	return t.inner.Property("intToString")
}

func (t *TypeBuilder) SimpleMaps() (*SimpleMapsClassView, error) {
	bld, err := t.inner.Class("SimpleMaps")
	if err != nil {
		return nil, err
	}
	return &SimpleMapsClassView{inner: bld}, nil
}

type UserClassView struct {
	inner baml.ClassBuilder
}

func (t *UserClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *UserClassView) Id() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *UserClassView) Name() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *UserClassView) Email() (ClassPropertyView, error) {
	return t.inner.Property("email")
}

func (t *UserClassView) Active() (ClassPropertyView, error) {
	return t.inner.Property("active")
}

func (t *TypeBuilder) User() (*UserClassView, error) {
	bld, err := t.inner.Class("User")
	if err != nil {
		return nil, err
	}
	return &UserClassView{inner: bld}, nil
}
