# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..__do_not_import.generated_baml_client import baml
from ..baml_types import ITestFnNamedArgsSingleStringList, ITestFnNamedArgsSingleStringListStream
from baml_lib._impl.deserializer import Deserializer
from json import dumps
from pytest_baml.ipc_channel import BaseIPCChannel
from typing import Any, List


@baml.TestFnNamedArgsSingleStringList.test(stream=False)
async def test_invisible_peach(TestFnNamedArgsSingleStringListImpl: ITestFnNamedArgsSingleStringList, baml_ipc_channel: BaseIPCChannel):
    def to_str(item: Any) -> str:
        if isinstance(item, str):
            return item
        return dumps(item)

    case = {"myArg": ["one", "two", "three"], }
    deserializer_myArg = Deserializer[List[str]](List[str]) # type: ignore
    myArg = deserializer_myArg.from_string(to_str(case["myArg"]))
    await TestFnNamedArgsSingleStringListImpl(
        myArg=myArg
    )
