name: ✨ Feature Request
description: Suggest an idea for BAML
title: "[feat] "
labels: ["feature request"]
body:
  - type: dropdown
    attributes:
      label: Product
      description: Which BoundaryML product would this feature be for?
      options:
        - BAML
        - VS Code Playground
        - Boundary Studio
        - Prompt Fiddle
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem Statement / Use Case
      description: What problem are you trying to solve? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions (Optional)
      description: Have you considered any alternative solutions or workarounds?
  - type: textarea
    attributes:
      label: Additional Context (Optional)
      description: Add any other context about the feature request here.