contact_links:
  - name: Ask a question on Discord
    url: https://discord.gg/yzaTpQ3tdT
    about: Ask questions and discuss with other community members
  - name: Report a security issue
    url: https://discord.gg/yzaTpQ3tdT
    about: Report security vulnerabilities
