[package]
name = "sdkgen_rust"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
baml_program_identity.workspace = true
baml_base = { workspace = true }
baml_codegen_types = { workspace = true }
indexmap = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = { workspace = true }
