[package]
name = "bex_sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bex_external_types = { workspace = true }
bex_resource_types = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
