[package]
name = "sdkgen_csharp"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
baml_artifact = { workspace = true }
baml_base = { workspace = true }
baml_codegen_types = { workspace = true }
baml_program_identity.workspace = true
bex_vm_types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true
