from __future__ import annotations

FILES: dict[str, str] = {
    "clients.baml": "client<llm> GPT4oMini {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n",
    "generators.baml": "generator target {\n    output_type \"python/pydantic\"\n    output_dir \"../python\"\n}\n",
    "ns_test003/functions.baml": "client<llm> GPT4oMiniLocal {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nfunction AnalyzeSentiment(text: string) -> Sentiment {\n  client GPT4oMiniLocal\n  prompt #\"\n    Analyze the sentiment of the following text.\n\n    Respond in JSON with this exact schema:\n    {\"label\": \"positive\" or \"negative\" or \"neutral\", \"confidence\": 0.0 to 1.0}\n\n    Text:\n    {{ text }}\n\n    JSON:\n  \"#\n}\n",
    "ns_test003/types.baml": "class Sentiment {\n  label \"positive\" | \"negative\" | \"neutral\"\n  confidence float\n}\n",
    "test001_basic.baml": "class Test001Basic {\n  name string\n  skills string[]\n}\n\nclass Inner001 {\n  value string\n}\n\n// Tests that @stream.done keeps original types at all nesting depths.\nclass StreamDoneNested {\n  // Top-level class: should be types.Inner001, not stream_types.Inner001\n  done_class Inner001 @stream.done\n  // List of classes: should be types.Inner001[], not stream_types.Inner001[]\n  done_list Inner001[] @stream.done\n  // Map with class values: should be map<string, types.Inner001>\n  done_map map<string, Inner001> @stream.done\n  // Regular field (no @stream.done): should use stream variant\n  regular Inner001\n}\n\nfunction ExtractTest001Basic(text: string) -> Test001Basic {\n  client GPT4oMini\n  prompt #\"\n    Extract a resume from the following text.\n    Return the name and a list of skills.\n\n    Respond in JSON with this exact schema:\n    {\"name\": \"string\", \"skills\": [\"string\", ...]}\n\n    Text:\n    {{ text }}\n\n    JSON:\n  \"#\n}\n",
    "test002_directory/functions.baml": "function ExtractContact(text: string) -> ContactInfo {\n  client GPT4oMini\n  prompt #\"\n    Extract contact information from the following text.\n\n    Respond in JSON with this exact schema:\n    {\"name\": \"string\", \"email\": \"string\", \"phone\": \"string or null\"}\n\n    Text:\n    {{ text }}\n\n    JSON:\n  \"#\n}\n",
    "test002_directory/types.baml": "class ContactInfo {\n  name string\n  email string\n  phone string?\n}\n",
    "test004_nonclass_returns/functions.baml": "function ExtractKeywords(text: string) -> string[] {\n  client GPT4oMini\n  prompt #\"\n    Extract the most important keywords from the following text.\n    Return a JSON array of strings.\n\n    Text:\n    {{ text }}\n\n    JSON array:\n  \"#\n}\n\nfunction CountWords(text: string) -> int {\n  client GPT4oMini\n  prompt #\"\n    Count the number of words in the following text.\n    Return only a single integer.\n\n    Text:\n    {{ text }}\n\n    Answer:\n  \"#\n}\n\nfunction ExtractMultipleResumes(text: string) -> Test001Basic[] {\n  client GPT4oMini\n  prompt #\"\n    Extract all people mentioned in the text as resumes.\n    Each resume should have a name and a list of skills.\n\n    Respond in JSON as an array of objects:\n    [{\"name\": \"string\", \"skills\": [\"string\", ...]}, ...]\n\n    Text:\n    {{ text }}\n\n    JSON array:\n  \"#\n}\n\nfunction Summarize(text: string) -> string {\n  client GPT4oMini\n  prompt #\"\n    Summarize the following text in one sentence.\n\n    Text:\n    {{ text }}\n\n    Summary:\n  \"#\n}\n",
}
