// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {
    ComplexOptional(ComplexOptional),

    MixedOptionalNullable(MixedOptionalNullable),

    NullableTypes(NullableTypes),

    OptionalData(OptionalData),

    OptionalFields(OptionalFields),

    OptionalItem(OptionalItem),

    OptionalValue(OptionalValue),

    Product(Product),

    UnionWithNull(UnionWithNull),

    User(User),

    Union2IntOrString(Union2IntOrString),

    Union2ProductOrUser(Union2ProductOrUser),
}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Types::ComplexOptional(_) => "ComplexOptional",

            Types::MixedOptionalNullable(_) => "MixedOptionalNullable",

            Types::NullableTypes(_) => "NullableTypes",

            Types::OptionalData(_) => "OptionalData",

            Types::OptionalFields(_) => "OptionalFields",

            Types::OptionalItem(_) => "OptionalItem",

            Types::OptionalValue(_) => "OptionalValue",

            Types::Product(_) => "Product",

            Types::UnionWithNull(_) => "UnionWithNull",

            Types::User(_) => "User",

            Types::Union2IntOrString(_) => "Union2IntOrString",

            Types::Union2ProductOrUser(_) => "Union2ProductOrUser",
        }
    }
}
