[package]
name = "internal-baml-jinja"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baml-types = { path = "../baml-types", features = ["mini-jinja"] }
internal-baml-jinja-types = { path = "../jinja" }
internal-baml-core = { path = "../baml-core" }
internal-baml-diagnostics = { path = "../diagnostics" }
# TODO: disable imports, etc
minijinja = { version = "1.0.16", default-features = false, features = [
  "macros",
  "builtins",
  "debug",
  "preserve_order",
  "adjacent_loop_items",
  "unicode",
  "json",
  "unstable_machinery",
  "unstable_machinery_serde",
  "custom_syntax",
  "internal_debug",
  "deserialization",
  # We don't want to use these features:
  # multi_template
  # loader
  #
] }
askama.workspace = true
anyhow.workspace = true
indexmap.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strsim = "0.11.1"
colored = "2.1.0"

[dev-dependencies]
env_logger = "0.11.3"
