[package]
name = "baml_cli"
version = { workspace = true }
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
baml_builtins2 = { workspace = true }
baml_codegen_types = { workspace = true }
baml_db = { workspace = true }
baml_exec = { workspace = true }
baml_fmt = { workspace = true }
baml_ide = { workspace = true }
baml_lsp_server = { workspace = true }
baml_release = { workspace = true }
baml_type = { workspace = true }
baml_version = { workspace = true }
bex_cache = { workspace = true }
bex_engine = { workspace = true }
bex_events = { workspace = true }
bex_project = { workspace = true }
bex_vm_types = { workspace = true }
sdkgen_cpp = { workspace = true }
sdkgen_csharp = { workspace = true }
sdkgen_go = { workspace = true }
sdkgen_java = { workspace = true }
sdkgen_python_pydantic2 = { workspace = true }
sdkgen_rust = { workspace = true }
sdkgen_swift = { workspace = true }
sdkgen_typescript_shared = { workspace = true }
sys_native = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true, features = [ "color", "env", "wrap_help" ] }
console = { workspace = true }
ctrlc = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true }
libsui = { workspace = true }
mimalloc = { workspace = true }
mime_guess = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = [ "blocking", "json", "rustls" ] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
strsim = { workspace = true }
tar = { workspace = true }
text-size = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
uuid = { workspace = true }
webbrowser = { workspace = true }

[features]
default = [ "aws-crypto" ]
aws-crypto = [ "bex_engine/aws-crypto", "sys_native/aws-crypto" ]
ring-crypto = [ "bex_engine/ring-crypto", "sys_native/ring-crypto" ]
native-tls = [ "sys_native/native-tls" ]
rustls = [ "aws-crypto" ]
defaults = [  ]
internal = [  ]
skip-integ-tests = [  ]

[dev-dependencies]
baml_tests = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "baml-cli"
path = "src/main.rs"

[package.metadata.ci]
wasm_support = false
