/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type {
  BamlRuntime,
  BamlCtxManager,
  ClientRegistry,
  Image,
  Audio,
  Collector,
} from "@boundaryml/baml";
import { toBamlError } from "@boundaryml/baml";
import type { Checked, Check } from "./types";
import type { partial_types } from "./partial_types";
import type * as types from "./types";
import type { SimpleClass } from "./types";
import type TypeBuilder from "./type_builder";

export class LlmResponseParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ConsumeSimpleClass(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): types.SimpleClass {
    try {
      const env = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      return this.runtime.parseLlmResponse(
        "ConsumeSimpleClass",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.SimpleClass;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  MakeSimpleClass(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): types.SimpleClass {
    try {
      const env = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      return this.runtime.parseLlmResponse(
        "MakeSimpleClass",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as types.SimpleClass;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class LlmStreamParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  ConsumeSimpleClass(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.SimpleClass | null {
    try {
      const env = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      return this.runtime.parseLlmResponse(
        "ConsumeSimpleClass",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.SimpleClass | null;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  MakeSimpleClass(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.SimpleClass | null {
    try {
      const env = __baml_options__?.env
        ? { ...process.env, ...__baml_options__.env }
        : { ...process.env };
      return this.runtime.parseLlmResponse(
        "MakeSimpleClass",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        env,
      ) as partial_types.SimpleClass | null;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
