// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{
  
  "baml_src/main.baml": "class SimpleClass {\n    digits int\n    words string  @stream.with_state\n}\n\nfunction MakeSimpleClass() -> SimpleClass {\n    client \"openai/gpt-4o-mini\"\n    prompt #\"\n        {{ ctx.output_format }}\n    \"#\n}\n\nfunction ConsumeSimpleClass(item: SimpleClass) -> SimpleClass {\n    client \"openai/gpt-4o-mini\"\n    prompt #\"\n        Return back to me verbatim:\n\n        {{ item }}\n    \"#\n}\n\ntest MakeSimpleClassTest {\n    functions [MakeSimpleClass]\n    args {}\n}\n",  
}

func getBamlFiles() map[string]string {
  return file_map
}