[package]
edition = "2021"
name = "baml-derive"
version.workspace = true
authors.workspace = true
license-file.workspace = true
description = "Derive macros for BAML"

[lints.rust]
dead_code = "warn"
elided_named_lifetimes = "deny"
unused_imports = "warn"
unused_variables = "warn"


[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
