flowchart TD
  subgraph sg0["Start"]
    direction LR
    n0{"Start"}
    class n0 decisionNode;
    n1["After"]
  end
  n0 --> n1
%%__BAML_SPANMAP__={"n0":{"file_path":"tests/validation_files/headers/if_then_only_header.baml","start_line":3,"start":4,"end_line":3,"end":13},"n1":{"file_path":"tests/validation_files/headers/if_then_only_header.baml","start_line":6,"start":4,"end_line":6,"end":14}}
  click n0 call bamlMermaidNodeClick() "Go to source"
  click n1 call bamlMermaidNodeClick() "Go to source"