flowchart TD
  n0["Parent"]
  subgraph sg0["MD Child"]
    direction LR
    n1["Loop Child"]
    n2["And stuff"]
  end
  n1 --> n2
  n0 --> n1
%%__BAML_SPANMAP__={"n0":{"file_path":"tests/validation_files/headers/mixed_children_not_flattened.baml","start_line":0,"start":0,"end_line":0,"end":10},"n1":{"file_path":"tests/validation_files/headers/mixed_children_not_flattened.baml","start_line":5,"start":8,"end_line":5,"end":24},"n2":{"file_path":"tests/validation_files/headers/mixed_children_not_flattened.baml","start_line":6,"start":0,"end_line":6,"end":23}}
  click n0 call bamlMermaidNodeClick() "Go to source"
  click n1 call bamlMermaidNodeClick() "Go to source"
  click n2 call bamlMermaidNodeClick() "Go to source"