flowchart TD
  subgraph sg0["Top Level"]
    direction TB
    subgraph sg1["First Section"]
      direction TB
      n0{"First Section"}
      class n0 decisionNode;
      n1["Inside If Block"]
      n2["Inside Else Block"]
    end
  end
  n0 --> n1
  n0 --> n2
%%__BAML_SPANMAP__={"n0":{"file_path":"tests/validation_files/headers/nested_scopes.baml","start_line":4,"start":4,"end_line":4,"end":22},"n1":{"file_path":"tests/validation_files/headers/nested_scopes.baml","start_line":6,"start":8,"end_line":6,"end":29},"n2":{"file_path":"tests/validation_files/headers/nested_scopes.baml","start_line":10,"start":8,"end_line":10,"end":31}}
  click n0 call bamlMermaidNodeClick() "Go to source"
  click n1 call bamlMermaidNodeClick() "Go to source"
  click n2 call bamlMermaidNodeClick() "Go to source"