# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_attendee import Attendee
from ..types.classes.cls_meetingrequest import MeetingRequest
from baml_lib._impl.functions import BaseBAMLFunction
from typing import Protocol, runtime_checkable


IExtractMeetingRequestInfoOutput = MeetingRequest

@runtime_checkable
class IExtractMeetingRequestInfo(Protocol):
    """
    This is the interface for a function.

    Args:
        query: str
        now: str

    Returns:
        MeetingRequest
    """

    async def __call__(self, *, query: str, now: str) -> MeetingRequest:
        ...


class IBAMLExtractMeetingRequestInfo(BaseBAMLFunction[MeetingRequest]):
    def __init__(self) -> None:
        super().__init__(
            "ExtractMeetingRequestInfo",
            IExtractMeetingRequestInfo,
            ["v1", "robust"],
        )

BAMLExtractMeetingRequestInfo = IBAMLExtractMeetingRequestInfo()

__all__ = [ "BAMLExtractMeetingRequestInfo" ]
