// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)
//! by the stream_type_to_rust conversion.

use crate::baml_client::types;
use crate::baml_client::types::*;
use std::collections::HashMap;

/// Streaming variant of ComplexMaps.
#[derive(Debug, Clone, Default)]
pub struct ComplexMaps {
    pub userMap: std::collections::HashMap<String, User>,

    pub productMap: std::collections::HashMap<String, Product>,

    pub nestedMap: std::collections::HashMap<String, std::collections::HashMap<String, String>>,

    pub arrayMap: std::collections::HashMap<String, Vec<i64>>,

    pub mapArray: Vec<std::collections::HashMap<String, String>>,
}

/// Streaming variant of Config.
#[derive(Debug, Clone, Default)]
pub struct Config {
    pub url: Option<String>,

    pub port: Option<i64>,

    pub debug: Option<bool>,
}

/// Streaming variant of EdgeCaseMaps.
#[derive(Debug, Clone, Default)]
pub struct EdgeCaseMaps {
    pub emptyMap: std::collections::HashMap<String, String>,

    pub nullableValues: std::collections::HashMap<String, Option<String>>,

    pub optionalValues: std::collections::HashMap<String, Option<String>>,

    pub unionValues: std::collections::HashMap<String, types::Union3BoolOrIntOrString>,
}

/// Streaming variant of MixedKeyMaps.
#[derive(Debug, Clone, Default)]
pub struct MixedKeyMaps {
    pub stringIntMap: std::collections::HashMap<String, i64>,

    pub intStringMap: std::collections::HashMap<String, String>,

    pub enumMap: std::collections::HashMap<String, String>,

    pub literalMap: std::collections::HashMap<String, Config>,
}

/// Streaming variant of NestedMaps.
#[derive(Debug, Clone, Default)]
pub struct NestedMaps {
    pub simple: std::collections::HashMap<String, String>,

    pub oneLevelNested: std::collections::HashMap<String, std::collections::HashMap<String, i64>>,

    pub twoLevelNested: std::collections::HashMap<
        String,
        std::collections::HashMap<String, std::collections::HashMap<String, bool>>,
    >,

    pub mapOfArrays: std::collections::HashMap<String, Vec<String>>,

    pub mapOfMaps: std::collections::HashMap<String, std::collections::HashMap<String, f64>>,
}

/// Streaming variant of Product.
#[derive(Debug, Clone, Default)]
pub struct Product {
    pub id: Option<i64>,

    pub name: Option<String>,

    pub price: Option<f64>,

    pub tags: Vec<String>,
}

/// Streaming variant of SimpleMaps.
#[derive(Debug, Clone, Default)]
pub struct SimpleMaps {
    pub stringToString: std::collections::HashMap<String, String>,

    pub stringToInt: std::collections::HashMap<String, i64>,

    pub stringToFloat: std::collections::HashMap<String, f64>,

    pub stringToBool: std::collections::HashMap<String, bool>,

    pub intToString: std::collections::HashMap<String, String>,
}

/// Streaming variant of User.
#[derive(Debug, Clone, Default)]
pub struct User {
    pub id: Option<i64>,

    pub name: Option<String>,

    pub email: Option<String>,

    pub active: Option<bool>,
}
