[package]
edition = "2021"
name = "boundary-collector"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[package.metadata.rustflags]
RSTEST_TIMEOUT = "10"

[build-dependencies]
anyhow.workspace = true

[lints.rust]
dead_code = "allow"
elided_named_lifetimes = "deny"
unused_imports = "allow"
unused_variables = "allow"

[dependencies]
baml-runtime.workspace = true
