enum Color {
  Red
  Green
  Blue
}

class Widget {
  color Color
  size int
}

// class baml.HttpRequest {
//   url: string
//   method: baml.HttpMethod
//   headers: (map<string, string> | null)
//   query_params: (map<string, string> | null)
//   json: (ANY | null)
// }
//
// class Widget {
//   color: Color
//   size: int
// }
//
// enum baml.HttpMethod {
//   Get
//   Post
//   Put
//   Delete
//   Patch
// }
//
// enum Color {
//   Red
//   Green
//   Blue
// }
