// Expression functions returning literal values
function ReturnInt() -> int {
    42
}

function ReturnString() -> string {
    "Hello World"
}

function ReturnBool() -> bool {
    true
}

function ReturnFloat() -> float {
    3.14
}

function ReturnArray() -> int[] {
    [1, 2, 3, 4, 5]
}

// function ReturnInt() {
//   return 42;
// }
//
// function ReturnString() {
//   return "Hello World";
// }
//
// function ReturnBool() {
//   return true;
// }
//
// function ReturnFloat() {
//   return 3.14;
// }
//
// function ReturnArray() {
//   return [1, 2, 3, 4, 5];
// }
//
// class std::Request {
//   base_url: string
//   headers: map<string, string>
//   query_params: map<string, string>
// }
//
// enum std::HttpMethod {
//   Get
// }