// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Example struct {
	A *int64  `json:"a"`
	B *string `json:"b"`
}

func (c *Example) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Example" {
		panic(fmt.Sprintf("expected Example, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "a":
			c.A = func(param *cffi.CFFIValueHolder) *int64 {
				decoded := baml.Decode(param)
				return func(result any) *int64 {
					if result == nil {
						return nil
					}
					casted := (result).(int64)
					return &casted
				}(decoded)
			}(valueHolder)

		case "b":
			c.B = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Example) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["a"] = c.A

	fields["b"] = c.B

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Example) BamlTypeName() string {
	return "Example"
}

func (u Example) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Example",
	}
}

type Example2 struct {
	Item     *Example `json:"item"`
	Element  *string  `json:"element"`
	Element2 *string  `json:"element2"`
}

func (c *Example2) Decode(holder *cffi.CFFIValueClass) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Example2" {
		panic(fmt.Sprintf("expected Example2, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "item":
			c.Item = func(param *cffi.CFFIValueHolder) *Example {
				decoded := baml.Decode(param)
				return func(result any) *Example {
					if result == nil {
						return nil
					}
					casted := (result).(*Example)
					return casted
				}(decoded)
			}(valueHolder)

		case "element":
			c.Element = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		case "element2":
			c.Element2 = func(param *cffi.CFFIValueHolder) *string {
				decoded := baml.Decode(param)
				return func(result any) *string {
					if result == nil {
						return nil
					}
					casted := (result).(string)
					return &casted
				}(decoded)
			}(valueHolder)

		default:
			panic(fmt.Sprintf("unexpected field: %s", key))
		}
	}

}

func (c Example2) Encode() (*cffi.CFFIValueHolder, error) {
	fields := map[string]any{}

	fields["item"] = c.Item

	fields["element"] = c.Element

	fields["element2"] = c.Element2

	return baml.EncodeClass(c.BamlEncodeName, fields, nil)
}

func (c Example2) BamlTypeName() string {
	return "Example2"
}

func (u Example2) BamlEncodeName() *cffi.CFFITypeName {
	return &cffi.CFFITypeName{
		Namespace: cffi.CFFITypeNamespace_STREAM_TYPES,
		Name:      "Example2",
	}
}
