[package]
name = "baml_lsp2_actions"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
baml_base = { workspace = true }
baml_compiler2_ast = { workspace = true }
baml_compiler2_hir = { workspace = true }
baml_compiler2_ppir = { workspace = true }
baml_compiler2_tir = { workspace = true }
baml_compiler_diagnostics = { workspace = true }
baml_compiler_parser = { workspace = true }
baml_compiler_syntax = { workspace = true }
sys_jinja_types = { workspace = true }
indexmap = { workspace = true }
rowan = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
text-size = { workspace = true }

[dev-dependencies]
baml_builtins2 = { workspace = true }
baml_workspace = { workspace = true }
insta = { workspace = true }
