[package]
name = "tools_sap_visualizer"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tools_sap_visualizer"
path = "src/main.rs"

[dependencies]
baml_project = { workspace = true }
baml_type = { workspace = true }
bex_sap = { workspace = true, features = [ "manual_db" ] }
bex_vm_types = { workspace = true }
sys_types = { workspace = true }
eframe = { workspace = true }
indexmap = { workspace = true }
ouroboros = { workspace = true }
serde_json = { workspace = true }
web-time = { workspace = true }
