export const TIME_INTERVALS = {
  SECOND: 1000,
  MINUTE: 60000,
  HOUR: 3600000,
} as const;

export const UPDATE_THRESHOLDS = {
  MINUTE: TIME_INTERVALS.MINUTE,
  HOUR: TIME_INTERVALS.HOUR,
} as const;