# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in baml.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
# Must be kept in sync with Cargo.toml
gem "rb_sys", "=0.9.97"

gem "async"