[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Vaibhav Gupta <vbv@gloo.chat>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
baml = { path = "../../../clients/python", develop = true }
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
