mod code_lens;
mod completion;
mod diagnostic;
mod execute_command;
mod format;
mod go_to_definition;
mod hover;
mod rename;

// pub(super) use code_action::CodeActions;
// pub(super) use code_action_resolve::CodeActionResolve;
// pub(super) use diagnostic::DocumentDiagnostic;
// pub(super) use execute_command::ExecuteCommand;
// pub(super) use format::Format;
// pub(super) use format_range::FormatRange;
pub use code_lens::CodeLens;
pub(super) use completion::Completion;
pub(super) use diagnostic::DocumentDiagnosticRequestHandler;
pub(super) use format::DocumentFormatting;
pub use go_to_definition::GotoDefinition;
pub(super) use hover::Hover;
type FormatResponse = Option<Vec<lsp_types::TextEdit>>;
