[package]
name = "baml_compiler2_ppir"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
baml_base = { workspace = true }
baml_compiler2_ast = { workspace = true }
baml_compiler2_hir = { workspace = true }
indexmap = { workspace = true }
salsa = { workspace = true }
text-size = { workspace = true }
