//! Semantic impls for [`TyTemplate`], the `Ty`-shaped template member of the
//! type family.
//!
//! A template is *complete*: every leaf is either realized or a positional
//! frame reference ([`TyTemplate::TypeArgRef`]), so `substitute` always has a
//! single concrete answer per position. This is the type of every emitted
//! template (a `LoadType`, a generic-function value, an instance's class type
//! args, a baked impl rule, a `match`/`is` test). A pattern position the MIR
//! lowering cannot resolve to a template is reported at the builder
//! (`Option::None`), never smuggled as an erased or match-any leaf.
//!
//! The enum itself, its satellites ([`TyTemplateInterface`],
//! [`crate::TyTemplateFunctionParamTy`]), and the `RealizedTy ⊂ TyTemplate`
//! conversions are generated by the
//! [`ty_family!`](baml_type_macros::ty_family) macro. It swaps the name-based
//! `TypeVar` for the positional frame leaf and keeps
//! `AssociatedTypeProjection` for symbolic projections — so a template can
//! express an unresolved generic *structurally*, never as an opaque name.
//!
//! A template that contains no template-only leaf is "fully realized" and
//! narrows to a [`RealizedTy`] (the generated `TryFrom`); that narrowing is
//! the `is_fully_concrete` check.
//!
//! # De Bruijn indexing
//!
//! `TypeArgRef(n)` refers to the n-th entry in the enclosing call-frame's
//! `type_args` vector (0-based). The compiler assigns indices using
//! `function_generic_params` ordering so the mapping is stable across
//! compilation.

use std::fmt;

use crate::{
    Interface, Name, RealizedFunctionParamTy, RealizedTy, RuntimeFunctionParamTy, RuntimeInterface,
    RuntimeTy, Ty, TyAttr, TyTemplate, TyTemplateInterface, TypeName,
    normalize::{ProjectionStep, TypeContext},
};

/// Why a [`TyTemplate::substitute`] failed to fully realize a template against a
/// frame's realized type arguments.
///
/// Substitution at runtime must produce a fully realized [`RealizedTy`] — every
/// frame reference filled, every projection reduced — or fail loudly. It never
/// erases an unresolved position to `unknown` (which would silently break the
/// value's compile-time type contract). Each variant is a broken invariant the VM
/// surfaces as an internal error, not a user-facing type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SubstituteError {
    /// An associated-type projection `(base as I).member` over a *realized* base
    /// could not be reduced to a concrete type — no impl binding was found. The
    /// compiler proves the impl exists for any realized base, so this is a broken
    /// invariant at runtime rather than a legitimate outcome.
    UnreducibleProjection {
        /// The associated-type member that failed to reduce.
        member: Name,
    },
    /// A projection reduced, but to a type that still contained a non-realized
    /// position (named by `variant`). A realized base should reduce to a realized
    /// witness, so this too is a broken invariant.
    ProjectionNotRealized {
        /// The associated-type member whose reduction was not realized.
        member: Name,
        /// The offending non-realized variant encountered in the reduced type.
        variant: &'static str,
    },
    /// A projection-reduction chain exceeded the fuel budget — a cyclic or
    /// pathologically deep associated-type binding whose reduction re-enters
    /// itself (`type X = (_ as I).Y` reducing back through `X`). The compiler is
    /// expected to reject such cycles at declaration, so hitting this runtime
    /// backstop is a broken invariant rather than a legitimate outcome; it stops
    /// the recursion instead of overflowing the stack.
    ProjectionFuelExhausted {
        /// The associated-type member whose reduction chain did not terminate.
        member: Name,
    },
    /// A `TypeArgRef(index)` referenced a slot the frame does not supply. It is
    /// a system invariant that a template's indices only reference its
    /// surrounding frame — the compiler seeds every generic frame at full
    /// declared width (an unconstrained parameter is seeded as an explicit
    /// `unknown`, never omitted) — so an out-of-range reference means the
    /// emitted De Bruijn indices and the seeded frame no longer agree: a
    /// frame-layout bug, checked in every build profile. (A later revision may
    /// drop the check in release and perform the access unchecked.)
    TypeArgRefOutOfRange {
        /// The out-of-range De Bruijn index.
        index: u32,
        /// The width of the frame the template was substituted against.
        frame_len: usize,
    },
}

impl fmt::Display for SubstituteError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnreducibleProjection { member } => {
                write!(
                    f,
                    "associated-type projection `.{member}` could not be reduced"
                )
            }
            Self::ProjectionNotRealized { member, variant } => write!(
                f,
                "associated-type projection `.{member}` reduced to a non-realized `{variant}`"
            ),
            Self::ProjectionFuelExhausted { member } => write!(
                f,
                "associated-type projection `.{member}` did not terminate within the reduction budget"
            ),
            Self::TypeArgRefOutOfRange { index, frame_len } => write!(
                f,
                "template references frame type-arg slot {index} but the frame has {frame_len} type args"
            ),
        }
    }
}

impl std::error::Error for SubstituteError {}

impl TyTemplate {
    // --- Ergonomic constructors (default TyAttr) ---

    /// `T[]` (list) with default attributes.
    pub fn list(inner: TyTemplate) -> Self {
        TyTemplate::List(Box::new(inner), TyAttr::default())
    }

    /// `map<K, V>` with default attributes.
    pub fn map(key: TyTemplate, value: TyTemplate) -> Self {
        TyTemplate::Map {
            key: Box::new(key),
            value: Box::new(value),
            attr: TyAttr::default(),
        }
    }

    /// `A | B | ...` (union) with default attributes.
    pub fn union(members: impl IntoIterator<Item = TyTemplate>) -> Self {
        TyTemplate::Union(members.into_iter().collect(), TyAttr::default())
    }

    /// `Class<A1, A2, ...>` (generic class instantiation) with default attributes.
    pub fn class(name: TypeName, args: Vec<TyTemplate>) -> Self {
        TyTemplate::Class(name, args, TyAttr::default())
    }

    /// `Interface<A1, Assoc = A2, ...>` with default attributes.
    pub fn interface(
        name: TypeName,
        args: Vec<TyTemplate>,
        associated_bindings: Vec<(Name, TyTemplate)>,
    ) -> Self {
        TyTemplate::Interface(name, args, associated_bindings, TyAttr::default())
    }

    /// Materialize this template against a frame's fully realized `type_args`,
    /// producing a [`RealizedTy`] — every `TypeArgRef(n)` replaced by
    /// `type_args[n]`, every associated-type projection reduced through `ctx` to
    /// its impl binding.
    ///
    /// Runtime type arguments are always realized (a generic call binds each
    /// parameter to a concrete type), so a template that occurs at a
    /// materialization site — a `LoadType`, a generic-function value, an instance's
    /// class type args — realizes fully or fails. It never erases an unresolved
    /// projection to `unknown`; an unreducible projection is a broken invariant
    /// returned as a [`SubstituteError`] for the VM to surface as an internal
    /// error.
    ///
    /// A projection reduces because its qualifier is always known (the interface is
    /// non-optional) and its base realizes here, so `ctx.project` — the same impl
    /// consultation the canonical algebra uses — determines the concrete witness.
    pub fn substitute<C: TypeContext>(
        &self,
        type_args: &[RealizedTy],
        ctx: &C,
    ) -> Result<RealizedTy, SubstituteError> {
        self.substitute_with_fuel(type_args, ctx, crate::normalize::PROJECTION_REDUCTION_FUEL)
    }

    /// [`Self::substitute`] with an explicit projection-reduction budget.
    ///
    /// `fuel` bounds the associated-type reduction chain: each projection reduced
    /// through `ctx.project` (which realizes the impl binding by re-entering this
    /// method) spends one unit, so a cyclic binding — `type X = (_ as I).Y`
    /// reducing back through `X` — terminates with
    /// [`SubstituteError::ProjectionFuelExhausted`] instead of overflowing the
    /// stack. This is the runtime twin of the canonical algebra's fuel guard in
    /// `normalize`'s `from_ty` walk. The public [`Self::substitute`] seeds the full
    /// `PROJECTION_REDUCTION_FUEL` budget; `ctx.project` threads the remainder back
    /// in for the binding it realizes.
    pub fn substitute_with_fuel<C: TypeContext>(
        &self,
        type_args: &[RealizedTy],
        ctx: &C,
        fuel: u32,
    ) -> Result<RealizedTy, SubstituteError> {
        match self {
            // ── Template-only leaf ────────────────────────────────────────────
            // A frame reference materializes to its bound type argument. The
            // frame always supplies every slot the template can reference: the
            // compiler seeds generic frames at full declared width, with an
            // unconstrained parameter seeded as an explicit `unknown` (so
            // `type.of<T>()` under an unknown-typed call still reflects
            // the honest top type through a real slot). An out-of-range index is
            // therefore a frame-layout bug — reported, never silently realized.
            Self::TypeArgRef(n) => match type_args.get(*n as usize) {
                Some(arg) => Ok(arg.clone()),
                None => Err(SubstituteError::TypeArgRefOutOfRange {
                    index: *n,
                    frame_len: type_args.len(),
                }),
            },

            // ── Composites: recurse, propagating failures ─────────────────────
            Self::List(inner, attr) => Ok(RealizedTy::List(
                Box::new(inner.substitute_with_fuel(type_args, ctx, fuel)?),
                attr.clone(),
            )),
            Self::Map { key, value, attr } => Ok(RealizedTy::Map {
                key: Box::new(key.substitute_with_fuel(type_args, ctx, fuel)?),
                value: Box::new(value.substitute_with_fuel(type_args, ctx, fuel)?),
                attr: attr.clone(),
            }),
            Self::Union(parts, attr) => Ok(RealizedTy::Union(
                parts
                    .iter()
                    .map(|p| p.substitute_with_fuel(type_args, ctx, fuel))
                    .collect::<Result<_, _>>()?,
                attr.clone(),
            )),
            Self::Class(name, args, attr) => Ok(RealizedTy::Class(
                name.clone(),
                args.iter()
                    .map(|a| a.substitute_with_fuel(type_args, ctx, fuel))
                    .collect::<Result<_, _>>()?,
                attr.clone(),
            )),
            Self::Interface(name, args, associated_bindings, attr) => Ok(RealizedTy::Interface(
                name.clone(),
                args.iter()
                    .map(|a| a.substitute_with_fuel(type_args, ctx, fuel))
                    .collect::<Result<_, _>>()?,
                associated_bindings
                    .iter()
                    .map(|(name, ty)| {
                        Ok((name.clone(), ty.substitute_with_fuel(type_args, ctx, fuel)?))
                    })
                    .collect::<Result<_, _>>()?,
                attr.clone(),
            )),
            Self::Function {
                params,
                ret,
                throws,
                attr,
            } => Ok(RealizedTy::Function {
                params: params
                    .iter()
                    .map(|p| {
                        Ok(RealizedFunctionParamTy {
                            name: p.name.clone(),
                            ty: p.ty.substitute_with_fuel(type_args, ctx, fuel)?,
                            mode: p.mode,
                        })
                    })
                    .collect::<Result<_, _>>()?,
                ret: Box::new(ret.substitute_with_fuel(type_args, ctx, fuel)?),
                throws: Box::new(throws.substitute_with_fuel(type_args, ctx, fuel)?),
                attr: attr.clone(),
            }),
            Self::Future(value, error, attr) => Ok(RealizedTy::Future(
                Box::new(value.substitute_with_fuel(type_args, ctx, fuel)?),
                Box::new(error.substitute_with_fuel(type_args, ctx, fuel)?),
                attr.clone(),
            )),
            // Realize the base, then reduce the projection to the impl's binding.
            // The qualifier is always known and the base is realized here, so a
            // realized-base projection reduces to exactly one concrete witness;
            // anything else is a broken invariant, never a symbolic leaf.
            Self::AssociatedTypeProjection {
                base,
                interface,
                member,
                ..
            } => {
                let base = base.substitute_with_fuel(type_args, ctx, fuel)?;
                let interface = interface.substitute(type_args, ctx, fuel)?;
                // Spend one unit on *this* reduction before consulting `ctx.project`,
                // which realizes the impl binding by re-entering `substitute` and can
                // reach another projection. A cyclic binding would otherwise recurse
                // forever; the backstop mirrors the canonical algebra's `from_ty`.
                let Some(fuel) = fuel.checked_sub(1) else {
                    return Err(SubstituteError::ProjectionFuelExhausted {
                        member: member.clone(),
                    });
                };
                match ctx.project(base.as_ty(), &interface, member, fuel) {
                    ProjectionStep::Reduced(reduced) => {
                        RealizedTy::try_from(&reduced).map_err(|e| {
                            SubstituteError::ProjectionNotRealized {
                                member: member.clone(),
                                variant: e.variant,
                            }
                        })
                    }
                    ProjectionStep::Opaque => Err(SubstituteError::UnreducibleProjection {
                        member: member.clone(),
                    }),
                }
            }

            // ── Realized leaf ─────────────────────────────────────────────────
            // No template refs and no nested type positions: it narrows to a
            // `RealizedTy` directly. A composite variant is handled above, so a
            // narrowing failure here would be a missing arm — surfaced loudly.
            other => Ok(RealizedTy::try_from(other.clone())
                .unwrap_or_else(|e| unreachable!("realized-leaf template narrowing failed: {e}"))),
        }
    }

    /// Returns `true` when the template contains no template-only leaf
    /// (`TypeArgRef` or an unresolved projection) at any depth — i.e. it is a
    /// fully realized type that narrows to a [`RealizedTy`].
    pub fn is_fully_concrete(&self) -> bool {
        <&RealizedTy>::try_from(self).is_ok()
    }

    /// Compile-time counterpart to [`Self::substitute`]: resolve each
    /// `TypeArgRef(n)` against `type_args` but leave every unresolved position
    /// *symbolic*. An associated projection stays a projection; an out-of-range
    /// reference falls back to `unknown`. Used by compile-time type
    /// computation (e.g. a class field's type given the receiver's class args),
    /// where the args may themselves be symbolic — an unspecialized generic — so
    /// the result is a `RuntimeTy` that can still carry type variables, unlike the
    /// runtime [`Self::substitute`], which realizes fully or fails.
    pub fn substitute_symbolic(&self, type_args: &[RuntimeTy]) -> RuntimeTy {
        match self {
            Self::TypeArgRef(n) => type_args
                .get(*n as usize)
                .cloned()
                .unwrap_or_else(RuntimeTy::unknown),
            Self::List(inner, attr) => {
                RuntimeTy::List(Box::new(inner.substitute_symbolic(type_args)), attr.clone())
            }
            Self::Map { key, value, attr } => RuntimeTy::Map {
                key: Box::new(key.substitute_symbolic(type_args)),
                value: Box::new(value.substitute_symbolic(type_args)),
                attr: attr.clone(),
            },
            Self::Union(parts, attr) => RuntimeTy::Union(
                parts
                    .iter()
                    .map(|p| p.substitute_symbolic(type_args))
                    .collect(),
                attr.clone(),
            ),
            Self::Class(name, args, attr) => RuntimeTy::Class(
                name.clone(),
                args.iter()
                    .map(|a| a.substitute_symbolic(type_args))
                    .collect(),
                attr.clone(),
            ),
            Self::Interface(name, args, associated_bindings, attr) => RuntimeTy::Interface(
                name.clone(),
                args.iter()
                    .map(|a| a.substitute_symbolic(type_args))
                    .collect(),
                associated_bindings
                    .iter()
                    .map(|(name, ty)| (name.clone(), ty.substitute_symbolic(type_args)))
                    .collect(),
                attr.clone(),
            ),
            Self::Function {
                params,
                ret,
                throws,
                attr,
            } => RuntimeTy::Function {
                params: params
                    .iter()
                    .map(|p| RuntimeFunctionParamTy {
                        name: p.name.clone(),
                        ty: p.ty.substitute_symbolic(type_args),
                        mode: p.mode,
                    })
                    .collect(),
                ret: Box::new(ret.substitute_symbolic(type_args)),
                throws: Box::new(throws.substitute_symbolic(type_args)),
                attr: attr.clone(),
            },
            Self::Future(value, error, attr) => RuntimeTy::Future(
                Box::new(value.substitute_symbolic(type_args)),
                Box::new(error.substitute_symbolic(type_args)),
                attr.clone(),
            ),
            Self::AssociatedTypeProjection {
                base,
                interface,
                member,
                attr,
            } => RuntimeTy::AssociatedTypeProjection {
                base: Box::new(base.substitute_symbolic(type_args)),
                interface: Box::new(interface.substitute_symbolic(type_args)),
                member: member.clone(),
                attr: attr.clone(),
            },
            // A realized leaf narrows to `RealizedTy` then widens to `RuntimeTy`.
            other => RealizedTy::try_from(other.clone())
                .unwrap_or_else(|e| unreachable!("realized-leaf template narrowing failed: {e}"))
                .into(),
        }
    }
}

impl std::fmt::Display for TyTemplateInterface {
    /// Renders as the existential template it denotes, so an interface constraint
    /// and the type it lifts to print identically in diagnostics and MIR dumps.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_template())
    }
}

impl TyTemplateInterface {
    /// The interface *existential* template ([`TyTemplate::Interface`]) denoted by
    /// this constraint, with default attributes — the template-level counterpart of
    /// [`Interface::to_ty`].
    ///
    /// Needed only at boundaries that carry a *type* rather than a constraint (the
    /// bytecode constant pool a `LoadType` reads from). Prefer holding the
    /// constraint itself wherever an interface is meant: a `TyTemplate` slot admits
    /// non-interface types, which an interface position can never legitimately hold.
    pub fn to_template(&self) -> TyTemplate {
        TyTemplate::interface(
            self.name.clone(),
            self.generics.clone(),
            self.associated_types.clone(),
        )
    }

    /// Substitute frame type args through the interface's generic and
    /// associated-binding positions, producing the realized [`Interface`]
    /// constraint used to reduce the enclosing projection (see
    /// [`TyTemplate::substitute`]). Each realized position widens into `Ty` for the
    /// [`Interface`] the projection query consumes.
    fn substitute<C: TypeContext>(
        &self,
        type_args: &[RealizedTy],
        ctx: &C,
        fuel: u32,
    ) -> Result<Interface, SubstituteError> {
        Ok(Interface::new(
            self.name.clone(),
            self.generics
                .iter()
                .map(|g| g.substitute_with_fuel(type_args, ctx, fuel).map(Ty::from))
                .collect::<Result<_, _>>()?,
            self.associated_types
                .iter()
                .map(|(name, ty)| {
                    Ok((
                        name.clone(),
                        Ty::from(ty.substitute_with_fuel(type_args, ctx, fuel)?),
                    ))
                })
                .collect::<Result<_, _>>()?,
        ))
    }

    /// Compile-time counterpart to [`Self::substitute`] (see
    /// [`TyTemplate::substitute_symbolic`]): resolve frame refs but leave
    /// unresolved positions symbolic, producing a `RuntimeInterface`.
    fn substitute_symbolic(&self, type_args: &[RuntimeTy]) -> RuntimeInterface {
        RuntimeInterface::new(
            self.name.clone(),
            self.generics
                .iter()
                .map(|g| g.substitute_symbolic(type_args))
                .collect(),
            self.associated_types
                .iter()
                .map(|(name, ty)| (name.clone(), ty.substitute_symbolic(type_args)))
                .collect(),
        )
    }
}

impl fmt::Display for TyTemplate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Render through `Ty`'s `Display` so every shared construct (list-postfix
        // parenthesization, `future<…>` casing, function `throws` handling, …)
        // stays byte-identical to the canonical type renderer — no per-variant
        // drift. Only the template-only leaf needs a placeholder: a frame ref
        // shows as `#n` (a `TypeVar` named `#n`).
        fmt::Display::fmt(&self.to_display_ty(), f)
    }
}

impl TyTemplate {
    /// A lossy [`Ty`] view for rendering only: frame refs become
    /// `TypeVar("#n")`. Every other node maps structurally, so
    /// [`fmt::Display`] can delegate to `Ty`'s renderer.
    fn to_display_ty(&self) -> crate::Ty {
        use crate::Ty;
        match self {
            Self::TypeArgRef(n) => Ty::TypeVar(
                crate::ParamTy::new(*n, Name::new(format!("#{n}"))),
                TyAttr::default(),
            ),
            Self::List(inner, attr) => Ty::List(Box::new(inner.to_display_ty()), attr.clone()),
            Self::Map { key, value, attr } => Ty::Map {
                key: Box::new(key.to_display_ty()),
                value: Box::new(value.to_display_ty()),
                attr: attr.clone(),
            },
            Self::Union(parts, attr) => Ty::Union(
                parts.iter().map(Self::to_display_ty).collect(),
                attr.clone(),
            ),
            Self::Class(name, args, attr) => Ty::Class(
                name.clone(),
                args.iter().map(Self::to_display_ty).collect(),
                attr.clone(),
            ),
            Self::Interface(name, args, associated_bindings, attr) => Ty::Interface(
                name.clone(),
                args.iter().map(Self::to_display_ty).collect(),
                associated_bindings
                    .iter()
                    .map(|(n, t)| (n.clone(), t.to_display_ty()))
                    .collect(),
                attr.clone(),
            ),
            Self::Function {
                params,
                ret,
                throws,
                attr,
            } => Ty::Function {
                params: params
                    .iter()
                    .map(|p| crate::FunctionParamTy {
                        name: p.name.clone(),
                        ty: p.ty.to_display_ty(),
                        mode: p.mode,
                    })
                    .collect(),
                ret: Box::new(ret.to_display_ty()),
                throws: Box::new(throws.to_display_ty()),
                attr: attr.clone(),
            },
            Self::Future(value, error, attr) => Ty::Future(
                Box::new(value.to_display_ty()),
                Box::new(error.to_display_ty()),
                attr.clone(),
            ),
            Self::AssociatedTypeProjection {
                base,
                interface,
                member,
                attr,
            } => Ty::AssociatedTypeProjection {
                base: Box::new(base.to_display_ty()),
                interface: Box::new(crate::Interface {
                    name: interface.name.clone(),
                    generics: interface.generics.iter().map(Self::to_display_ty).collect(),
                    associated_types: interface
                        .associated_types
                        .iter()
                        .map(|(n, t)| (n.clone(), t.to_display_ty()))
                        .collect(),
                }),
                member: member.clone(),
                attr: attr.clone(),
            },
            // A realized leaf widens into `Ty` by the generated conversion.
            other => Ty::from(RealizedTy::try_from(other.clone()).unwrap_or_else(|e| {
                unreachable!("realized-leaf template widening for display failed: {e}")
            })),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Interface, QualifiedTypeName, RuntimeTy};

    /// A context-free [`TypeContext`]: these substitution tests exercise frame-ref
    /// resolution and realization, not projection reduction, so every query fails
    /// safe (no aliases, memberships, bounds, or reducible projections).
    struct NoCtx;
    impl TypeContext for NoCtx {
        fn alias_def(&self, _: &QualifiedTypeName) -> Option<Ty> {
            None
        }
        fn implements_interface(&self, _: &Ty, _: &Interface) -> bool {
            false
        }
        fn type_var_bound(&self, _: &crate::ParamTy) -> Vec<Interface> {
            Vec::new()
        }
        fn interface_requires(&self, _: &Interface, _: &Interface) -> bool {
            false
        }
        fn enum_variants(&self, _: &QualifiedTypeName) -> Option<Vec<Name>> {
            None
        }
        fn associated_type_bound(&self, _: &Interface, _: Name) -> Vec<Interface> {
            Vec::new()
        }
        fn project(&self, _: &Ty, _: &Interface, _: &Name, _fuel: u32) -> ProjectionStep {
            ProjectionStep::Opaque
        }
    }

    /// Build a `RealizedTy` frame argument from a `RuntimeTy` constructor.
    fn r(ty: RuntimeTy) -> RealizedTy {
        RealizedTy::try_from(ty).expect("test arg is realized")
    }

    /// Materialize against a frame, upcasting the realized result to `RuntimeTy`
    /// so it can be compared with `RuntimeTy`'s ergonomic constructors.
    fn sub(tmpl: &TyTemplate, args: &[RealizedTy]) -> RuntimeTy {
        RuntimeTy::from(
            tmpl.substitute(args, &NoCtx)
                .expect("substitution realizes"),
        )
    }

    #[test]
    fn concrete_template_substitutes_to_itself() {
        let tmpl = TyTemplate::from(RealizedTy::int());
        assert_eq!(sub(&tmpl, &[]), RuntimeTy::int());
        assert!(tmpl.is_fully_concrete());
    }

    #[test]
    fn type_arg_ref_substitutes_correctly() {
        let tmpl = TyTemplate::TypeArgRef(0);
        assert_eq!(sub(&tmpl, &[r(RuntimeTy::string())]), RuntimeTy::string());
        assert!(!tmpl.is_fully_concrete());
    }

    #[test]
    fn array_of_type_arg_ref() {
        // list<#0> with type_args=[int] → int[]
        let tmpl = TyTemplate::list(TyTemplate::TypeArgRef(0));
        assert_eq!(
            sub(&tmpl, &[r(RuntimeTy::int())]),
            RuntimeTy::list(RuntimeTy::int())
        );
        assert!(!tmpl.is_fully_concrete());
    }

    #[test]
    fn optional_of_type_arg_ref() {
        // (#0 | null) with type_args=[string] → string?
        let tmpl = TyTemplate::union([
            TyTemplate::TypeArgRef(0),
            TyTemplate::from(RealizedTy::null()),
        ]);
        assert_eq!(
            sub(&tmpl, &[r(RuntimeTy::string())]),
            RuntimeTy::optional(RuntimeTy::string())
        );
        assert!(!tmpl.is_fully_concrete());
    }

    #[test]
    fn out_of_range_type_arg_ref_is_an_error() {
        // A template's indices only reference the surrounding frame — the
        // compiler seeds generic frames at full declared width (an
        // unconstrained param is an explicit `unknown` slot, never omitted) —
        // so an out-of-range ref is a frame-layout bug, reported in every
        // build profile rather than silently realized as `unknown`.
        let tmpl = TyTemplate::TypeArgRef(0);
        assert_eq!(
            tmpl.substitute(&[], &NoCtx),
            Err(SubstituteError::TypeArgRefOutOfRange {
                index: 0,
                frame_len: 0
            })
        );
    }

    /// `(#0 as Cyclic).member` — a projection whose base is a realized frame ref.
    fn cyclic_projection(member: crate::Name) -> TyTemplate {
        TyTemplate::AssociatedTypeProjection {
            base: Box::new(TyTemplate::TypeArgRef(0)),
            interface: Box::new(TyTemplateInterface {
                name: TypeName::local(crate::Name::new("Cyclic")),
                generics: vec![],
                associated_types: vec![],
            }),
            member,
            attr: TyAttr::default(),
        }
    }

    /// A context whose every projection reduces by realizing *the same* projection
    /// again — a cyclic associated-type binding. Without the fuel backstop this
    /// recurses forever; with it, the chain exhausts its budget and fails.
    struct CyclicCtx;
    impl TypeContext for CyclicCtx {
        fn alias_def(&self, _: &QualifiedTypeName) -> Option<Ty> {
            None
        }
        fn implements_interface(&self, _: &Ty, _: &Interface) -> bool {
            false
        }
        fn type_var_bound(&self, _: &crate::ParamTy) -> Vec<Interface> {
            Vec::new()
        }
        fn interface_requires(&self, _: &Interface, _: &Interface) -> bool {
            false
        }
        fn enum_variants(&self, _: &QualifiedTypeName) -> Option<Vec<Name>> {
            None
        }
        fn associated_type_bound(&self, _: &Interface, _: Name) -> Vec<Interface> {
            Vec::new()
        }
        fn project(&self, _: &Ty, _: &Interface, member: &Name, fuel: u32) -> ProjectionStep {
            // The binding for `member` is the same projection, so realizing it
            // re-enters `project`. The threaded `fuel` bounds the cycle; an
            // exhausted budget surfaces as a substitution error (→ `Opaque`).
            match cyclic_projection(member.clone()).substitute_with_fuel(
                &[RealizedTy::unknown()],
                self,
                fuel,
            ) {
                Ok(reduced) => ProjectionStep::Reduced(reduced.into()),
                Err(_) => ProjectionStep::Opaque,
            }
        }
    }

    #[test]
    fn projection_fuel_guard_fires_at_zero() {
        // With no remaining budget a projection cannot even attempt its reduction.
        let proj = cyclic_projection(crate::Name::new("Item"));
        assert_eq!(
            proj.substitute_with_fuel(&[RealizedTy::unknown()], &CyclicCtx, 0),
            Err(SubstituteError::ProjectionFuelExhausted {
                member: crate::Name::new("Item"),
            })
        );
    }

    #[test]
    fn cyclic_projection_terminates_instead_of_overflowing() {
        // A cyclic associated-type binding would realize to itself forever without
        // the backstop; with it, the chain exhausts its fuel and fails rather than
        // overflowing the stack.
        let proj = cyclic_projection(crate::Name::new("Item"));
        assert!(
            proj.substitute_with_fuel(&[RealizedTy::unknown()], &CyclicCtx, 16)
                .is_err()
        );
    }

    #[test]
    fn concrete_array_is_fully_concrete() {
        let tmpl = TyTemplate::list(TyTemplate::from(RealizedTy::int()));
        assert!(tmpl.is_fully_concrete());
    }

    #[test]
    fn union_of_concrete_is_fully_concrete() {
        let tmpl = TyTemplate::union([
            TyTemplate::from(RealizedTy::int()),
            TyTemplate::from(RealizedTy::string()),
        ]);
        assert!(tmpl.is_fully_concrete());
        assert_eq!(
            sub(&tmpl, &[]),
            RuntimeTy::union([RuntimeTy::int(), RuntimeTy::string()])
        );
    }

    #[test]
    fn union_containing_type_arg_ref_not_concrete() {
        let tmpl = TyTemplate::union([
            TyTemplate::from(RealizedTy::int()),
            TyTemplate::TypeArgRef(0),
        ]);
        assert!(!tmpl.is_fully_concrete());
    }

    #[test]
    fn class_with_type_arg_ref_substitution() {
        let tmpl = TyTemplate::class(
            TypeName::local(crate::Name::new("Container")),
            vec![TyTemplate::TypeArgRef(0)],
        );
        let user = RuntimeTy::user_class("User");
        assert_eq!(
            sub(&tmpl, &[r(user.clone())]),
            RuntimeTy::class_with_args(TypeName::local(crate::Name::new("Container")), vec![user])
        );
        assert!(!tmpl.is_fully_concrete());
    }

    #[test]
    fn class_no_args_is_fully_concrete() {
        let tmpl = TyTemplate::class(TypeName::local(crate::Name::new("User")), vec![]);
        assert!(tmpl.is_fully_concrete());
        assert_eq!(
            sub(&tmpl, &[]),
            RuntimeTy::Class(
                TypeName::local(crate::Name::new("User")),
                vec![],
                crate::TyAttr::default()
            )
        );
    }
}
