// String-builder style: the registration and anchor bodies are assembled
// by appending rendered fragments; the `write!`-into-String alternative
// buys nothing here but noise (same rationale as `emit.rs`).
#![allow(clippy::format_push_string)]

//! Java SDK emitter. Produces a `baml_sdk/` tree from a `SymbolPool`:
//! one `.java` file per generated top (Java allows one public type per
//! file), a per-package `Fns` holder binding free functions to the
//! `baml_bridge.BamlFfi` runtime entry points, minted sealed-union
//! types, a root `Baml.java` runtime anchor, and the compiled BAML
//! bytecode as a base64 classpath resource (`inlinedbaml.b64` — Java
//! caps a static initializer at 64KB of JVM bytecode, so a
//! `new byte[]{...}` literal like TS's `_inlinedbaml.ts` cannot work).
//!
//! Unlike TS, Java needs no barrel/`index` files: a package exists by
//! virtue of its directory, so container namespaces emit nothing.
//! Type expressions come from `translate_ty` and are fully qualified,
//! so no import machinery exists either.
//!
//! Not yet emitted (later capabilities): explicit generic type-args
//! overloads, the typemap, runtime init in `Baml.java`.
//!
//! Generated-API conventions live in
//! `sdks/agent-docs/bridge-ref/ref-java-codegen-conventions.md`.

mod emit;
mod routing;
mod translate_ty;

use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    path::PathBuf,
};

use baml_base::qualified_name::{AI_STREAM_DONE, AI_STREAM_STREAM};
use baml_codegen_types::{Function, Symbol, SymbolPool, Ty};
pub use baml_codegen_types::{NamingConvention, OutputType};

use crate::{
    emit::{render_class, render_enum, render_fns_holder, render_union},
    routing::{PackagePath, java_identifier, route},
    translate_ty::{AliasTable, TranslateCtx, UnionSink, descriptor_expr_opt, registry_arm_expr},
};

/// Banner prepended to every generated `.java` file. Mirrors the TS
/// emitter's `NODE_BANNER`.
const JAVA_BANNER: &str = "\
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, add the baml-bridge
//  dependency to your build.
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// baml-cli is available with the baml package.

";

/// Runtime-owned stdlib types. Their bodies live in the
/// `baml-bridge` runtime library (callers need the runtime's
/// constructors and handle identity — a generated structural class
/// would not round-trip), so codegen must not emit a class for them.
/// Mirrors the TS emitter's re-export set; how the runtime library
/// claims these package paths is a `bridge_java` decision.
const RUNTIME_OWNED_FQNS: &[&str] = &[
    "baml.media.Image",
    "baml.media.Audio",
    "baml.media.Video",
    "baml.media.Pdf",
    AI_STREAM_STREAM,
    // The stream-done sentinel is runtime-owned: its body ships in
    // `baml-bridge` as `baml_sdk.ai.stream.Done` and
    // is registered in the typemap by the runtime (TypeRegistry static block),
    // so the emitter must not also generate a split-package `Done.java`.
    AI_STREAM_DONE,
];

/// One enum typemap entry: (BAML FQN, Java binary name, per-variant
/// (java const ident, wire name)).
type EnumRegistration = (String, String, Vec<(String, String)>);

/// One union typemap registration. `alias_fqn` is `None` for the structural
/// registration (keyed by the arm set, derived runtime-side from the arms) and
/// `Some(fqn)` for a recursive alias's second registration under its own FQN.
/// `arms` is per-arm `(arm-token BamlType expression, record binary name)` in
/// declaration order.
#[derive(PartialEq, Eq, PartialOrd, Ord)]
struct UnionReg {
    alias_fqn: Option<String>,
    union_binary: String,
    arms: Vec<(String, String)>,
}

/// Build the Java SDK output tree for `pool`. Returned paths are
/// relative to the `baml_sdk/` output root.
pub fn to_source_code(
    pool: &SymbolPool,
    baml_bytecode: &[u8],
    naming_convention: NamingConvention,
) -> HashMap<PathBuf, String> {
    to_source_code_internal(pool, baml_bytecode, None, naming_convention)
}

fn to_source_code_internal(
    pool: &SymbolPool,
    baml_bytecode: &[u8],
    embedded_baml_toml: Option<&str>,
    naming_convention: NamingConvention,
) -> HashMap<PathBuf, String> {
    // Only `PreserveCase` is wired up so far.
    assert!(
        matches!(naming_convention, NamingConvention::PreserveCase),
        "sdkgen_java only supports naming_convention = PreserveCase (got {naming_convention})",
    );
    let mut out: HashMap<PathBuf, String> = HashMap::new();

    // Alias table for translate_ty: non-recursive aliases erase at
    // use sites; recursive ones keep a nominal name.
    let mut aliases = AliasTable::new();
    for (name, symbol) in pool {
        if let Symbol::TypeAlias(alias) = symbol {
            aliases.insert(name.clone(), (alias.resolves_to.clone(), alias.recursive));
        }
    }

    // The root runtime anchor is `baml_sdk.Baml` — unless a user BAML type at
    // the ROOT namespace already claims the `Baml` name (its generated file
    // would otherwise be overwritten by `out.insert`), in which case the ANCHOR
    // escapes to `Baml$` (the same trailing-`$` policy as `Fns` → `Fns$`) and
    // the user's `Baml` file is preserved. The chosen name threads through every
    // `<root>.Baml.ensure()` reference (the `Fns` holders and each binding
    // class's runtime-init static block).
    let anchor_ident = root_anchor_ident(pool);
    let anchor_fqn = format!("baml_sdk.{anchor_ident}");

    // Group symbols per package. BTreeMap/BTreeSet for deterministic
    // output independent of the pool's HashMap iteration order.
    let mut sink = UnionSink::default();
    // Typemap entries generated into Baml.java's static initializer:
    // (BAML FQN, Java binary name, per-kind payload). Field order is
    // carried explicitly because the JVM does not guarantee
    // getDeclaredFields() order and the decoder constructs via the
    // canonical constructor positionally. Classes also carry a parallel
    // per-field decode-descriptor array (same order as the field idents).
    let mut class_registry: Vec<(String, String, Vec<String>, Vec<String>)> = Vec::new();
    let mut enum_registry: Vec<EnumRegistration> = Vec::new();
    let mut fns_per_package: BTreeMap<PackagePath, Vec<(u32, String, &Function)>> = BTreeMap::new();
    let mut type_idents_per_package: BTreeMap<PackagePath, BTreeSet<String>> = BTreeMap::new();
    let mut type_files: Vec<(PackagePath, String, String)> = Vec::new(); // (pkg, ident, body)
    let mut recursive_aliases: Vec<(PackagePath, String, String, &Ty)> = Vec::new();
    let mut union_registry: Vec<UnionReg> = Vec::new();

    for (name, symbol) in pool {
        let pkg = route(name);
        let symbol_fqn = {
            let mut s = String::from(name.package().as_str());
            for seg in name.namespace() {
                s.push('.');
                s.push_str(seg.as_str());
            }
            s.push('.');
            s.push_str(name.name().as_str());
            s
        };
        let is_runtime_owned = RUNTIME_OWNED_FQNS.contains(&symbol_fqn.as_str());
        let ctx = TranslateCtx {
            aliases: &aliases,
            pkg: pkg.clone(),
        };

        match symbol {
            Symbol::Class(class) => {
                if is_runtime_owned {
                    continue;
                }
                let ident = java_identifier(class.name.name().as_str());
                type_idents_per_package
                    .entry(pkg.clone())
                    .or_default()
                    .insert(ident.clone());
                class_registry.push((
                    symbol_fqn.clone(),
                    format!("{}.{}", pkg.java_package(), ident),
                    class
                        .properties
                        .iter()
                        .map(|prop| java_identifier(prop.name.as_str()))
                        .collect(),
                    class
                        .properties
                        .iter()
                        .map(|prop| {
                            descriptor_expr_opt(&prop.ty, &aliases)
                                .unwrap_or_else(|| "null".to_string())
                        })
                        .collect(),
                ));
                type_files.push((
                    pkg,
                    ident,
                    render_class(class, &symbol_fqn, &anchor_fqn, &ctx, &mut sink),
                ));
            }
            Symbol::Enum(enum_) => {
                let ident = java_identifier(enum_.name.name().as_str());
                type_idents_per_package
                    .entry(pkg.clone())
                    .or_default()
                    .insert(ident.clone());
                enum_registry.push((
                    symbol_fqn.clone(),
                    format!("{}.{}", pkg.java_package(), ident),
                    enum_
                        .variants
                        .iter()
                        .map(|v| {
                            (
                                java_identifier(v.name.as_str()),
                                v.name.as_str().to_string(),
                            )
                        })
                        .collect(),
                ));
                type_files.push((pkg, ident, render_enum(enum_)));
            }
            Symbol::Function(function) => {
                fns_per_package.entry(pkg).or_default().push((
                    function.origin.span_start,
                    symbol_fqn,
                    function,
                ));
            }
            // Non-recursive aliases erase at every use site; recursive
            // aliases mint a nominal type (emitted below).
            Symbol::TypeAlias(alias) if alias.recursive => {
                let ident = java_identifier(name.name().as_str());
                type_idents_per_package
                    .entry(pkg.clone())
                    .or_default()
                    .insert(ident.clone());
                recursive_aliases.push((pkg, ident, symbol_fqn.clone(), &alias.resolves_to));
            }
            Symbol::TypeAlias(_) => {}
        }
    }

    for (pkg, ident, body) in type_files {
        out.insert(java_file_path(&pkg, &ident), with_package(&pkg, &body));
    }

    // Per-package free-function holders. `Fns$` when a generated type
    // in the same package is already named `Fns`.
    for (pkg, mut entries) in fns_per_package {
        entries.sort_by(|a, b| (a.0, a.1.as_str()).cmp(&(b.0, b.1.as_str())));
        let functions: Vec<(String, &Function)> =
            entries.into_iter().map(|(_, fqn, f)| (fqn, f)).collect();
        let taken = type_idents_per_package.get(&pkg);
        let holder = if taken.is_some_and(|set| set.contains("Fns")) {
            "Fns$"
        } else {
            "Fns"
        };
        let ctx = TranslateCtx {
            aliases: &aliases,
            pkg: pkg.clone(),
        };
        out.insert(
            java_file_path(&pkg, holder),
            with_package(
                &pkg,
                &render_fns_holder(
                    holder,
                    &pkg.java_package(),
                    &anchor_fqn,
                    &functions,
                    &ctx,
                    &mut sink,
                ),
            ),
        );
    }

    // Recursive aliases: a recursive alias over a union renders as a
    // minted union under the alias's own name; other recursive shapes
    // get a reserved placeholder until the aliases capability lands.
    for (pkg, ident, alias_fqn, resolves_to) in recursive_aliases {
        let ctx = TranslateCtx {
            aliases: &aliases,
            pkg: pkg.clone(),
        };
        let body = if let Ty::Union(items, _) = resolves_to {
            let arms: Vec<Ty> = items
                .iter()
                .filter(|t| !matches!(t, Ty::Null { .. }))
                .cloned()
                .collect();
            let (union_binary, arm_entries) = union_registration(&pkg, &ident, &arms, &aliases);
            // Two registrations — by the arm SET (structural, derived runtime-side)
            // AND by the alias's own FQN: the engine may send self_type either
            // resolved (the member union) or as the alias node, depending on how
            // the declared type was spelled.
            union_registry.push(UnionReg {
                alias_fqn: None,
                union_binary: union_binary.clone(),
                arms: arm_entries.clone(),
            });
            union_registry.push(UnionReg {
                alias_fqn: Some(alias_fqn.clone()),
                union_binary,
                arms: arm_entries,
            });
            render_union(&ident, &arms, &ctx, &mut sink)
        } else {
            format!(
                "/** Recursive type alias — full support lands with the aliases capability. */\npublic final class {ident} {{\n    private {ident}() {{}}\n}}\n"
            )
        };
        out.insert(java_file_path(&pkg, &ident), with_package(&pkg, &body));
    }

    // Anonymous multi-arm unions no longer mint nominal files: they
    // render inline as the runtime's generic arity family
    // (`baml_bridge.Union{n}<...>`) and decode is type-directed via the
    // per-binding descriptors, so nothing records into `sink.unions`.
    // The only nominal union files are the recursive aliases emitted
    // above (a positional generic cannot reference itself).

    // Host-callable functional interfaces (design point E): a callable whose
    // own type carries optional params / arity > 2 has no `java.util.function`
    // shape, so `translate_callable` minted a `@FunctionalInterface` (recorded in
    // `sink.callbacks`, deduped per package). Emit one file per interface beside
    // its owning package, after all rendering has populated the sink.
    for (pkg, entries) in &sink.callbacks {
        for (_, iface) in entries {
            out.insert(
                java_file_path(pkg, &iface.name),
                with_package(pkg, &emit::render_callback_interface(iface)),
            );
        }
    }

    // Root runtime anchor. Loading any generated class must (in a
    // later phase) trigger idempotent runtime initialization from the
    // embedded bytecode — the Java analog of Python's root-package
    // import side effect.
    let root = PackagePath {
        segments: Vec::new(),
    };
    class_registry.sort();
    enum_registry.sort();
    union_registry.sort();
    union_registry.dedup();
    let mut registrations = String::new();
    for reg in &union_registry {
        // Arm tokens are BamlType builder EXPRESSIONS (emitted raw); record binary
        // names are strings. The structural key is derived runtime-side from the
        // arms, so the emitter renders no grammar string.
        let tokens: Vec<String> = reg.arms.iter().map(|(t, _)| t.clone()).collect();
        let records: Vec<String> = reg.arms.iter().map(|(_, r)| format!("{r:?}")).collect();
        let union_binary = &reg.union_binary;
        match &reg.alias_fqn {
            None => registrations.push_str(&format!(
                "        baml_bridge.TypeRegistry.registerUnion({union_binary:?}, new baml_bridge.BamlType[] {{{}}}, new java.lang.String[] {{{}}});\n",
                tokens.join(", "),
                records.join(", ")
            )),
            Some(alias_fqn) => registrations.push_str(&format!(
                "        baml_bridge.TypeRegistry.registerUnionAlias({alias_fqn:?}, {union_binary:?}, new baml_bridge.BamlType[] {{{}}}, new java.lang.String[] {{{}}});\n",
                tokens.join(", "),
                records.join(", ")
            )),
        }
    }
    for (fqn, java_name, fields, descriptors) in &class_registry {
        let field_list: Vec<String> = fields.iter().map(|f| format!("{f:?}")).collect();
        // Field descriptors are BamlType builder expressions (or the literal
        // `null` for a wire-driven field) — emitted raw.
        registrations.push_str(&format!(
            "        baml_bridge.TypeRegistry.registerClass({fqn:?}, {java_name:?}, new java.lang.String[] {{{}}}, new baml_bridge.BamlType[] {{{}}});\n",
            field_list.join(", "),
            descriptors.join(", ")
        ));
    }
    for (fqn, java_name, variants) in &enum_registry {
        let consts: Vec<String> = variants.iter().map(|(c, _)| format!("{c:?}")).collect();
        let wires: Vec<String> = variants.iter().map(|(_, w)| format!("{w:?}")).collect();
        registrations.push_str(&format!(
            "        baml_bridge.TypeRegistry.registerEnum({fqn:?}, {java_name:?}, new java.lang.String[] {{{}}}, new java.lang.String[] {{{}}});\n",
            consts.join(", "),
            wires.join(", ")
        ));
    }
    let anchor_body = format!(
        "/**\n * Runtime anchor for the generated SDK: loading this class registers\n * the type map (BAML FQN \u{2194} generated class, with field declaration\n * order) and initializes the BAML runtime from the embedded bytecode\n * resource (idempotent) \u{2014} the Java analog of Python's root-package\n * import side effect. Every generated binding holder forces this via\n * {{@link #ensure()}}.\n */\npublic final class {anchor_ident} {{\n    private {anchor_ident}() {{}}\n\n    static {{\n{registrations}        try (java.io.InputStream in = {anchor_ident}.class.getResourceAsStream(\"/baml_sdk/inlinedbaml.b64\")) {{\n            if (in == null) {{\n                throw new IllegalStateException(\n                        \"baml_sdk/inlinedbaml.b64 not found on the classpath \u{2014} is the generated resource root registered?\");\n            }}\n            byte[] b64 = in.readAllBytes();\n            byte[] bytecode = java.util.Base64.getMimeDecoder().decode(b64);\n            baml_bridge.BamlFfi.initFromBytecode(bytecode);\n        }} catch (java.io.IOException e) {{\n            throw new java.io.UncheckedIOException(\"failed to read embedded BAML bytecode\", e);\n        }}\n    }}\n\n    /** Forces class initialization (and thus runtime init). No-op afterwards. */\n    public static void ensure() {{}}\n}}\n"
    );
    let anchor_body = if embedded_baml_toml.is_some() {
        anchor_body.replace(
            "            baml_bridge.BamlFfi.initFromBytecode(bytecode);",
            &format!(
                "            try (java.io.InputStream manifestIn = {anchor_ident}.class.getResourceAsStream(\"/baml_sdk/inlinedbaml.toml\")) {{\n                if (manifestIn == null) {{\n                    throw new IllegalStateException(\"baml_sdk/inlinedbaml.toml not found on the classpath\");\n                }}\n                String embeddedBamlToml = new String(manifestIn.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);\n                baml_bridge.BamlFfi.initFromBytecode(bytecode, embeddedBamlToml);\n            }}"
            ),
        )
    } else {
        anchor_body
    };
    out.insert(
        java_file_path(&root, anchor_ident),
        with_package(&root, &anchor_body),
    );

    // Compiled BAML bytecode as a base64 text resource. Base64 keeps
    // the emitter's `HashMap<PathBuf, String>` contract (raw bytecode
    // is not valid UTF-8) and dodges Java's 64KB static-initializer /
    // constant-pool limits that rule out a byte-array literal.
    out.insert(
        PathBuf::from("inlinedbaml.b64"),
        base64_encode(baml_bytecode),
    );
    if let Some(embedded_baml_toml) = embedded_baml_toml {
        out.insert(
            PathBuf::from("inlinedbaml.toml"),
            embedded_baml_toml.to_string(),
        );
    }

    // Prepend the do-not-edit banner to every `.java` file.
    for (path, content) in &mut out {
        let is_java = path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| e == "java");
        if is_java {
            content.insert_str(0, JAVA_BANNER);
        }
    }

    out
}

pub fn to_source_code_with_bytecode(
    pool: &SymbolPool,
    baml_bytecode: &[u8],
    naming_convention: NamingConvention,
) -> HashMap<PathBuf, String> {
    to_source_code(pool, baml_bytecode, naming_convention)
}

pub fn to_source_code_with_bytecode_and_metadata(
    pool: &SymbolPool,
    baml_bytecode: &[u8],
    embedded_baml_toml: &str,
    naming_convention: NamingConvention,
) -> HashMap<PathBuf, String> {
    to_source_code_internal(
        pool,
        baml_bytecode,
        Some(embedded_baml_toml),
        naming_convention,
    )
}

/// A structural string token for a type, used ONLY as the emitter-internal
/// dedup key for a minted host-callable functional interface
/// ([`crate::translate_ty::callback_signature_key`]) — it never crosses to the
/// Java runtime. A generic class carries its concrete args (`Wrapper<int>` vs
/// `Wrapper<string>`) so distinct instantiations get distinct keys. (Union arm
/// tokens and decode descriptors are typed `BamlType`s now — see
/// `crate::translate_ty::registry_arm_expr` / `descriptor_expr`; this token no
/// longer feeds any registry key or wire comparison, so it carries the raw
/// literal value with no escaping.)
pub(crate) fn signature_token(ty: &Ty, aliases: &AliasTable) -> String {
    match ty {
        Ty::Int { .. } => "int".to_string(),
        Ty::Bigint { .. } => "bigint".to_string(),
        Ty::Float { .. } => "float".to_string(),
        Ty::String { .. } => "string".to_string(),
        Ty::Bool { .. } => "bool".to_string(),
        Ty::Null { .. } => "null".to_string(),
        Ty::Uint8Array { .. } => "uint8array".to_string(),
        Ty::Void { .. } => "void".to_string(),
        Ty::Unknown { .. } => "unknown".to_string(),
        // A generic class carries its concrete type args in its identity token
        // (`Wrapper<int>` vs `Wrapper<string>`) — kept for parity with
        // `registry_arm_expr`, which distinguishes two instantiations so a union /
        // registry key can't silently first-win. (The class *descriptor* path
        // stays bare — see `descriptor_expr`'s `Class` arm — so class decode still
        // resolves by FQN.)
        Ty::Class(name, args, _) => {
            let base = baml_fqn(name);
            if args.is_empty() {
                base
            } else {
                let inner: Vec<String> = args.iter().map(|a| signature_token(a, aliases)).collect();
                format!("{base}<{}>", inner.join(","))
            }
        }
        Ty::Enum(name, _) | Ty::EnumVariant(name, _, _) => baml_fqn(name),
        Ty::TypeAlias(name, _) => match aliases.get(name) {
            Some((resolved, false)) => signature_token(resolved, aliases),
            _ => baml_fqn(name),
        },
        Ty::TypeVar(name, _) => format!("tv:{}", name.as_str()),
        Ty::List(inner, _) => format!("list<{}>", signature_token(inner, aliases)),
        Ty::Map { key, value, .. } => format!(
            "map<{},{}>",
            signature_token(key, aliases),
            signature_token(value, aliases)
        ),
        Ty::Literal(lit, ..) => match lit {
            baml_base::Literal::Int(v) => format!("lit:int:{v}"),
            baml_base::Literal::Bigint(v) => format!("lit:bigint:{v}"),
            baml_base::Literal::Float(v) => format!("lit:float:{v}"),
            baml_base::Literal::String(v) => format!("lit:string:{v}"),
            baml_base::Literal::Bool(v) => format!("lit:bool:{v}"),
        },
        Ty::Media(kind, _) => format!("media:{}", format!("{kind:?}").to_lowercase()),
        Ty::Function { .. } => "callable".to_string(),
        Ty::RustType { .. } => "handle".to_string(),
        // Types the Java SDK does not model yet collapse to the opaque
        // `unknown` token (the conservative "?"-token fallback).
        Ty::Interface(..)
        | Ty::Type { .. }
        | Ty::Resource { .. }
        | Ty::PromptAst { .. }
        | Ty::Never { .. }
        | Ty::Future(..) => "unknown".to_string(),
        Ty::Union(..) => "union".to_string(), // banned by validate(); defensive
    }
}

/// The canonical dotted BAML FQN of a named type (`pkg.namespace….Name`),
/// shared by [`signature_token`] and the typed decode-descriptor builders in
/// [`crate::translate_ty`].
pub(crate) fn baml_fqn(name: &baml_codegen_types::Name) -> String {
    let mut s = String::from(name.package().as_str());
    for seg in name.namespace() {
        s.push('.');
        s.push_str(seg.as_str());
    }
    s.push('.');
    s.push_str(name.name().as_str());
    s
}

/// Build one union registry entry: the sealed interface's binary name and
/// per-arm `(arm-token BamlType expression, record binary name)` pairs in
/// declaration order. Record binary names use the `$` nested separator
/// (`baml_sdk.unions.UnionIntOrString$IntValue`). The registry key is derived
/// runtime-side from the arm set (sorted + distinct `List<BamlType>`), so the
/// emitter renders no signature string.
fn union_registration(
    pkg: &PackagePath,
    ident: &str,
    arms: &[Ty],
    aliases: &AliasTable,
) -> (String, Vec<(String, String)>) {
    let union_binary = format!("{}.{}", pkg.java_package(), ident);
    let arm_tokens = crate::translate_ty::union_arm_tokens(arms);
    let arm_entries: Vec<(String, String)> = arms
        .iter()
        .zip(&arm_tokens)
        .map(|(arm, token)| {
            (
                registry_arm_expr(arm, aliases),
                format!("{union_binary}${token}Value"),
            )
        })
        .collect();
    (union_binary, arm_entries)
}

/// The root runtime-anchor class name: `Baml`, or `Baml$` when a user BAML type
/// at the ROOT namespace generates a file that would claim the `Baml` name (a
/// root-package `Class`/`Enum`/recursive `TypeAlias`). Non-recursive aliases
/// erase (no file), and functions land on `Fns`, so only those three kinds can
/// collide. Mirrors the `Fns` → `Fns$` holder escape.
fn root_anchor_ident(pool: &SymbolPool) -> &'static str {
    let claimed = pool.iter().any(|(name, symbol)| {
        route(name).segments.is_empty()
            && java_identifier(name.name().as_str()) == "Baml"
            && match symbol {
                Symbol::Class(_) | Symbol::Enum(_) => true,
                Symbol::TypeAlias(alias) => alias.recursive,
                Symbol::Function(_) => false,
            }
    });
    if claimed { "Baml$" } else { "Baml" }
}

fn java_file_path(pkg: &PackagePath, ident: &str) -> PathBuf {
    let mut path = PathBuf::new();
    for seg in &pkg.segments {
        path.push(seg);
    }
    path.push(format!("{ident}.java"));
    path
}

fn with_package(pkg: &PackagePath, body: &str) -> String {
    format!("package {};\n\n{body}", pkg.java_package())
}

/// Standard-alphabet base64 with padding, dependency-free. The
/// bytecode payload is written once per fixture at build time, so
/// encoder throughput is irrelevant.
fn base64_encode(data: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(data.len().div_ceil(3) * 4);
    for chunk in data.chunks(3) {
        let b = [
            chunk[0],
            chunk.get(1).copied().unwrap_or(0),
            chunk.get(2).copied().unwrap_or(0),
        ];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        out.push(ALPHABET[(n >> 18) as usize & 63] as char);
        out.push(ALPHABET[(n >> 12) as usize & 63] as char);
        out.push(if chunk.len() > 1 {
            ALPHABET[(n >> 6) as usize & 63] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            ALPHABET[n as usize & 63] as char
        } else {
            '='
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use baml_base::Name as BaseName;
    use baml_codegen_types::{
        Class, ClassProperty, Enum, EnumVariant, Function, FunctionArgument, Name, Origin, Symbol,
        SymbolPool, Ty, TypeAlias,
    };

    use super::*;

    fn name(pkg: &str, ns: &[&str], n: &str) -> Name {
        Name::new(
            BaseName::new(pkg),
            ns.iter().map(|s| BaseName::new(*s)).collect(),
            BaseName::new(n),
        )
    }

    fn origin(span: u32) -> Origin {
        Origin {
            source_file_path: "main.baml".to_string(),
            span_start: span,
        }
    }

    // Leaf-type constructors: the codegen `Ty` variants now carry a
    // `TyAttr`, so these keep the fixture builders readable.
    fn a() -> baml_base::TyAttr {
        baml_base::TyAttr::EMPTY
    }
    fn t_int() -> Ty {
        Ty::Int { attr: a() }
    }
    fn t_float() -> Ty {
        Ty::Float { attr: a() }
    }
    fn t_string() -> Ty {
        Ty::String { attr: a() }
    }
    fn nullary_fn(fn_name: &str, span: u32) -> Function {
        Function {
            name: BaseName::new(fn_name),
            generic_params: Vec::new(),
            docstring: None,
            arguments: Vec::new(),
            return_type: t_int(),
            throws: None,
            watchers: Vec::new(),
            origin: origin(span),
        }
    }
    fn t_uint8array() -> Ty {
        Ty::Uint8Array { attr: a() }
    }
    fn t_typevar(n: &str) -> Ty {
        Ty::TypeVar(baml_codegen_types::ParamTy::new(0, BaseName::new(n)), a())
    }
    fn t_union(items: Vec<Ty>) -> Ty {
        Ty::Union(items, a())
    }
    fn t_list(inner: Ty) -> Ty {
        Ty::List(Box::new(inner), a())
    }
    fn t_alias(n: Name) -> Ty {
        Ty::TypeAlias(n, a())
    }
    fn t_class(n: Name) -> Ty {
        Ty::Class(n, Vec::new(), a())
    }
    fn t_null() -> Ty {
        Ty::Null { attr: a() }
    }
    /// `T?` — a nullable BAML type (`T | null`).
    fn t_opt(inner: Ty) -> Ty {
        Ty::Union(vec![inner, t_null()], a())
    }

    fn class_sym_with_props(
        n: &Name,
        generic_params: &[&str],
        props: Vec<(&str, Ty)>,
        span: u32,
    ) -> Symbol {
        Symbol::Class(Class {
            name: n.clone(),
            generic_params: generic_params.iter().map(|p| BaseName::new(*p)).collect(),
            docstring: None,
            properties: props
                .into_iter()
                .map(|(p_name, ty)| ClassProperty {
                    name: BaseName::new(p_name),
                    docstring: None,
                    ty,
                })
                .collect(),
            static_methods: Vec::new(),
            instance_methods: Vec::new(),
            origin: origin(span),
        })
    }

    fn class_sym(n: &Name, generic_params: &[&str], span: u32) -> Symbol {
        class_sym_with_props(n, generic_params, Vec::new(), span)
    }

    fn enum_sym(n: &Name, span: u32) -> Symbol {
        Symbol::Enum(Enum {
            name: n.clone(),
            docstring: None,
            variants: vec![
                EnumVariant {
                    name: BaseName::new("Positive"),
                    docstring: None,
                    value: "Positive".to_string(),
                },
                EnumVariant {
                    name: BaseName::new("new"),
                    docstring: None,
                    value: "new".to_string(),
                },
            ],
            origin: origin(span),
        })
    }

    fn func_sym(span: u32) -> Symbol {
        Symbol::Function(Function {
            name: BaseName::new("extract_resume"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![FunctionArgument {
                injected: false,
                name: BaseName::new("x"),
                docstring: None,
                ty: t_int(),
                default: None,
            }],
            return_type: t_int(),
            throws: None,
            watchers: Vec::new(),
            origin: origin(span),
        })
    }

    /// A one-argument method `Function` (same shape the pool builder
    /// hands the class emitter). The receiver is never listed here —
    /// the emitter prepends it for instance methods.
    fn method_fn(name: &str, arg: (&str, Ty), ret: Ty, span: u32) -> Function {
        Function {
            name: BaseName::new(name),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![FunctionArgument {
                injected: false,
                name: BaseName::new(arg.0),
                docstring: None,
                ty: arg.1,
                default: None,
            }],
            return_type: ret,
            throws: None,
            watchers: Vec::new(),
            origin: origin(span),
        }
    }

    fn class_sym_with_methods(
        n: &Name,
        static_methods: Vec<Function>,
        instance_methods: Vec<Function>,
        span: u32,
    ) -> Symbol {
        Symbol::Class(Class {
            name: n.clone(),
            generic_params: Vec::new(),
            docstring: None,
            properties: Vec::new(),
            static_methods,
            instance_methods,
            origin: origin(span),
        })
    }

    /// A recursive type alias `RecList = int | RecList[]` — self-
    /// referential, so `recursive: true`.
    fn recursive_alias_sym(n: &Name, span: u32) -> Symbol {
        Symbol::TypeAlias(TypeAlias {
            name: n.clone(),
            resolves_to: t_union(vec![t_int(), t_list(t_alias(n.clone()))]),
            recursive: true,
            origin: origin(span),
        })
    }

    fn emit_sdk(pool: &SymbolPool) -> HashMap<PathBuf, String> {
        to_source_code(pool, &[], NamingConvention::PreserveCase)
    }

    #[test]
    fn empty_pool_emits_structural_files() {
        let out = emit_sdk(&SymbolPool::new());
        assert!(out.contains_key(&PathBuf::from("Baml.java")));
        assert!(out.contains_key(&PathBuf::from("inlinedbaml.b64")));
        let anchor = &out[&PathBuf::from("Baml.java")];
        assert!(anchor.starts_with("// ---"));
        assert!(anchor.contains("package baml_sdk;"));
        assert!(anchor.contains("public final class Baml {"));
    }

    #[test]
    fn class_accessor_escapes_object_final_method_names() {
        // A field may legally be called `wait`, but its accessor may not:
        // `wait()` cannot override `java.lang.Object`'s final `wait()`, so the
        // generated class would not compile. The field keeps its name and the
        // accessor takes the `$` escape.
        let mut pool = SymbolPool::new();
        let n = name("user", &["collide"], "Collide");
        pool.insert(
            n.clone(),
            class_sym_with_props(
                &n,
                &[],
                vec![("wait", t_int()), ("notify", t_string()), ("ok", t_int())],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("collide/Collide.java")];

        // Fields keep the BAML names.
        assert!(file.contains("private final long wait;"), "{file}");
        assert!(
            file.contains("private final java.lang.String notify;"),
            "{file}"
        );

        // Accessors are escaped, and read the unescaped field.
        assert!(file.contains("public long wait$() {"), "{file}");
        assert!(file.contains("return this.wait;"), "{file}");
        assert!(
            file.contains("public java.lang.String notify$() {"),
            "{file}"
        );

        // A non-colliding field is untouched.
        assert!(file.contains("public long ok() {"), "{file}");

        // The un-escaped forms must not be declared as methods.
        assert!(!file.contains("public long wait() {"), "{file}");
    }

    #[test]
    fn class_renders_fields_ctor_accessors_equality() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["primitives"], "Primitives");
        pool.insert(
            n.clone(),
            class_sym_with_props(
                &n,
                &[],
                vec![
                    ("int_field", t_int()),
                    ("string_field", t_string()),
                    ("uint8array_field", t_uint8array()),
                ],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("primitives/Primitives.java")];
        assert!(file.contains("private final long int_field;"));
        assert!(file.contains("private final java.lang.String string_field;"));
        assert!(file.contains(
            "public Primitives(long int_field, java.lang.String string_field, byte[] uint8array_field)"
        ));
        assert!(file.contains("public long int_field() {"));
        assert!(file.contains("this.int_field == other.int_field"));
        assert!(
            file.contains("java.util.Arrays.equals(this.uint8array_field, other.uint8array_field)")
        );
        assert!(file.contains("java.util.Objects.equals(this.string_field, other.string_field)"));
        assert!(file.contains("java.util.Arrays.hashCode(this.uint8array_field)"));
    }

    #[test]
    fn generic_class_declares_type_params() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["generics"], "Wrapper");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &["T"], vec![("value", t_typevar("T"))], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("generics/Wrapper.java")];
        assert!(file.contains("public final class Wrapper<T> {"));
        assert!(file.contains("private final T value;"));
        assert!(file.contains("Wrapper<?> other = (Wrapper<?>) o;"));
    }

    #[test]
    fn enum_renders_variants_with_keyword_escape() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["ipsum"], "Sentiment");
        pool.insert(n.clone(), enum_sym(&n, 0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("ipsum/Sentiment.java")];
        assert!(file.contains("public enum Sentiment {"));
        assert!(file.contains("    Positive,"));
        assert!(file.contains("    new$,"));
    }

    #[test]
    fn ctx_param_name_yields_to_user_argument_named_ctx() {
        // The shared go_codegen fixtures declare a BAML argument literally
        // named `ctx`; the synthetic cancellation parameter must escape
        // (`ctx` -> `ctx$`) instead of colliding (javac: "variable ctx is
        // already defined").
        let mut pool = SymbolPool::new();
        pool.insert(
            name("user", &["lorem"], "reserved_args"),
            Symbol::Function(Function {
                name: BaseName::new("reserved_args"),
                generic_params: Vec::new(),
                docstring: None,
                arguments: vec![FunctionArgument {
                    injected: false,
                    name: BaseName::new("ctx"),
                    docstring: None,
                    ty: t_string(),
                    default: None,
                }],
                return_type: t_string(),
                throws: None,
                watchers: Vec::new(),
                origin: origin(0),
            }),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Fns.java")];
        assert!(
            file.contains("reserved_args(java.lang.String ctx, baml_bridge.BamlCallContext ctx$)"),
            "{file}"
        );
        assert!(
            file.contains(", $RET0, ctx$);"),
            "escaped name must thread to the runtime call: {file}"
        );
        // The plain pair keeps the user's `ctx` untouched.
        assert!(
            file.contains("reserved_args(java.lang.String ctx) {"),
            "{file}"
        );
    }

    #[test]
    fn function_emits_sync_and_async_bindings() {
        let mut pool = SymbolPool::new();
        pool.insert(name("user", &["lorem"], "extract_resume"), func_sym(0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Fns.java")];
        assert!(file.contains("public final class Fns {"));
        assert!(file.contains("public static long extract_resume(long x) {"));
        // The return-type decode descriptor is a typed `baml_bridge.BamlType`,
        // pooled into a per-holder constant and passed by name as the last call arg.
        assert!(
            file.contains(
                "private static final baml_bridge.BamlType $RET0 = baml_bridge.BamlType.INT;"
            ),
            "{file}"
        );
        assert!(file.contains(
            "return (java.lang.Long) baml_bridge.BamlFfi.callSync(\"user.lorem.extract_resume\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0);"
        ));
        assert!(file.contains(
            "public static java.util.concurrent.CompletableFuture<java.lang.Long> extract_resume_async(long x) {"
        ));
        // The async sibling returns the callAsync future itself (the object
        // that owns `cancel`), reinterpreted to the element type via a
        // wildcard-bridge cast — no `thenApply` stage.
        assert!(
            file.contains(
                "return (java.util.concurrent.CompletableFuture<java.lang.Long>) (java.util.concurrent.CompletableFuture<?>) baml_bridge.BamlFfi.callAsync(\"user.lorem.extract_resume\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0);"
            ),
            "{file}"
        );
        assert!(!file.contains("thenApply"), "{file}");

        // Trailing-`ctx` overload pair (cancellation): `BamlCallContext` last,
        // threaded to the runtime as the final callSync/callAsync argument.
        assert!(
            file.contains(
                "public static long extract_resume(long x, baml_bridge.BamlCallContext ctx) {"
            ),
            "{file}"
        );
        assert!(
            file.contains(
                "return (java.lang.Long) baml_bridge.BamlFfi.callSync(\"user.lorem.extract_resume\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0, ctx);"
            ),
            "{file}"
        );
        assert!(
            file.contains("public static java.util.concurrent.CompletableFuture<java.lang.Long> extract_resume_async(long x, baml_bridge.BamlCallContext ctx) {"),
            "{file}"
        );
        assert!(
            file.contains(
                "return (java.util.concurrent.CompletableFuture<java.lang.Long>) (java.util.concurrent.CompletableFuture<?>) baml_bridge.BamlFfi.callAsync(\"user.lorem.extract_resume\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0, ctx);"
            ),
            "{file}"
        );
    }

    #[test]
    fn throwing_function_renders_throws_tags_on_both_siblings() {
        // A free function that throws `ParseError | TimeoutError` documents
        // one `@throws <UnqualifiedName>` tag per arm, in source order, on
        // both the sync binding and its `_async` sibling; the summary
        // precedes the tags.
        let mut pool = SymbolPool::new();
        let f = Function {
            name: BaseName::new("LoadDoc"),
            generic_params: Vec::new(),
            docstring: Some("Load a document from a path.".to_string()),
            arguments: vec![FunctionArgument {
                injected: false,
                name: BaseName::new("path"),
                docstring: None,
                ty: t_string(),
                default: None,
            }],
            return_type: t_string(),
            throws: Some(t_union(vec![
                t_class(name("user", &["raises_test"], "ParseError")),
                t_class(name("user", &["raises_test"], "TimeoutError")),
            ])),
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(
            name("user", &["raises_test"], "LoadDoc"),
            Symbol::Function(f),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("raises_test/Fns.java")];

        // Both arms, unqualified (FQN leaf only), one tag per line.
        assert!(file.contains(" * @throws ParseError\n"), "{file}");
        assert!(file.contains(" * @throws TimeoutError\n"), "{file}");
        // Each entry point carries the same javadoc: the required-only pair
        // (sync + async) and its trailing-`ctx` overload pair → four of each.
        assert_eq!(file.matches("@throws ParseError").count(), 4, "{file}");
        assert_eq!(file.matches("@throws TimeoutError").count(), 4, "{file}");
        // The summary precedes the `@throws` block.
        let summary = file.find("Load a document from a path.").unwrap();
        let throws = file.find("@throws").unwrap();
        assert!(summary < throws, "{file}");
    }

    #[test]
    fn non_throwing_function_has_no_throws_tags() {
        // `func_sym` has no throws contract → no `@throws` tag anywhere.
        let mut pool = SymbolPool::new();
        pool.insert(name("user", &["lorem"], "extract_resume"), func_sym(0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Fns.java")];
        assert!(!file.contains("@throws"), "{file}");
    }

    #[test]
    fn throwing_methods_render_throws_tags() {
        // Both a static and an instance method surface their single-arm
        // throws contract as an `@throws` tag on the generated class.
        let mut pool = SymbolPool::new();
        let n = name("user", &["raises_test"], "DocLoader");
        let mut load = method_fn("load", ("path", t_string()), t_string(), 2);
        load.throws = Some(t_class(name("user", &["raises_test"], "ParseError")));
        let mut create = method_fn("create", ("root", t_string()), t_string(), 1);
        create.throws = Some(t_class(name("user", &["raises_test"], "TimeoutError")));
        pool.insert(
            n.clone(),
            class_sym_with_methods(&n, vec![create], vec![load], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("raises_test/DocLoader.java")];
        assert!(file.contains("@throws ParseError"), "{file}");
        assert!(file.contains("@throws TimeoutError"), "{file}");
    }

    #[test]
    fn class_emits_static_and_instance_method_bindings() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["methods_on_classes"], "Greeter");
        pool.insert(
            n.clone(),
            class_sym_with_methods(
                &n,
                vec![method_fn("create", ("name", t_string()), t_string(), 1)],
                vec![method_fn("greet", ("greeting", t_string()), t_string(), 2)],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("methods_on_classes/Greeter.java")];

        // Static method: `static` binding, no receiver — same shape as a
        // free function, bound to `<class fqn>.<method>`.
        assert!(file.contains("public static java.lang.String create(java.lang.String name) {"));
        assert!(file.contains(
            "return (java.lang.String) baml_bridge.BamlFfi.callSync(\"user.methods_on_classes.Greeter.create\", new java.lang.String[] {\"name\"}, new java.lang.Object[] {name}, $RET0);"
        ));
        assert!(file.contains(
            "public static java.util.concurrent.CompletableFuture<java.lang.String> create_async(java.lang.String name) {"
        ));

        // Instance method: non-static, receiver prepended as `self` /
        // `this` in the runtime arrays.
        assert!(file.contains("public java.lang.String greet(java.lang.String greeting) {"));
        assert!(!file.contains("public static java.lang.String greet("));
        assert!(file.contains(
            "return (java.lang.String) baml_bridge.BamlFfi.callSync(\"user.methods_on_classes.Greeter.greet\", new java.lang.String[] {\"self\", \"greeting\"}, new java.lang.Object[] {this, greeting}, $RET0);"
        ));
        assert!(file.contains(
            "public java.util.concurrent.CompletableFuture<java.lang.String> greet_async(java.lang.String greeting) {"
        ));
        assert!(!file.contains("thenApply"), "{file}");
        assert!(file.contains(
            "return (java.util.concurrent.CompletableFuture<java.lang.String>) (java.util.concurrent.CompletableFuture<?>) baml_bridge.BamlFfi.callAsync(\"user.methods_on_classes.Greeter.greet\", new java.lang.String[] {\"self\", \"greeting\"}, new java.lang.Object[] {this, greeting}, $RET0);"
        ), "{file}");

        // Trailing-`ctx` overloads land on both the static and instance methods.
        assert!(file.contains(
            "public static java.lang.String create(java.lang.String name, baml_bridge.BamlCallContext ctx) {"
        ), "{file}");
        assert!(file.contains(
            "public java.lang.String greet(java.lang.String greeting, baml_bridge.BamlCallContext ctx) {"
        ), "{file}");
        assert!(file.contains(
            "return (java.lang.String) baml_bridge.BamlFfi.callSync(\"user.methods_on_classes.Greeter.greet\", new java.lang.String[] {\"self\", \"greeting\"}, new java.lang.Object[] {this, greeting}, $RET0, ctx);"
        ), "{file}");
    }

    #[test]
    fn optional_args_emit_configurator_overload_and_opts_class() {
        use baml_codegen_types::{DefaultLiteral, FunctionArgumentDefault};
        // (required int x, optional int opt1 default, optional string opt2 default)
        let mut pool = SymbolPool::new();
        let f = Function {
            name: BaseName::new("optional_args_probe"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("x"),
                    docstring: None,
                    ty: t_int(),
                    default: None,
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("opt1"),
                    docstring: None,
                    ty: t_int(),
                    default: Some(FunctionArgumentDefault::Literal(DefaultLiteral::Scalar(
                        baml_base::Literal::Int(5),
                    ))),
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("opt2"),
                    docstring: None,
                    ty: t_string(),
                    default: Some(FunctionArgumentDefault::Literal(DefaultLiteral::Scalar(
                        baml_base::Literal::String("hi".into()),
                    ))),
                },
            ],
            return_type: t_int(),
            throws: None,
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(
            name("user", &[], "optional_args_probe"),
            Symbol::Function(f),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("Fns.java")];

        // The required-only pair is preserved: its base arrays carry ONLY the
        // required arg, so untouched optionals are absent (engine defaults).
        assert!(file.contains("public static long optional_args_probe(long x) {"));
        assert!(file.contains(
            "return (java.lang.Long) baml_bridge.BamlFfi.callSync(\"user.optional_args_probe\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0);"
        ));

        // The configurator overload pair: a trailing Consumer<...$Opts>.
        assert!(file.contains(
            "public static long optional_args_probe(long x, java.util.function.Consumer<optional_args_probe$Opts> $cfg) {"
        ));
        assert!(file.contains(
            "public static java.util.concurrent.CompletableFuture<java.lang.Long> optional_args_probe_async(long x, java.util.function.Consumer<optional_args_probe$Opts> $cfg) {"
        ));

        // Overload body: run the configurator, then append the touched
        // optionals onto the required base arrays via the opts accessors.
        assert!(file.contains("optional_args_probe$Opts $opts = new optional_args_probe$Opts();"));
        assert!(file.contains("$cfg.accept($opts);"));
        assert!(file.contains(
            "baml_bridge.BamlFfi.callSync(\"user.optional_args_probe\", $opts.$names(new java.lang.String[] {\"x\"}), $opts.$args(new java.lang.Object[] {x}), $RET0);"
        ));

        // The configurator overload gains its own trailing-`ctx` pair, with
        // `ctx` after the Consumer (always last).
        assert!(file.contains(
            "public static long optional_args_probe(long x, java.util.function.Consumer<optional_args_probe$Opts> $cfg, baml_bridge.BamlCallContext ctx) {"
        ), "{file}");
        assert!(file.contains(
            "public static java.util.concurrent.CompletableFuture<java.lang.Long> optional_args_probe_async(long x, java.util.function.Consumer<optional_args_probe$Opts> $cfg, baml_bridge.BamlCallContext ctx) {"
        ), "{file}");
        assert!(file.contains(
            "baml_bridge.BamlFfi.callSync(\"user.optional_args_probe\", $opts.$names(new java.lang.String[] {\"x\"}), $opts.$args(new java.lang.Object[] {x}), $RET0, ctx);"
        ), "{file}");

        // Nested opts class with BOXED fluent setters (null must be passable).
        assert!(file.contains("public static final class optional_args_probe$Opts {"));
        assert!(file.contains("public optional_args_probe$Opts opt1(java.lang.Long v) {"));
        assert!(file.contains("public optional_args_probe$Opts opt2(java.lang.String v) {"));
        assert!(file.contains("this.$values.put(\"opt1\", v);"));
        assert!(file.contains("this.$touched.add(\"opt1\");"));

        // Package-visible accessors the binding reads.
        assert!(file.contains("java.lang.String[] $names(java.lang.String[] base) {"));
        assert!(file.contains("java.lang.Object[] $args(java.lang.Object[] base) {"));
    }

    #[test]
    fn optional_args_instance_method_puts_configurator_last() {
        use baml_codegen_types::{DefaultLiteral, FunctionArgumentDefault};
        let mut pool = SymbolPool::new();
        let n = name("user", &[], "OptBox");
        let probe = Function {
            name: BaseName::new("probe"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("arg0"),
                    docstring: None,
                    ty: t_int(),
                    default: None,
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("opt1"),
                    docstring: None,
                    ty: t_int(),
                    default: Some(FunctionArgumentDefault::Literal(DefaultLiteral::Scalar(
                        baml_base::Literal::Int(5),
                    ))),
                },
            ],
            return_type: t_int(),
            throws: None,
            watchers: Vec::new(),
            origin: origin(1),
        };
        pool.insert(
            n.clone(),
            class_sym_with_methods(&n, Vec::new(), vec![probe], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("OptBox.java")];

        // Required-only instance binding: receiver prepended as self/this.
        assert!(file.contains("public long probe(long arg0) {"));
        // Configurator overload keeps the receiver first, the Consumer last.
        assert!(file.contains(
            "public long probe(long arg0, java.util.function.Consumer<probe$Opts> $cfg) {"
        ));
        assert!(file.contains(
            "baml_bridge.BamlFfi.callSync(\"user.OptBox.probe\", $opts.$names(new java.lang.String[] {\"self\", \"arg0\"}), $opts.$args(new java.lang.Object[] {this, arg0}), $RET0);"
        ));
        // The nested opts class is static (instantiable from an instance method).
        assert!(file.contains("public static final class probe$Opts {"));
        assert!(file.contains("public probe$Opts opt1(java.lang.Long v) {"));
    }

    #[test]
    fn optional_args_callable_mints_functional_interface_and_types_param() {
        use baml_codegen_types::{CallableParam, CodegenFunctionParamMode};
        // A free function taking a callable whose own type carries optionals
        // (`(x: int, y?: int, z?: int) -> int`): the param types as the minted
        // interface, and the interface file is emitted beside `Fns`.
        let mut pool = SymbolPool::new();
        let callback_ty = Ty::Function {
            params: vec![
                CallableParam {
                    name: Some(BaseName::new("x")),
                    ty: t_int(),
                    mode: CodegenFunctionParamMode::Required,
                },
                CallableParam {
                    name: Some(BaseName::new("y")),
                    ty: t_int(),
                    mode: CodegenFunctionParamMode::Optional,
                },
                CallableParam {
                    name: Some(BaseName::new("z")),
                    ty: t_int(),
                    mode: CodegenFunctionParamMode::Optional,
                },
            ],
            ret: Box::new(t_int()),
            throws: Box::new(Ty::Never { attr: a() }),
            attr: a(),
        };
        let f = Function {
            name: BaseName::new("call_cb"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("callback"),
                    docstring: None,
                    ty: callback_ty,
                    default: None,
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("x"),
                    docstring: None,
                    ty: t_int(),
                    default: None,
                },
            ],
            return_type: t_list(t_int()),
            throws: None,
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(name("user", &["host_cb"], "call_cb"), Symbol::Function(f));
        let out = emit_sdk(&pool);

        // The Fns param is typed as the minted interface (not Object).
        let fns = &out[&PathBuf::from("host_cb/Fns.java")];
        assert!(
            fns.contains(
                "public static java.util.List<java.lang.Long> call_cb(baml_sdk.host_cb.IntOptCallback callback, long x) {"
            ),
            "{fns}"
        );

        // The interface file: extends the marker, single-abstract SAM, the
        // dispatch reshape, and a nested Opts bag with nullable accessors.
        let iface = &out[&PathBuf::from("host_cb/IntOptCallback.java")];
        assert!(
            iface
                .contains("public interface IntOptCallback extends baml_bridge.BamlHostCallable {"),
            "{iface}"
        );
        assert!(
            iface.contains("java.lang.Long apply(java.lang.Long x, Opts $opts);"),
            "{iface}"
        );
        assert!(
            iface.contains(
                "default java.lang.Object __bamlDispatch(java.util.List<java.lang.Object> $positional, java.util.Map<java.lang.String, java.lang.Object> $optional) {"
            ),
            "{iface}"
        );
        assert!(
            iface.contains(
                "return apply((java.lang.Long) $positional.get(0), new Opts((java.lang.Long) $optional.get(\"y\"), (java.lang.Long) $optional.get(\"z\")));"
            ),
            "{iface}"
        );
        assert!(iface.contains("final class Opts {"), "{iface}");
        // The Opts bag accessors are `@Nullable` by design (null ⇒ BAML omitted).
        assert!(
            iface.contains("public java.lang.@org.jspecify.annotations.Nullable Long y() {"),
            "{iface}"
        );
        assert!(
            iface.contains("public java.lang.@org.jspecify.annotations.Nullable Long z() {"),
            "{iface}"
        );
    }

    #[test]
    #[should_panic(
        expected = "Java generation does not yet support optional parameters on returned callable"
    )]
    fn optional_returned_callable_fails_generation_instead_of_emitting_an_unsafe_cast() {
        use baml_codegen_types::{CallableParam, CodegenFunctionParamMode};

        let returned = Ty::Function {
            params: vec![CallableParam {
                name: Some(BaseName::new("value")),
                ty: t_int(),
                mode: CodegenFunctionParamMode::Optional,
            }],
            ret: Box::new(t_int()),
            throws: Box::new(Ty::Never { attr: a() }),
            attr: a(),
        };
        let mut pool = SymbolPool::new();
        pool.insert(
            name("user", &[], "make_optional"),
            Symbol::Function(Function {
                name: BaseName::new("make_optional"),
                generic_params: Vec::new(),
                docstring: None,
                arguments: Vec::new(),
                return_type: returned,
                throws: None,
                watchers: Vec::new(),
                origin: origin(0),
            }),
        );
        let _ = emit_sdk(&pool);
    }

    #[test]
    fn unnamed_returned_callable_uses_its_canonical_positional_wire_name() {
        use baml_codegen_types::{CallableParam, CodegenFunctionParamMode};

        let returned = Ty::Function {
            params: vec![CallableParam {
                name: None,
                ty: t_int(),
                mode: CodegenFunctionParamMode::Required,
            }],
            ret: Box::new(t_int()),
            throws: Box::new(Ty::Never { attr: a() }),
            attr: a(),
        };
        let mut pool = SymbolPool::new();
        pool.insert(
            name("user", &[], "make_unnamed"),
            Symbol::Function(Function {
                name: BaseName::new("make_unnamed"),
                generic_params: Vec::new(),
                docstring: None,
                arguments: Vec::new(),
                return_type: returned,
                throws: None,
                watchers: Vec::new(),
                origin: origin(0),
            }),
        );
        let out = emit_sdk(&pool);
        let fns = &out[&PathBuf::from("Fns.java")];
        assert!(fns.contains("new java.lang.String[] {\"arg0\"}"), "{fns}");
        assert!(
            fns.contains("baml_bridge.BamlFfi.returnedClosure("),
            "{fns}"
        );
    }

    #[test]
    fn fns_holder_escapes_on_user_class_collision() {
        let mut pool = SymbolPool::new();
        let cls = name("user", &["lorem"], "Fns");
        pool.insert(cls.clone(), class_sym(&cls, &[], 0));
        pool.insert(name("user", &["lorem"], "extract_resume"), func_sym(1));
        let out = emit_sdk(&pool);
        assert!(out.contains_key(&PathBuf::from("lorem/Fns.java"))); // the user class
        let holder = &out[&PathBuf::from("lorem/Fns$.java")];
        assert!(holder.contains("public final class Fns$ {"));
    }

    #[test]
    fn union_field_renders_generic_arity_family() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["unions"], "UnionContainer");
        pool.insert(
            n.clone(),
            class_sym_with_props(
                &n,
                &[],
                vec![("value", t_union(vec![t_int(), t_string()]))],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let container = &out[&PathBuf::from("unions/UnionContainer.java")];
        // Anonymous unions render inline as the runtime's arity family;
        // no nominal sealed type (and no `unions$` file) is minted.
        assert!(
            container.contains(
                "private final baml_bridge.Union2<java.lang.Long, java.lang.String> value;"
            )
        );
        assert!(!out.contains_key(&PathBuf::from("unions$/UnionIntOrString.java")));
        // registerClass carries a parallel per-field decode-descriptor
        // array (typed `baml_bridge.BamlType[]`) as its fourth argument.
        let anchor = &out[&PathBuf::from("Baml.java")];
        assert!(anchor.contains(
            "baml_bridge.TypeRegistry.registerClass(\"user.unions.UnionContainer\", \"baml_sdk.unions.UnionContainer\", new java.lang.String[] {\"value\"}, new baml_bridge.BamlType[] {baml_bridge.BamlType.union(baml_bridge.BamlType.INT, baml_bridge.BamlType.STRING)});"
        ), "{anchor}");
    }

    #[test]
    fn recursive_alias_mints_nominal_union_and_registers() {
        // A recursive alias keeps its minted nominal sealed type (a
        // positional generic can't reference itself) and still emits BOTH
        // union registrations: the structural signature AND the alias's
        // own FQN.
        let mut pool = SymbolPool::new();
        let n = name("user", &["aliases"], "RecList");
        pool.insert(n.clone(), recursive_alias_sym(&n, 0));
        let out = emit_sdk(&pool);

        let file = &out[&PathBuf::from("aliases/RecList.java")];
        assert!(file.contains(
            "public sealed interface RecList permits RecList.IntValue, RecList.RecListListValue {"
        ));
        assert!(file.contains("record IntValue(java.lang.Long value) implements RecList {}"));

        let anchor = &out[&PathBuf::from("Baml.java")];
        // Structural registration: keyed runtime-side by the arm SET, so the
        // emitter passes the sealed name + the typed arm tokens (no signature
        // string). Arms: `int` and `list<RecList>` (the alias's self-reference).
        assert!(anchor.contains(
            "baml_bridge.TypeRegistry.registerUnion(\"baml_sdk.aliases.RecList\", new baml_bridge.BamlType[] {baml_bridge.BamlType.INT, baml_bridge.BamlType.list(baml_bridge.BamlType.classByFqn(\"user.aliases.RecList\"))},"
        ), "{anchor}");
        // Alias-FQN registration (the engine may send self_type either way).
        assert!(anchor.contains(
            "baml_bridge.TypeRegistry.registerUnionAlias(\"user.aliases.RecList\", \"baml_sdk.aliases.RecList\", new baml_bridge.BamlType[] {baml_bridge.BamlType.INT, baml_bridge.BamlType.list(baml_bridge.BamlType.classByFqn(\"user.aliases.RecList\"))},"
        ), "{anchor}");
    }

    #[test]
    fn vendor_symbol_routes_under_vendor_dirs() {
        let mut pool = SymbolPool::new();
        let n = name("aws", &["s3"], "Bucket");
        pool.insert(n.clone(), class_sym(&n, &[], 0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("vendor/aws/s3/Bucket.java")];
        assert!(file.contains("package baml_sdk.vendor.aws.s3;"));
    }

    #[test]
    fn root_namespace_symbol_in_root_package() {
        let mut pool = SymbolPool::new();
        let n = name("user", &[], "Foo");
        pool.insert(n.clone(), class_sym(&n, &[], 0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("Foo.java")];
        assert!(file.contains("package baml_sdk;"));
        assert!(file.contains("public final class Foo {"));
    }

    #[test]
    fn stream_class_emits_beside_base_with_suffix() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["lorem"], "Resume$stream");
        pool.insert(n.clone(), class_sym(&n, &[], 0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Resume$stream.java")];
        assert!(file.contains("public final class Resume$stream {"));
    }

    #[test]
    fn keyword_namespace_routes_to_escaped_package_dir() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["void"], "VoidProbe");
        pool.insert(n.clone(), class_sym(&n, &[], 0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("void$/VoidProbe.java")];
        assert!(file.contains("package baml_sdk.void$;"));
    }

    #[test]
    fn runtime_owned_stdlib_types_are_not_emitted() {
        let mut pool = SymbolPool::new();
        let img = name("baml", &["media"], "Image");
        pool.insert(img.clone(), class_sym(&img, &[], 0));
        let stream = name("ai", &["stream"], "Stream");
        pool.insert(stream.clone(), class_sym(&stream, &[], 1));
        let done = name("ai", &["stream"], "Done");
        pool.insert(done.clone(), class_sym(&done, &[], 2));
        let resp = name("baml", &["http"], "Response");
        pool.insert(resp.clone(), class_sym(&resp, &[], 3));
        let out = emit_sdk(&pool);
        assert!(!out.contains_key(&PathBuf::from("baml/media/Image.java")));
        assert!(!out.contains_key(&PathBuf::from("vendor/ai/stream/Stream.java")));
        assert!(!out.contains_key(&PathBuf::from("vendor/ai/stream/Done.java")));
        assert!(out.contains_key(&PathBuf::from("baml/http/Response.java")));
    }

    #[test]
    fn inlinedbaml_is_base64() {
        let out = to_source_code(
            &SymbolPool::new(),
            &[0, 1, 2, 253, 254, 255],
            NamingConvention::PreserveCase,
        );
        assert_eq!(out[&PathBuf::from("inlinedbaml.b64")], "AAEC/f7/");
    }

    #[test]
    fn base64_padding() {
        assert_eq!(base64_encode(b""), "");
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
    }

    // -- explicit generics: emitter surface ----------------------------------

    /// A generic free function (`identity<T>(x: T) -> T`).
    fn generic_identity_sym(span: u32) -> Symbol {
        Symbol::Function(Function {
            name: BaseName::new("identity"),
            generic_params: vec![BaseName::new("T")],
            docstring: None,
            arguments: vec![FunctionArgument {
                injected: false,
                name: BaseName::new("x"),
                docstring: None,
                ty: t_typevar("T"),
                default: None,
            }],
            return_type: t_typevar("T"),
            throws: None,
            watchers: Vec::new(),
            origin: origin(span),
        })
    }

    #[test]
    fn generic_function_emits_types_overloads() {
        let mut pool = SymbolPool::new();
        pool.insert(
            name("user", &["generic_tests"], "identity"),
            generic_identity_sym(0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("generic_tests/Fns.java")];

        // The required-only pair and its trailing-`ctx` pair are preserved.
        assert!(
            file.contains("public static <T> T identity(T x) {"),
            "{file}"
        );
        assert!(
            file.contains("public static <T> T identity(T x, baml_bridge.BamlCallContext ctx) {"),
            "{file}"
        );

        // The `types` overload (no ctx) threads the bag through the 6-arg
        // runtime call with a `null` ctx; the return descriptor is the TypeVar
        // token `tv:T`.
        assert!(
            file.contains("public static <T> T identity(T x, baml_bridge.BamlTypes types) {"),
            "{file}"
        );
        assert!(
            file.contains(
                "return (T) baml_bridge.BamlFfi.callSync(\"user.generic_tests.identity\", new java.lang.String[] {\"x\"}, new java.lang.Object[] {x}, $RET0, null, types);"
            ),
            "{file}"
        );

        // The `types` + `ctx` overload passes both, in `(ctx, types)` order.
        assert!(
            file.contains(
                "public static <T> T identity(T x, baml_bridge.BamlTypes types, baml_bridge.BamlCallContext ctx) {"
            ),
            "{file}"
        );
        assert!(
            file.contains("new java.lang.Object[] {x}, $RET0, ctx, types);"),
            "{file}"
        );

        // The async siblings gain the same two overloads.
        assert!(
            file.contains(
                "public static <T> java.util.concurrent.CompletableFuture<T> identity_async(T x, baml_bridge.BamlTypes types) {"
            ),
            "{file}"
        );

        // Exactly four sync + four async entry points (8 declarations): the
        // required-only base's {types?}×{ctx?} family.
        assert_eq!(file.matches("public static <T>").count(), 8, "{file}");
        // A free function has no receiver, so no explicit-bag receiver guard.
        assert!(!file.contains("reified receiver"), "{file}");
    }

    #[test]
    fn non_generic_function_emits_no_types_overload() {
        // `func_sym` is non-generic: only the required-only + ctx pairs, no bag.
        let mut pool = SymbolPool::new();
        pool.insert(name("user", &["lorem"], "extract_resume"), func_sym(0));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Fns.java")];
        assert!(!file.contains("baml_bridge.BamlTypes"), "{file}");
    }

    #[test]
    fn generic_optional_function_emits_full_overload_matrix() {
        use baml_codegen_types::{DefaultLiteral, FunctionArgumentDefault};
        // A generic (`<T>`) function with one optional arg → the worst-case
        // matrix: {opts?}×{types?}×{ctx?} = 8 pairs = 16 entry-point methods.
        let mut pool = SymbolPool::new();
        let f = Function {
            name: BaseName::new("probe"),
            generic_params: vec![BaseName::new("T")],
            docstring: None,
            arguments: vec![
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("x"),
                    docstring: None,
                    ty: t_typevar("T"),
                    default: None,
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("opt1"),
                    docstring: None,
                    ty: t_int(),
                    default: Some(FunctionArgumentDefault::Literal(DefaultLiteral::Scalar(
                        baml_base::Literal::Int(5),
                    ))),
                },
            ],
            return_type: t_typevar("T"),
            throws: None,
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(name("user", &[], "probe"), Symbol::Function(f));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("Fns.java")];

        // 16 generic entry-point declarations (the opts class is `public static
        // final class`, not `public static <T>`, so it doesn't count).
        assert_eq!(file.matches("public static <T>").count(), 16, "{file}");
        // The fullest overload stacks every trailing param in order:
        // `f(required…, opts, types, ctx)`.
        assert!(
            file.contains(
                "public static <T> T probe(T x, java.util.function.Consumer<probe$Opts> $cfg, baml_bridge.BamlTypes types, baml_bridge.BamlCallContext ctx) {"
            ),
            "{file}"
        );
        // The configurator + types overload routes the opts accessors AND the
        // bag through the runtime call.
        assert!(
            file.contains(
                "baml_bridge.BamlFfi.callSync(\"user.probe\", $opts.$names(new java.lang.String[] {\"x\"}), $opts.$args(new java.lang.Object[] {x}), $RET0, ctx, types);"
            ),
            "{file}"
        );
    }

    #[test]
    fn generic_class_emits_reified_factory_and_readback() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["generic_tests"], "GenericBox");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &["T"], vec![("value", t_typevar("T"))], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("generic_tests/GenericBox.java")];

        // Reified factory: one BamlType token per class type param, then fields.
        assert!(
            file.contains(
                "public static <T> GenericBox<T> of(baml_bridge.BamlType $t0, T value) {"
            ),
            "{file}"
        );
        assert!(
            file.contains("GenericBox<T> $instance = new GenericBox<>(value);"),
            "{file}"
        );
        assert!(
            file.contains(
                "baml_bridge.TypeRegistry.bindTypeArgs($instance, java.util.List.of($t0));"
            ),
            "{file}"
        );
        assert!(file.contains("        return $instance;"), "{file}");

        // Readback delegates to the side-table.
        assert!(
            file.contains("public java.util.List<baml_bridge.BamlType> bamlTypeArgs() {"),
            "{file}"
        );
        assert!(
            file.contains("return baml_bridge.TypeRegistry.typeArgsOf(this);"),
            "{file}"
        );
    }

    #[test]
    fn reified_factory_takes_one_token_per_type_param() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["g"], "Pair");
        pool.insert(
            n.clone(),
            class_sym_with_props(
                &n,
                &["A", "B"],
                vec![("first", t_typevar("A")), ("second", t_typevar("B"))],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("g/Pair.java")];
        assert!(
            file.contains(
                "public static <A, B> Pair<A, B> of(baml_bridge.BamlType $t0, baml_bridge.BamlType $t1, A first, B second) {"
            ),
            "{file}"
        );
        assert!(file.contains("new Pair<>(first, second)"), "{file}");
        assert!(file.contains("java.util.List.of($t0, $t1)"), "{file}");
    }

    #[test]
    fn non_generic_class_has_no_reified_surface() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["p"], "Plain");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &[], vec![("x", t_int())], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("p/Plain.java")];
        assert!(!file.contains("bamlTypeArgs"), "{file}");
        assert!(!file.contains("bindTypeArgs"), "{file}");
        assert!(!file.contains(" of("), "{file}");
    }

    #[test]
    fn baml_type_args_readback_escapes_on_field_collision() {
        // A BAML field literally named `bamlTypeArgs` claims that accessor name,
        // so the readback method escapes to `bamlTypeArgs$()` (the Fns→Fns$ rule).
        let mut pool = SymbolPool::new();
        let n = name("user", &["g"], "Weird");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &["T"], vec![("bamlTypeArgs", t_typevar("T"))], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("g/Weird.java")];
        // The field's own accessor keeps the un-escaped name.
        assert!(file.contains("public T bamlTypeArgs() {"), "{file}");
        // The readback escapes.
        assert!(
            file.contains("public java.util.List<baml_bridge.BamlType> bamlTypeArgs$() {"),
            "{file}"
        );
    }

    #[test]
    fn generic_instance_method_explicit_overload_guards_receiver() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["g"], "GenericBox");
        let mut pair_with = method_fn("pair_with", ("other", t_typevar("U")), t_string(), 1);
        pair_with.generic_params = vec![BaseName::new("U")];
        pool.insert(
            n.clone(),
            Symbol::Class(Class {
                name: n,
                generic_params: vec![BaseName::new("T")],
                docstring: None,
                properties: vec![ClassProperty {
                    name: BaseName::new("value"),
                    docstring: None,
                    ty: t_typevar("T"),
                }],
                static_methods: Vec::new(),
                instance_methods: vec![pair_with],
                origin: origin(0),
            }),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("g/GenericBox.java")];

        // The bare + ctx overloads take no bag and carry no guard.
        assert!(
            file.contains("public <U> java.lang.String pair_with(U other) {"),
            "{file}"
        );
        // The explicit-bag overload exists and guards the receiver.
        assert!(
            file.contains(
                "public <U> java.lang.String pair_with(U other, baml_bridge.BamlTypes types) {"
            ),
            "{file}"
        );
        assert!(
            file.contains("if (baml_bridge.TypeRegistry.typeArgsOf(this).isEmpty()) {"),
            "{file}"
        );
        assert!(file.contains("reified receiver"), "{file}");
        // The guard rides only the two explicit-bag overloads (types-only and
        // types+ctx), each sync + async → exactly four occurrences.
        assert_eq!(
            file.matches("if (baml_bridge.TypeRegistry.typeArgsOf(this).isEmpty()) {")
                .count(),
            4,
            "{file}"
        );
    }

    #[test]
    fn generic_static_method_types_overload_has_no_receiver_guard() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["g"], "GenericBox");
        let mut new_m = method_fn("new", ("value", t_typevar("V")), t_string(), 1);
        new_m.generic_params = vec![BaseName::new("V")];
        pool.insert(
            n.clone(),
            Symbol::Class(Class {
                name: n,
                generic_params: vec![BaseName::new("T")],
                docstring: None,
                properties: Vec::new(),
                static_methods: vec![new_m],
                instance_methods: Vec::new(),
                origin: origin(0),
            }),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("g/GenericBox.java")];

        // A static re-declares the class param plus its own; the `new` keyword
        // escapes to `new$`; the explicit-bag overload exists with NO guard.
        assert!(
            file.contains("public static <T, V> ")
                && file.contains("new$(V value, baml_bridge.BamlTypes types)"),
            "{file}"
        );
        assert!(!file.contains("reified receiver"), "{file}");
    }

    // -- double field equality (NaN / ±0.0) ----------------------------------

    #[test]
    fn double_field_uses_double_compare_and_hashcode() {
        // A `double` field must NOT use `==` (NaN != NaN; +0.0 == -0.0 with
        // differing hashCodes breaks the equals/hashCode contract). Use
        // Double.compare in equals and Double.hashCode in hashCode.
        let mut pool = SymbolPool::new();
        let n = name("user", &["primitives"], "Floaty");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &[], vec![("ratio", t_float())], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("primitives/Floaty.java")];
        assert!(file.contains("private final double ratio;"), "{file}");
        assert!(
            file.contains("java.lang.Double.compare(this.ratio, other.ratio) == 0"),
            "{file}"
        );
        assert!(!file.contains("this.ratio == other.ratio"), "{file}");
        assert!(
            file.contains("java.lang.Double.hashCode(this.ratio)"),
            "{file}"
        );
    }

    // -- runtime-init static block on binding-bearing classes ----------------

    #[test]
    fn class_with_bindings_emits_runtime_init_static_block() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["methods_on_classes"], "Greeter");
        pool.insert(
            n.clone(),
            class_sym_with_methods(
                &n,
                vec![method_fn("create", ("name", t_string()), t_string(), 1)],
                Vec::new(),
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("methods_on_classes/Greeter.java")];
        // The FIRST-touched entrypoint (`Greeter.create()`) must boot the runtime.
        assert!(
            file.contains("    static {\n        baml_sdk.Baml.ensure();\n    }"),
            "{file}"
        );
    }

    #[test]
    fn pure_value_class_has_no_runtime_init_static_block() {
        let mut pool = SymbolPool::new();
        let n = name("user", &["p"], "Plain");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &[], vec![("x", t_int())], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("p/Plain.java")];
        // A pure value class is only reached via decode (runtime already up).
        assert!(!file.contains("ensure()"), "{file}");
    }

    // -- `_async` sibling collision escape -----------------------------------

    #[test]
    fn async_sibling_escapes_on_user_async_named_collision() {
        // A user function `foo_async` collides with the generated `_async`
        // sibling of `foo`; foo's SYNTHETIC sibling escapes to `foo_async$`.
        let mut pool = SymbolPool::new();
        pool.insert(
            name("user", &["lorem"], "foo"),
            Symbol::Function(nullary_fn("foo", 0)),
        );
        pool.insert(
            name("user", &["lorem"], "foo_async"),
            Symbol::Function(nullary_fn("foo_async", 1)),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("lorem/Fns.java")];
        // foo's sync + escaped async.
        assert!(file.contains("public static long foo() {"), "{file}");
        assert!(file.contains("foo_async$("), "{file}");
        // The user's own foo_async sync + its (unescaped) async sibling.
        assert!(file.contains("public static long foo_async() {"), "{file}");
        assert!(file.contains("foo_async_async("), "{file}");
    }

    // -- root `Baml` anchor collision escape ---------------------------------

    #[test]
    fn user_root_type_named_baml_escapes_anchor() {
        // A user root-level type named `Baml` must NOT be clobbered by the
        // generated anchor; the ANCHOR escapes to `Baml$` and every
        // `<root>.Baml.ensure()` reference threads the escaped name.
        let mut pool = SymbolPool::new();
        let baml = name("user", &[], "Baml");
        pool.insert(
            baml.clone(),
            class_sym_with_props(&baml, &[], vec![("x", t_int())], 0),
        );
        pool.insert(name("user", &["lorem"], "extract_resume"), func_sym(1));
        let out = emit_sdk(&pool);

        // The user's Baml type keeps Baml.java (not overwritten).
        let user = &out[&PathBuf::from("Baml.java")];
        assert!(user.contains("public final class Baml {"), "{user}");
        assert!(!user.contains("public static void ensure()"), "{user}");

        // The anchor lives at Baml$.java.
        let anchor = &out[&PathBuf::from("Baml$.java")];
        assert!(anchor.contains("public final class Baml$ {"), "{anchor}");
        assert!(
            anchor.contains("public static void ensure() {}"),
            "{anchor}"
        );

        // The Fns holder references the escaped anchor.
        let fns = &out[&PathBuf::from("lorem/Fns.java")];
        assert!(fns.contains("baml_sdk.Baml$.ensure();"), "{fns}");
    }

    // ---- JSpecify nullness annotations ---------------------------------------

    #[test]
    fn nullable_field_accessor_return_is_annotated() {
        // A `string?` field: the private field, constructor param, and accessor
        // return all carry `@Nullable`; a non-null `int` field is untouched.
        let mut pool = SymbolPool::new();
        let n = name("user", &["nn"], "Doc");
        pool.insert(
            n.clone(),
            class_sym_with_props(
                &n,
                &[],
                vec![("title", t_opt(t_string())), ("count", t_int())],
                0,
            ),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("nn/Doc.java")];
        assert!(
            file.contains(
                "private final java.lang.@org.jspecify.annotations.Nullable String title;"
            ),
            "{file}"
        );
        assert!(
            file.contains("public java.lang.@org.jspecify.annotations.Nullable String title() {"),
            "{file}"
        );
        // The constructor param is annotated too.
        assert!(
            file.contains("java.lang.@org.jspecify.annotations.Nullable String title"),
            "{file}"
        );
        // The non-null primitive field stays a bare unboxed `long`.
        assert!(file.contains("public long count() {"), "{file}");
        assert!(!file.contains("Nullable Long count"), "{file}");
    }

    #[test]
    fn nullable_list_element_field_is_annotated() {
        // A `(string?)[]` field: the element is `@Nullable`, the list is not.
        let mut pool = SymbolPool::new();
        let n = name("user", &["nn"], "Tags");
        pool.insert(
            n.clone(),
            class_sym_with_props(&n, &[], vec![("items", t_list(t_opt(t_string())))], 0),
        );
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("nn/Tags.java")];
        assert!(
            file.contains(
                "public java.util.List<java.lang.@org.jspecify.annotations.Nullable String> items() {"
            ),
            "{file}"
        );
    }

    #[test]
    fn nullable_param_and_return_are_annotated() {
        // `fn find(needle: string?) -> string?`: the required param and both the
        // sync return and the async future's element type carry `@Nullable`.
        let mut pool = SymbolPool::new();
        let f = Function {
            name: BaseName::new("find"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![FunctionArgument {
                injected: false,
                name: BaseName::new("needle"),
                docstring: None,
                ty: t_opt(t_string()),
                default: None,
            }],
            return_type: t_opt(t_string()),
            throws: None,
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(name("user", &["nn"], "find"), Symbol::Function(f));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("nn/Fns.java")];
        assert!(
            file.contains(
                "public static java.lang.@org.jspecify.annotations.Nullable String find(java.lang.@org.jspecify.annotations.Nullable String needle) {"
            ),
            "{file}"
        );
        assert!(
            file.contains(
                "public static java.util.concurrent.CompletableFuture<java.lang.@org.jspecify.annotations.Nullable String> find_async(java.lang.@org.jspecify.annotations.Nullable String needle) {"
            ),
            "{file}"
        );
    }

    #[test]
    fn nullable_optional_setter_param_is_annotated() {
        use baml_codegen_types::{DefaultLiteral, FunctionArgumentDefault};
        // A nullable optional arg (`hint?: string?`) → its `$Opts` setter param
        // is `@Nullable`; a non-null optional's setter is not.
        let mut pool = SymbolPool::new();
        let f = Function {
            name: BaseName::new("probe"),
            generic_params: Vec::new(),
            docstring: None,
            arguments: vec![
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("x"),
                    docstring: None,
                    ty: t_int(),
                    default: None,
                },
                FunctionArgument {
                    injected: false,
                    name: BaseName::new("hint"),
                    docstring: None,
                    ty: t_opt(t_string()),
                    default: Some(FunctionArgumentDefault::Literal(DefaultLiteral::Scalar(
                        baml_base::Literal::String("hi".into()),
                    ))),
                },
            ],
            return_type: t_int(),
            throws: None,
            watchers: Vec::new(),
            origin: origin(0),
        };
        pool.insert(name("user", &["nn"], "probe"), Symbol::Function(f));
        let out = emit_sdk(&pool);
        let file = &out[&PathBuf::from("nn/Fns.java")];
        assert!(
            file.contains(
                "public probe$Opts hint(java.lang.@org.jspecify.annotations.Nullable String v) {"
            ),
            "{file}"
        );
    }
}
