// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: baml_bridge/cffi/v1/baml_inbound.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// See crates/bridge_ctypes/README.md for the list of consumers and the
/// commands used to regenerate each language's proto client.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Core value type. `value_type` is a sparse exact-type annotation for this
/// node, never a copy of the enclosing union. Most values omit it and are
/// decoded from the declared contextual type plus payload shape. Hosts set it
/// only when shape/context cannot preserve their choice (for example an empty
/// container, an overlapping union arm, or a literal-vs-primitive selection).
nonisolated struct BamlBridge_Cffi_V1_InboundValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var valueType: BamlBridge_Cffi_V1_BamlTy {
    get {_valueType ?? BamlBridge_Cffi_V1_BamlTy()}
    set {_valueType = newValue}
  }
  /// Returns true if `valueType` has been explicitly set.
  var hasValueType: Bool {self._valueType != nil}
  /// Clears the value of `valueType`. Subsequent reads from it will return its default value.
  mutating func clearValueType() {self._valueType = nil}

  var value: BamlBridge_Cffi_V1_InboundValue.OneOf_Value? = nil

  var stringValue: String {
    get {
      if case .stringValue(let v)? = value {return v}
      return String()
    }
    set {value = .stringValue(newValue)}
  }

  var intValue: Int64 {
    get {
      if case .intValue(let v)? = value {return v}
      return 0
    }
    set {value = .intValue(newValue)}
  }

  var floatValue: Double {
    get {
      if case .floatValue(let v)? = value {return v}
      return 0
    }
    set {value = .floatValue(newValue)}
  }

  var boolValue: Bool {
    get {
      if case .boolValue(let v)? = value {return v}
      return false
    }
    set {value = .boolValue(newValue)}
  }

  var listValue: BamlBridge_Cffi_V1_InboundListValue {
    get {
      if case .listValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_InboundListValue()
    }
    set {value = .listValue(newValue)}
  }

  var mapValue: BamlBridge_Cffi_V1_InboundMapValue {
    get {
      if case .mapValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_InboundMapValue()
    }
    set {value = .mapValue(newValue)}
  }

  var classValue: BamlBridge_Cffi_V1_InboundClassValue {
    get {
      if case .classValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_InboundClassValue()
    }
    set {value = .classValue(newValue)}
  }

  var enumValue: BamlBridge_Cffi_V1_InboundEnumValue {
    get {
      if case .enumValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_InboundEnumValue()
    }
    set {value = .enumValue(newValue)}
  }

  var handle: BamlBridge_Cffi_V1_BamlHandle {
    get {
      if case .handle(let v)? = value {return v}
      return BamlBridge_Cffi_V1_BamlHandle()
    }
    set {value = .handle(newValue)}
  }

  var uint8ArrayValue: Data {
    get {
      if case .uint8ArrayValue(let v)? = value {return v}
      return Data()
    }
    set {value = .uint8ArrayValue(newValue)}
  }

  var bigintValue: String {
    get {
      if case .bigintValue(let v)? = value {return v}
      return String()
    }
    set {value = .bigintValue(newValue)}
  }

  /// A reflected BAML type passed as a value (mirrors a `reflect.Type` BAML
  /// value, e.g. the result of `reflect.Type.of<T>()`). Accepted as an
  /// argument value so the host can pass types as data.
  var tyValue: BamlBridge_Cffi_V1_BamlTy {
    get {
      if case .tyValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_BamlTy()
    }
    set {value = .tyValue(newValue)}
  }

  /// Definition-carrying reflected type. New hosts use this for values that
  /// must retain runtime-created class/enum schemas; tag 13 remains for
  /// rollout compatibility with structural/static type senders.
  var tyDefValue: BamlBridge_Cffi_V1_BamlTyDef {
    get {
      if case .tyDefValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_BamlTyDef()
    }
    set {value = .tyDefValue(newValue)}
  }

  /// Rust-backed values cross as portable data, never as capability handles.
  /// These message shapes are shared with the outbound side so host-created
  /// and engine-created values have one canonical representation.
  var mediaValue: BamlBridge_Cffi_V1_BamlValueMedia {
    get {
      if case .mediaValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_BamlValueMedia()
    }
    set {value = .mediaValue(newValue)}
  }

  var promptAstValue: BamlBridge_Cffi_V1_BamlValuePromptAst {
    get {
      if case .promptAstValue(let v)? = value {return v}
      return BamlBridge_Cffi_V1_BamlValuePromptAst()
    }
    set {value = .promptAstValue(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Value: Equatable, Sendable {
    case stringValue(String)
    case intValue(Int64)
    case floatValue(Double)
    case boolValue(Bool)
    case listValue(BamlBridge_Cffi_V1_InboundListValue)
    case mapValue(BamlBridge_Cffi_V1_InboundMapValue)
    case classValue(BamlBridge_Cffi_V1_InboundClassValue)
    case enumValue(BamlBridge_Cffi_V1_InboundEnumValue)
    case handle(BamlBridge_Cffi_V1_BamlHandle)
    case uint8ArrayValue(Data)
    case bigintValue(String)
    /// A reflected BAML type passed as a value (mirrors a `reflect.Type` BAML
    /// value, e.g. the result of `reflect.Type.of<T>()`). Accepted as an
    /// argument value so the host can pass types as data.
    case tyValue(BamlBridge_Cffi_V1_BamlTy)
    /// Definition-carrying reflected type. New hosts use this for values that
    /// must retain runtime-created class/enum schemas; tag 13 remains for
    /// rollout compatibility with structural/static type senders.
    case tyDefValue(BamlBridge_Cffi_V1_BamlTyDef)
    /// Rust-backed values cross as portable data, never as capability handles.
    /// These message shapes are shared with the outbound side so host-created
    /// and engine-created values have one canonical representation.
    case mediaValue(BamlBridge_Cffi_V1_BamlValueMedia)
    case promptAstValue(BamlBridge_Cffi_V1_BamlValuePromptAst)

  }

  init() {}

  fileprivate var _valueType: BamlBridge_Cffi_V1_BamlTy? = nil
}

nonisolated struct BamlBridge_Cffi_V1_InboundListValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var values: [BamlBridge_Cffi_V1_InboundValue] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct BamlBridge_Cffi_V1_InboundMapValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entries: [BamlBridge_Cffi_V1_InboundMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct BamlBridge_Cffi_V1_InboundMapEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: BamlBridge_Cffi_V1_InboundMapEntry.OneOf_Key? = nil

  var stringKey: String {
    get {
      if case .stringKey(let v)? = key {return v}
      return String()
    }
    set {key = .stringKey(newValue)}
  }

  var intKey: Int64 {
    get {
      if case .intKey(let v)? = key {return v}
      return 0
    }
    set {key = .intKey(newValue)}
  }

  var boolKey: Bool {
    get {
      if case .boolKey(let v)? = key {return v}
      return false
    }
    set {key = .boolKey(newValue)}
  }

  var enumKey: BamlBridge_Cffi_V1_InboundEnumValue {
    get {
      if case .enumKey(let v)? = key {return v}
      return BamlBridge_Cffi_V1_InboundEnumValue()
    }
    set {key = .enumKey(newValue)}
  }

  var value: BamlBridge_Cffi_V1_InboundValue {
    get {_value ?? BamlBridge_Cffi_V1_InboundValue()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() {self._value = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Key: Equatable, Sendable {
    case stringKey(String)
    case intKey(Int64)
    case boolKey(Bool)
    case enumKey(BamlBridge_Cffi_V1_InboundEnumValue)

  }

  init() {}

  fileprivate var _value: BamlBridge_Cffi_V1_InboundValue? = nil
}

nonisolated struct BamlBridge_Cffi_V1_InboundClassValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fields: [BamlBridge_Cffi_V1_InboundMapEntry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct BamlBridge_Cffi_V1_InboundEnumValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// One explicit `TypeVar` binding for a generic function/method call: the
/// TypeVar name paired with the concrete type it is bound to.
nonisolated struct BamlBridge_Cffi_V1_BamlTyArg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// TypeVar name, e.g. "T", "A"
  var typeVar: String = String()

  /// the concrete binding
  var typeValue: BamlBridge_Cffi_V1_BamlTy {
    get {_typeValue ?? BamlBridge_Cffi_V1_BamlTy()}
    set {_typeValue = newValue}
  }
  /// Returns true if `typeValue` has been explicitly set.
  var hasTypeValue: Bool {self._typeValue != nil}
  /// Clears the value of `typeValue`. Subsequent reads from it will return its default value.
  mutating func clearTypeValue() {self._typeValue = nil}

  /// Explicit portable definition: importing it creates fresh runtime types.
  var typeDefinition: BamlBridge_Cffi_V1_BamlTyDef {
    get {_typeDefinition ?? BamlBridge_Cffi_V1_BamlTyDef()}
    set {_typeDefinition = newValue}
  }
  /// Returns true if `typeDefinition` has been explicitly set.
  var hasTypeDefinition: Bool {self._typeDefinition != nil}
  /// Clears the value of `typeDefinition`. Subsequent reads from it will return its default value.
  mutating func clearTypeDefinition() {self._typeDefinition = nil}

  /// Borrowed session reference to an engine-owned reflected type. Exactly one
  /// of type_value, type_definition or type_reference must be present.
  var typeReference: UInt64 {
    get {_typeReference ?? 0}
    set {_typeReference = newValue}
  }
  /// Returns true if `typeReference` has been explicitly set.
  var hasTypeReference: Bool {self._typeReference != nil}
  /// Clears the value of `typeReference`. Subsequent reads from it will return its default value.
  mutating func clearTypeReference() {self._typeReference = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _typeValue: BamlBridge_Cffi_V1_BamlTy? = nil
  fileprivate var _typeDefinition: BamlBridge_Cffi_V1_BamlTyDef? = nil
  fileprivate var _typeReference: UInt64? = nil
}

/// Type arguments for a method are ordered by its checked declaration. Live
/// references preserve identity; definitions explicitly create fresh types.
/// Each BamlTyArg.type_var must be empty on this positional path.
nonisolated struct BamlBridge_Cffi_V1_InterfaceMethodTarget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var view: UInt64 = 0

  var member: String = String()

  var typeArgs: [BamlBridge_Cffi_V1_BamlTyArg] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compiler-selected method on a concrete class.
/// The receiver is borrowed and pinned during preparation. Class variables in
/// interface_pattern index the receiver's stored class arguments, never the
/// host's method arguments. The engine checks the exact class declaration and
/// complete obligation before invoking the concrete implementation contract.
nonisolated struct BamlBridge_Cffi_V1_ConcreteMethodTarget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var receiver: UInt64 = 0

  var className: String = String()

  var dispatch: BamlBridge_Cffi_V1_ConcreteMethodTarget.OneOf_Dispatch? = nil

  var interfacePattern: BamlBridge_Cffi_V1_BamlTy {
    get {
      if case .interfacePattern(let v)? = dispatch {return v}
      return BamlBridge_Cffi_V1_BamlTy()
    }
    set {dispatch = .interfacePattern(newValue)}
  }

  /// Must be true when selected; a missing dispatch is an invalid request.
  var inherent: Bool {
    get {
      if case .inherent(let v)? = dispatch {return v}
      return false
    }
    set {dispatch = .inherent(newValue)}
  }

  var member: String = String()

  var typeArgs: [BamlBridge_Cffi_V1_BamlTyArg] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Dispatch: Equatable, Sendable {
    case interfacePattern(BamlBridge_Cffi_V1_BamlTy)
    /// Must be true when selected; a missing dispatch is an invalid request.
    case inherent(Bool)

  }

  init() {}
}

nonisolated struct BamlBridge_Cffi_V1_CallFunctionArgs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kwargs: [BamlBridge_Cffi_V1_InboundMapEntry] = []

  var callID: UInt64 = 0

  /// Explicit TypeVar bindings for a generic function/method call. Named and
  /// order-preserving: each entry self-describes its TypeVar, and entries are
  /// sent in De Bruijn order (enclosing class params first — recovered from a
  /// generic receiver's type args — then the callee's own `<...>` params,
  /// `_types=` in Python). The engine maps each named binding onto the entry
  /// frame's `type_args` slot by matching the TypeVar name against the callee's
  /// generic params (see `set_entry_point_with_type_args`). Empty for
  /// non-generic calls.
  var typeArgs: [BamlBridge_Cffi_V1_BamlTyArg] = []

  var callTarget: BamlBridge_Cffi_V1_CallFunctionArgs.OneOf_CallTarget? = nil

  var functionName: String {
    get {
      if case .functionName(let v)? = callTarget {return v}
      return String()
    }
    set {callTarget = .functionName(newValue)}
  }

  var functionHandle: UInt64 {
    get {
      if case .functionHandle(let v)? = callTarget {return v}
      return 0
    }
    set {callTarget = .functionHandle(newValue)}
  }

  var interfaceMethod: BamlBridge_Cffi_V1_InterfaceMethodTarget {
    get {
      if case .interfaceMethod(let v)? = callTarget {return v}
      return BamlBridge_Cffi_V1_InterfaceMethodTarget()
    }
    set {callTarget = .interfaceMethod(newValue)}
  }

  var concreteMethod: BamlBridge_Cffi_V1_ConcreteMethodTarget {
    get {
      if case .concreteMethod(let v)? = callTarget {return v}
      return BamlBridge_Cffi_V1_ConcreteMethodTarget()
    }
    set {callTarget = .concreteMethod(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_CallTarget: Equatable, Sendable {
    case functionName(String)
    case functionHandle(UInt64)
    case interfaceMethod(BamlBridge_Cffi_V1_InterfaceMethodTarget)
    case concreteMethod(BamlBridge_Cffi_V1_ConcreteMethodTarget)

  }

  init() {}
}

/// CallAck is the engine's acknowledgment of an inbound call. It flows
/// engine->host, but is defined in the inbound proto because it completes
/// the inbound call contract (CallFunctionArgs request + CallAck response).
nonisolated struct BamlBridge_Cffi_V1_CallAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: BamlBridge_Cffi_V1_CallAck.OneOf_Response? = nil

  var error: String {
    get {
      if case .error(let v)? = response {return v}
      return String()
    }
    set {response = .error(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Response: Equatable, Sendable {
    case error(String)

  }

  init() {}
}

/// Host adapter registration. No host callbacks are acquired at this stage.
/// Template type-var index 0 denotes Self. Index n+1 selects type_args[n].
/// Type arguments are positional and shared across the whole registration;
/// definitions are materialized once, references retain their issuing identity.
nonisolated struct BamlBridge_Cffi_V1_RegisterHostAdapterRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var implementations: [BamlBridge_Cffi_V1_HostAdapterImplementation] = []

  var typeArgs: [BamlBridge_Cffi_V1_BamlTyArg] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct BamlBridge_Cffi_V1_HostAdapterImplementation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var interfaceTemplate: BamlBridge_Cffi_V1_BamlTy {
    get {_interfaceTemplate ?? BamlBridge_Cffi_V1_BamlTy()}
    set {_interfaceTemplate = newValue}
  }
  /// Returns true if `interfaceTemplate` has been explicitly set.
  var hasInterfaceTemplate: Bool {self._interfaceTemplate != nil}
  /// Clears the value of `interfaceTemplate`. Subsequent reads from it will return its default value.
  mutating func clearInterfaceTemplate() {self._interfaceTemplate = nil}

  var methods: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _interfaceTemplate: BamlBridge_Cffi_V1_BamlTy? = nil
}

nonisolated struct BamlBridge_Cffi_V1_RegisteredHostAdapter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var adapterType: BamlBridge_Cffi_V1_BamlOutboundHandle {
    get {_adapterType ?? BamlBridge_Cffi_V1_BamlOutboundHandle()}
    set {_adapterType = newValue}
  }
  /// Returns true if `adapterType` has been explicitly set.
  var hasAdapterType: Bool {self._adapterType != nil}
  /// Clears the value of `adapterType`. Subsequent reads from it will return its default value.
  mutating func clearAdapterType() {self._adapterType = nil}

  var classType: BamlBridge_Cffi_V1_BamlOutboundHandle {
    get {_classType ?? BamlBridge_Cffi_V1_BamlOutboundHandle()}
    set {_classType = newValue}
  }
  /// Returns true if `classType` has been explicitly set.
  var hasClassType: Bool {self._classType != nil}
  /// Clears the value of `classType`. Subsequent reads from it will return its default value.
  mutating func clearClassType() {self._classType = nil}

  var callbacks: [BamlBridge_Cffi_V1_HostAdapterCallbackSlot] = []

  /// Exact checked interface types in request implementation order, including
  /// interfaces with no callbacks. Borrow these when projecting a new instance;
  /// importing a portable type definition again would create different types.
  var interfaceTypes: [BamlBridge_Cffi_V1_BamlOutboundHandle] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _adapterType: BamlBridge_Cffi_V1_BamlOutboundHandle? = nil
  fileprivate var _classType: BamlBridge_Cffi_V1_BamlOutboundHandle? = nil
}

nonisolated struct BamlBridge_Cffi_V1_HostAdapterCallbackSlot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Index into RegisterHostAdapterRequest.implementations. The pair of this
  /// index and method identifies an operation even when obligations share names.
  var implementationIndex: UInt32 = 0

  var method: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// adapter_type is borrowed and pinned by synchronous preparation. Receiver
/// and callbacks transfer their occurrences as one batch, including on failure.
nonisolated struct BamlBridge_Cffi_V1_CreateHostAdapterRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var adapterType: UInt64 = 0

  var receiver: BamlBridge_Cffi_V1_InboundValue {
    get {_receiver ?? BamlBridge_Cffi_V1_InboundValue()}
    set {_receiver = newValue}
  }
  /// Returns true if `receiver` has been explicitly set.
  var hasReceiver: Bool {self._receiver != nil}
  /// Clears the value of `receiver`. Subsequent reads from it will return its default value.
  mutating func clearReceiver() {self._receiver = nil}

  var callbacks: [BamlBridge_Cffi_V1_InboundValue] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _receiver: BamlBridge_Cffi_V1_InboundValue? = nil
}

/// The receiver is borrowed and retained during preparation. Type evidence has
/// the same named/definition/reference semantics as method type arguments.
nonisolated struct BamlBridge_Cffi_V1_ProjectInterfaceRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var receiver: UInt64 = 0

  var interfaceType: BamlBridge_Cffi_V1_BamlTyArg {
    get {_interfaceType ?? BamlBridge_Cffi_V1_BamlTyArg()}
    set {_interfaceType = newValue}
  }
  /// Returns true if `interfaceType` has been explicitly set.
  var hasInterfaceType: Bool {self._interfaceType != nil}
  /// Clears the value of `interfaceType`. Subsequent reads from it will return its default value.
  mutating func clearInterfaceType() {self._interfaceType = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _interfaceType: BamlBridge_Cffi_V1_BamlTyArg? = nil
}

/// Private SDK administrative channel. Each request selects exactly one
/// operation; preparation consumes create-input transfers before admission.
nonisolated struct BamlBridge_Cffi_V1_HostOperationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var operation: BamlBridge_Cffi_V1_HostOperationRequest.OneOf_Operation? = nil

  var register: BamlBridge_Cffi_V1_RegisterHostAdapterRequest {
    get {
      if case .register(let v)? = operation {return v}
      return BamlBridge_Cffi_V1_RegisterHostAdapterRequest()
    }
    set {operation = .register(newValue)}
  }

  var create: BamlBridge_Cffi_V1_CreateHostAdapterRequest {
    get {
      if case .create(let v)? = operation {return v}
      return BamlBridge_Cffi_V1_CreateHostAdapterRequest()
    }
    set {operation = .create(newValue)}
  }

  var project: BamlBridge_Cffi_V1_ProjectInterfaceRequest {
    get {
      if case .project(let v)? = operation {return v}
      return BamlBridge_Cffi_V1_ProjectInterfaceRequest()
    }
    set {operation = .project(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Operation: Equatable, Sendable {
    case register(BamlBridge_Cffi_V1_RegisterHostAdapterRequest)
    case create(BamlBridge_Cffi_V1_CreateHostAdapterRequest)
    case project(BamlBridge_Cffi_V1_ProjectInterfaceRequest)

  }

  init() {}
}

/// Carried by the same owned delivery/receipt as ordinary call results.
/// Registration metadata is not a BAML value. Failure reuses the ordinary
/// structured error/panic envelope (its ok arm is never produced here).
nonisolated struct BamlBridge_Cffi_V1_HostOperationResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: BamlBridge_Cffi_V1_HostOperationResult.OneOf_Result? = nil

  var registered: BamlBridge_Cffi_V1_RegisteredHostAdapter {
    get {
      if case .registered(let v)? = result {return v}
      return BamlBridge_Cffi_V1_RegisteredHostAdapter()
    }
    set {result = .registered(newValue)}
  }

  var value: BamlBridge_Cffi_V1_BamlOutboundValue {
    get {
      if case .value(let v)? = result {return v}
      return BamlBridge_Cffi_V1_BamlOutboundValue()
    }
    set {result = .value(newValue)}
  }

  var failure: BamlBridge_Cffi_V1_BamlOutboundResult {
    get {
      if case .failure(let v)? = result {return v}
      return BamlBridge_Cffi_V1_BamlOutboundResult()
    }
    set {result = .failure(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case registered(BamlBridge_Cffi_V1_RegisteredHostAdapter)
    case value(BamlBridge_Cffi_V1_BamlOutboundValue)
    case failure(BamlBridge_Cffi_V1_BamlOutboundResult)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "baml_bridge.cffi.v1"

nonisolated extension BamlBridge_Cffi_V1_InboundValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}value_type\0\u{3}string_value\0\u{3}int_value\0\u{3}float_value\0\u{3}bool_value\0\u{3}list_value\0\u{3}map_value\0\u{3}class_value\0\u{3}enum_value\0\u{1}handle\0\u{3}uint8array_value\0\u{3}bigint_value\0\u{3}ty_value\0\u{3}ty_def_value\0\u{3}media_value\0\u{3}prompt_ast_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._valueType) }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .stringValue(v)
        }
      }()
      case 3: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intValue(v)
        }
      }()
      case 4: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .floatValue(v)
        }
      }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolValue(v)
        }
      }()
      case 6: try {
        var v: BamlBridge_Cffi_V1_InboundListValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .listValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .listValue(v)
        }
      }()
      case 7: try {
        var v: BamlBridge_Cffi_V1_InboundMapValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .mapValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .mapValue(v)
        }
      }()
      case 8: try {
        var v: BamlBridge_Cffi_V1_InboundClassValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .classValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .classValue(v)
        }
      }()
      case 9: try {
        var v: BamlBridge_Cffi_V1_InboundEnumValue?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .enumValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .enumValue(v)
        }
      }()
      case 10: try {
        var v: BamlBridge_Cffi_V1_BamlHandle?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .handle(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .handle(v)
        }
      }()
      case 11: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .uint8ArrayValue(v)
        }
      }()
      case 12: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .bigintValue(v)
        }
      }()
      case 13: try {
        var v: BamlBridge_Cffi_V1_BamlTy?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .tyValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .tyValue(v)
        }
      }()
      case 14: try {
        var v: BamlBridge_Cffi_V1_BamlTyDef?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .tyDefValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .tyDefValue(v)
        }
      }()
      case 15: try {
        var v: BamlBridge_Cffi_V1_BamlValueMedia?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .mediaValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .mediaValue(v)
        }
      }()
      case 16: try {
        var v: BamlBridge_Cffi_V1_BamlValuePromptAst?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .promptAstValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .promptAstValue(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._valueType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    switch self.value {
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .intValue?: try {
      guard case .intValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    }()
    case .floatValue?: try {
      guard case .floatValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    }()
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case .listValue?: try {
      guard case .listValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .mapValue?: try {
      guard case .mapValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .classValue?: try {
      guard case .classValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .enumValue?: try {
      guard case .enumValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .handle?: try {
      guard case .handle(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .uint8ArrayValue?: try {
      guard case .uint8ArrayValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 11)
    }()
    case .bigintValue?: try {
      guard case .bigintValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    }()
    case .tyValue?: try {
      guard case .tyValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .tyDefValue?: try {
      guard case .tyDefValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .mediaValue?: try {
      guard case .mediaValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
    }()
    case .promptAstValue?: try {
      guard case .promptAstValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundValue, rhs: BamlBridge_Cffi_V1_InboundValue) -> Bool {
    if lhs._valueType != rhs._valueType {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InboundListValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundListValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}values\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundListValue, rhs: BamlBridge_Cffi_V1_InboundListValue) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InboundMapValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundMapValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundMapValue, rhs: BamlBridge_Cffi_V1_InboundMapValue) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InboundMapEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundMapEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}string_key\0\u{3}int_key\0\u{3}bool_key\0\u{4}\u{2}enum_key\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .stringKey(v)
        }
      }()
      case 2: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .intKey(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.key != nil {try decoder.handleConflictingOneOf()}
          self.key = .boolKey(v)
        }
      }()
      case 5: try {
        var v: BamlBridge_Cffi_V1_InboundEnumValue?
        var hadOneofValue = false
        if let current = self.key {
          hadOneofValue = true
          if case .enumKey(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.key = .enumKey(v)
        }
      }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.key {
    case .stringKey?: try {
      guard case .stringKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .intKey?: try {
      guard case .intKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    }()
    case .boolKey?: try {
      guard case .boolKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .enumKey?: try {
      guard case .enumKey(let v)? = self.key else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundMapEntry, rhs: BamlBridge_Cffi_V1_InboundMapEntry) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InboundClassValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundClassValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}fields\0\u{c}\u{1}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.fields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fields, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundClassValue, rhs: BamlBridge_Cffi_V1_InboundClassValue) -> Bool {
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InboundEnumValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InboundEnumValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InboundEnumValue, rhs: BamlBridge_Cffi_V1_InboundEnumValue) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_BamlTyArg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BamlTyArg"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}type_var\0\u{3}type_value\0\u{3}type_definition\0\u{3}type_reference\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeVar) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._typeValue) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._typeDefinition) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self._typeReference) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.typeVar.isEmpty {
      try visitor.visitSingularStringField(value: self.typeVar, fieldNumber: 1)
    }
    try { if let v = self._typeValue {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._typeDefinition {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._typeReference {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_BamlTyArg, rhs: BamlBridge_Cffi_V1_BamlTyArg) -> Bool {
    if lhs.typeVar != rhs.typeVar {return false}
    if lhs._typeValue != rhs._typeValue {return false}
    if lhs._typeDefinition != rhs._typeDefinition {return false}
    if lhs._typeReference != rhs._typeReference {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_InterfaceMethodTarget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InterfaceMethodTarget"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}view\0\u{1}member\0\u{3}type_args\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.view) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.member) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.typeArgs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.view != 0 {
      try visitor.visitSingularUInt64Field(value: self.view, fieldNumber: 1)
    }
    if !self.member.isEmpty {
      try visitor.visitSingularStringField(value: self.member, fieldNumber: 2)
    }
    if !self.typeArgs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.typeArgs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_InterfaceMethodTarget, rhs: BamlBridge_Cffi_V1_InterfaceMethodTarget) -> Bool {
    if lhs.view != rhs.view {return false}
    if lhs.member != rhs.member {return false}
    if lhs.typeArgs != rhs.typeArgs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_ConcreteMethodTarget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConcreteMethodTarget"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}receiver\0\u{3}class_name\0\u{3}interface_pattern\0\u{1}member\0\u{3}type_args\0\u{1}inherent\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.receiver) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.className) }()
      case 3: try {
        var v: BamlBridge_Cffi_V1_BamlTy?
        var hadOneofValue = false
        if let current = self.dispatch {
          hadOneofValue = true
          if case .interfacePattern(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.dispatch = .interfacePattern(v)
        }
      }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.member) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.typeArgs) }()
      case 6: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.dispatch != nil {try decoder.handleConflictingOneOf()}
          self.dispatch = .inherent(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.receiver != 0 {
      try visitor.visitSingularUInt64Field(value: self.receiver, fieldNumber: 1)
    }
    if !self.className.isEmpty {
      try visitor.visitSingularStringField(value: self.className, fieldNumber: 2)
    }
    try { if case .interfacePattern(let v)? = self.dispatch {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.member.isEmpty {
      try visitor.visitSingularStringField(value: self.member, fieldNumber: 4)
    }
    if !self.typeArgs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.typeArgs, fieldNumber: 5)
    }
    try { if case .inherent(let v)? = self.dispatch {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_ConcreteMethodTarget, rhs: BamlBridge_Cffi_V1_ConcreteMethodTarget) -> Bool {
    if lhs.receiver != rhs.receiver {return false}
    if lhs.className != rhs.className {return false}
    if lhs.dispatch != rhs.dispatch {return false}
    if lhs.member != rhs.member {return false}
    if lhs.typeArgs != rhs.typeArgs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_CallFunctionArgs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CallFunctionArgs"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kwargs\0\u{3}call_id\0\u{3}type_args\0\u{3}function_name\0\u{3}function_handle\0\u{3}interface_method\0\u{3}concrete_method\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.kwargs) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.callID) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.typeArgs) }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.callTarget != nil {try decoder.handleConflictingOneOf()}
          self.callTarget = .functionName(v)
        }
      }()
      case 5: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.callTarget != nil {try decoder.handleConflictingOneOf()}
          self.callTarget = .functionHandle(v)
        }
      }()
      case 6: try {
        var v: BamlBridge_Cffi_V1_InterfaceMethodTarget?
        var hadOneofValue = false
        if let current = self.callTarget {
          hadOneofValue = true
          if case .interfaceMethod(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.callTarget = .interfaceMethod(v)
        }
      }()
      case 7: try {
        var v: BamlBridge_Cffi_V1_ConcreteMethodTarget?
        var hadOneofValue = false
        if let current = self.callTarget {
          hadOneofValue = true
          if case .concreteMethod(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.callTarget = .concreteMethod(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.kwargs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.kwargs, fieldNumber: 1)
    }
    if self.callID != 0 {
      try visitor.visitSingularUInt64Field(value: self.callID, fieldNumber: 2)
    }
    if !self.typeArgs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.typeArgs, fieldNumber: 3)
    }
    switch self.callTarget {
    case .functionName?: try {
      guard case .functionName(let v)? = self.callTarget else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case .functionHandle?: try {
      guard case .functionHandle(let v)? = self.callTarget else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
    }()
    case .interfaceMethod?: try {
      guard case .interfaceMethod(let v)? = self.callTarget else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .concreteMethod?: try {
      guard case .concreteMethod(let v)? = self.callTarget else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_CallFunctionArgs, rhs: BamlBridge_Cffi_V1_CallFunctionArgs) -> Bool {
    if lhs.kwargs != rhs.kwargs {return false}
    if lhs.callID != rhs.callID {return false}
    if lhs.typeArgs != rhs.typeArgs {return false}
    if lhs.callTarget != rhs.callTarget {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_CallAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CallAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.response != nil {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .error(let v)? = self.response {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_CallAck, rhs: BamlBridge_Cffi_V1_CallAck) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_RegisterHostAdapterRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterHostAdapterRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}implementations\0\u{3}type_args\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.implementations) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.typeArgs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.implementations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.implementations, fieldNumber: 2)
    }
    if !self.typeArgs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.typeArgs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_RegisterHostAdapterRequest, rhs: BamlBridge_Cffi_V1_RegisterHostAdapterRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.implementations != rhs.implementations {return false}
    if lhs.typeArgs != rhs.typeArgs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_HostAdapterImplementation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostAdapterImplementation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}interface_template\0\u{1}methods\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._interfaceTemplate) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.methods) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._interfaceTemplate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.methods.isEmpty {
      try visitor.visitRepeatedStringField(value: self.methods, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_HostAdapterImplementation, rhs: BamlBridge_Cffi_V1_HostAdapterImplementation) -> Bool {
    if lhs._interfaceTemplate != rhs._interfaceTemplate {return false}
    if lhs.methods != rhs.methods {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_RegisteredHostAdapter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisteredHostAdapter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}adapter_type\0\u{3}class_type\0\u{1}callbacks\0\u{3}interface_types\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._adapterType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._classType) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.callbacks) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.interfaceTypes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._adapterType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._classType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.callbacks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.callbacks, fieldNumber: 3)
    }
    if !self.interfaceTypes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.interfaceTypes, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_RegisteredHostAdapter, rhs: BamlBridge_Cffi_V1_RegisteredHostAdapter) -> Bool {
    if lhs._adapterType != rhs._adapterType {return false}
    if lhs._classType != rhs._classType {return false}
    if lhs.callbacks != rhs.callbacks {return false}
    if lhs.interfaceTypes != rhs.interfaceTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_HostAdapterCallbackSlot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostAdapterCallbackSlot"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}method\0\u{4}\u{2}implementation_index\0\u{c}\u{2}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.method) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.implementationIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.method.isEmpty {
      try visitor.visitSingularStringField(value: self.method, fieldNumber: 1)
    }
    if self.implementationIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.implementationIndex, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_HostAdapterCallbackSlot, rhs: BamlBridge_Cffi_V1_HostAdapterCallbackSlot) -> Bool {
    if lhs.implementationIndex != rhs.implementationIndex {return false}
    if lhs.method != rhs.method {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_CreateHostAdapterRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateHostAdapterRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}adapter_type\0\u{1}receiver\0\u{1}callbacks\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.adapterType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._receiver) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.callbacks) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.adapterType != 0 {
      try visitor.visitSingularUInt64Field(value: self.adapterType, fieldNumber: 1)
    }
    try { if let v = self._receiver {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.callbacks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.callbacks, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_CreateHostAdapterRequest, rhs: BamlBridge_Cffi_V1_CreateHostAdapterRequest) -> Bool {
    if lhs.adapterType != rhs.adapterType {return false}
    if lhs._receiver != rhs._receiver {return false}
    if lhs.callbacks != rhs.callbacks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_ProjectInterfaceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProjectInterfaceRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}receiver\0\u{3}interface_type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.receiver) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._interfaceType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.receiver != 0 {
      try visitor.visitSingularUInt64Field(value: self.receiver, fieldNumber: 1)
    }
    try { if let v = self._interfaceType {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_ProjectInterfaceRequest, rhs: BamlBridge_Cffi_V1_ProjectInterfaceRequest) -> Bool {
    if lhs.receiver != rhs.receiver {return false}
    if lhs._interfaceType != rhs._interfaceType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_HostOperationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostOperationRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}register\0\u{1}create\0\u{1}project\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: BamlBridge_Cffi_V1_RegisterHostAdapterRequest?
        var hadOneofValue = false
        if let current = self.operation {
          hadOneofValue = true
          if case .register(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.operation = .register(v)
        }
      }()
      case 2: try {
        var v: BamlBridge_Cffi_V1_CreateHostAdapterRequest?
        var hadOneofValue = false
        if let current = self.operation {
          hadOneofValue = true
          if case .create(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.operation = .create(v)
        }
      }()
      case 3: try {
        var v: BamlBridge_Cffi_V1_ProjectInterfaceRequest?
        var hadOneofValue = false
        if let current = self.operation {
          hadOneofValue = true
          if case .project(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.operation = .project(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.operation {
    case .register?: try {
      guard case .register(let v)? = self.operation else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .create?: try {
      guard case .create(let v)? = self.operation else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .project?: try {
      guard case .project(let v)? = self.operation else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_HostOperationRequest, rhs: BamlBridge_Cffi_V1_HostOperationRequest) -> Bool {
    if lhs.operation != rhs.operation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension BamlBridge_Cffi_V1_HostOperationResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HostOperationResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}registered\0\u{1}value\0\u{1}failure\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: BamlBridge_Cffi_V1_RegisteredHostAdapter?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .registered(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .registered(v)
        }
      }()
      case 2: try {
        var v: BamlBridge_Cffi_V1_BamlOutboundValue?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .value(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .value(v)
        }
      }()
      case 3: try {
        var v: BamlBridge_Cffi_V1_BamlOutboundResult?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .failure(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .failure(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .registered?: try {
      guard case .registered(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .failure?: try {
      guard case .failure(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BamlBridge_Cffi_V1_HostOperationResult, rhs: BamlBridge_Cffi_V1_HostOperationResult) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
