import type { TestRequest } from '@baml/common'
import { fetchEventSource } from '@microsoft/fetch-event-source'
import { useSetAtom } from 'jotai'
import { useAtomCallback } from 'jotai/utils'
import posthog from 'posthog-js'
import { currentEditorFilesAtom } from '../_atoms/atoms'
import { TestState } from './TestState'

const serverBaseURL = 'http://localhost:8000'
const prodBaseURL = 'https://prompt-fiddle.fly.dev'
