name: "Setup Development Tools"
description: "Setup common development tools"

inputs:
  install-mise:
    description: "Install mise version manager"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Remove unused tools
      shell: bash
      run: |
        # from https://carlosbecker.com/posts/github-actions-disk-space/ and
        # https://github.com/marketplace/actions/maximize-build-disk-space-only-remove-unwanted-software
        # frees up about ~20G space
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install_args: "protoc-gen-go"
        cache: true
