[package]
name = "bridge_ctypes"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
baml_type = { workspace = true }
bex_project = { workspace = true }
base64 = { workspace = true }
indexmap = { workspace = true }
num-bigint = { workspace = true }
prost = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
web-time = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[features]
default = [ "aws-crypto" ]
aws-crypto = [ "bex_project/aws-crypto" ]
ring-crypto = [ "bex_project/ring-crypto" ]

[lints]
workspace = true
