import type { GateResult, Issue } from "./types";

// Mock dataset shaped like triage_issues rows after the whole pipeline has
// run. Nothing here is real; ids, PRs and logins are placeholders.

const greenGate = (crates: string[]): GateResult => ({
  ok: true,
  changed_crates: crates,
  steps: [
    { name: "fmt", ok: true, seconds: 4, exit_code: 0 },
    { name: "clippy", ok: true, seconds: 412, exit_code: 0 },
    ...crates
      .filter((c) => c !== "baml_tests")
      .map((c) => ({ name: `cargo test --lib -p ${c}`, ok: true, seconds: 96, exit_code: 0 })),
    { name: "nextest baml_tests", ok: true, seconds: 184, exit_code: 0 },
    { name: "insta baml_tests", ok: true, seconds: 190, exit_code: 0 },
    { name: "insta clean", ok: true, seconds: 0, exit_code: 0 },
    { name: "build baml-cli", ok: true, seconds: 61, exit_code: 0 },
    { name: "baml-cli test baml_src", ok: true, seconds: 73, exit_code: 0 },
  ],
});

export const ISSUES: Issue[] = [
  {
    id: "GH-4587",
    title: "`throws` clause with an unresolved type panics the compiler (index out of bounds)",
    description:
      "A `throws` clause naming a type that does not exist takes the compiler down with `index out of bounds` in `type_ref.rs:346` instead of reporting `E0002: unresolved type`.",
    shepherd: "codeshaunted",
    subsystem: "Compiler",
    repros: [
      {
        files: { "baml_src/main.baml": "function f() -> int throws Nope { 1 }" },
        command: "baml check",
        setup: null,
        expectation: { check: "should_not_compile", diagnostic_contains: "E0002" },
      },
    ],
    version: "0.17.0",
    feedback_ids: ["FB-01j9x7", "FB-01j9y2"],
    status: { state: "in_progress", pr: "https://github.com/BoundaryML/baml/pull/4641" },
    comments: [
      { author: "codeshaunted", body: "Guard looks right; want the fixture to also cover a generic arg.", at: "2026-08-29T18:20:00Z" },
    ],
    resolution_plan: "Bounds-check the type-ref lookup before lowering the throws clause; report E0002.",
    difficulty: "Easy",
    design_doc: null,
    outcome: {
      kind: "fixed",
      branch: "agent/gh-4587-throws-clause-with-an-unresolved",
      pr: "https://github.com/BoundaryML/baml/pull/4641",
      turns: 12,
      seconds: 640,
      timed_out: false,
      gate: greenGate(["baml_compiler2_hir", "baml_tests"]),
      design_doc: null,
      reason: null,
    },
    created_at: "2026-08-27T09:12:00Z",
    updated_at: "2026-08-29T18:20:00Z",
  },
  {
    id: "GH-4468",
    title: "Empty-array match arm next to string[] arms crashes the checker when the binding type is inferred",
    description:
      "`let owners = match (x) { A => [\"a\"], B => [] }` hits an ICE in unification. Annotating the binding as `string[]` avoids it.",
    shepherd: "antoniosarosi",
    subsystem: "Compiler",
    repros: [
      {
        files: {
          "baml_src/main.baml":
            'enum K { A, B }\nfunction f(k: K) -> string[] {\n    let owners = match (k) { K.A => ["a"], K.B => [] };\n    owners\n}',
        },
        command: "baml check",
        setup: null,
        expectation: { check: "should_compile" },
      },
    ],
    version: "0.17.0",
    feedback_ids: ["FB-01j8q1"],
    status: { state: "open" },
    comments: [],
    resolution_plan: "Unify the empty-array literal with the join of the other arms before defaulting.",
    difficulty: "Medium",
    design_doc: null,
    outcome: {
      kind: "gate_failed",
      branch: "agent/gh-4468-empty-array-match-arm-next-to-string",
      pr: null,
      turns: 41,
      seconds: 5210,
      timed_out: false,
      gate: {
        ok: false,
        changed_crates: ["baml_type", "baml_compiler2_hir_ty", "baml_tests"],
        steps: [
          { name: "fmt", ok: true, seconds: 4, exit_code: 0 },
          { name: "clippy", ok: true, seconds: 388, exit_code: 0 },
          { name: "cargo test --lib -p baml_type", ok: true, seconds: 44, exit_code: 0 },
          { name: "cargo test --lib -p baml_compiler2_hir_ty", ok: true, seconds: 120, exit_code: 0 },
          { name: "nextest baml_tests", ok: false, seconds: 201, exit_code: 100 },
        ],
      },
      design_doc: null,
      reason: null,
    },
    created_at: "2026-08-24T14:02:00Z",
    updated_at: "2026-08-30T02:41:00Z",
  },
  {
    id: "GH-4506",
    title: "Streaming a union of classes drops the discriminant on the first partial",
    description:
      "With `stream` on a function returning `A | B`, the first partial arrives with no discriminant so clients cannot tell which branch is being filled.",
    shepherd: "2kai2kai2",
    subsystem: "Runtime",
    repros: [
      {
        files: { "baml_src/main.baml": "// see attached stream.baml" },
        command: "baml run -e main()",
        setup: null,
        expectation: { check: "requires_inspection", instructions: "Watch the first partial event." },
      },
    ],
    version: "0.16.2",
    feedback_ids: ["FB-01j7aa", "FB-01j7ab", "FB-01j7ac"],
    status: { state: "open" },
    comments: [
      { author: "2kai2kai2", body: "This interacts with the partial-type derivation; needs a design.", at: "2026-08-28T11:00:00Z" },
    ],
    resolution_plan: null,
    difficulty: "Hard",
    design_doc:
      "## Suggested fix\n\nEmit the discriminant with the first partial by deriving it eagerly from the class the parser committed to.\n\n## Problem\n...",
    outcome: {
      kind: "hard",
      branch: "agent/gh-4506-streaming-a-union-of-classes-drops",
      pr: null,
      turns: 23,
      seconds: 1710,
      timed_out: false,
      gate: null,
      design_doc: "## Suggested fix ...",
      reason: null,
    },
    created_at: "2026-08-21T08:30:00Z",
    updated_at: "2026-08-28T11:00:00Z",
  },
  {
    id: "GH-4612",
    title: "`baml fmt` reorders `//#` header comments away from the statement they annotate",
    description:
      "Formatting a function with `//#` step headers moves the comment above the preceding `let`, so the playground graph labels the wrong step.",
    shepherd: "sxlijin",
    subsystem: "Tooling",
    repros: [
      {
        files: { "baml_src/main.baml": "function f() -> int {\n    let a = 1;\n    //# add one\n    a + 1\n}" },
        command: "baml fmt --check",
        setup: null,
        expectation: { check: "should_compile" },
      },
    ],
    version: "0.17.0",
    feedback_ids: ["FB-01ja01"],
    status: { state: "in_progress", pr: null },
    comments: [],
    resolution_plan: "Attach `//#` comments as leading trivia of the next statement in the formatter.",
    difficulty: "Easy",
    design_doc: null,
    outcome: {
      kind: "fixed",
      branch: "agent/gh-4612-baml-fmt-reorders-header-comments",
      pr: null,
      turns: 9,
      seconds: 1320,
      timed_out: false,
      gate: null,
      design_doc: null,
      reason: null,
      running: "fix",
    },
    created_at: "2026-08-29T20:15:00Z",
    updated_at: "2026-08-30T03:05:00Z",
  },
  {
    id: "GH-4432",
    title: "`baml.json.from_string<T>` on a map with integer-like keys returns strings",
    description:
      "`from_string<map<int, string>>` parses fine but the keys come back as strings; `.get(1)` misses.",
    shepherd: "codeshaunted",
    subsystem: "StdLibrary",
    repros: [
      {
        files: { "baml_src/main.baml": 'function repro_main() -> string? {\n    let m = baml.json.from_string<map<int, string>>("{\\"1\\": \\"a\\"}");\n    m.get(1)\n}' },
        command: "baml run -e repro_main()",
        setup: null,
        expectation: { check: "should_evaluate_to", expected: "a" },
      },
    ],
    version: "0.16.0",
    feedback_ids: ["FB-01j5zz"],
    status: { state: "merged", pr: "https://github.com/BoundaryML/baml/pull/4590" },
    comments: [],
    resolution_plan: "Coerce JSON object keys through the declared key type in the map decoder.",
    difficulty: "Easy",
    design_doc: null,
    outcome: {
      kind: "fixed",
      branch: "agent/gh-4432-baml-json-from-string-on-a-map",
      pr: "https://github.com/BoundaryML/baml/pull/4590",
      turns: 15,
      seconds: 902,
      timed_out: false,
      gate: greenGate(["bex_vm", "baml_tests"]),
      design_doc: null,
      reason: null,
    },
    created_at: "2026-08-18T10:00:00Z",
    updated_at: "2026-08-26T16:44:00Z",
  },
  {
    id: "GH-4401",
    title: "Backtick string with an escaped `${` inside a `${}` interpolation fails to parse",
    description:
      "`\\${` inside an interpolation expression is treated as the start of a nested interpolation.",
    shepherd: "aaronvg",
    subsystem: "Syntax",
    repros: [
      {
        files: { "baml_src/main.baml": 'function f() -> string {\n    `a ${"\\${b}"} c`\n}' },
        command: "baml check",
        setup: null,
        expectation: { check: "should_compile" },
      },
    ],
    version: "0.15.4",
    feedback_ids: ["FB-01j4k2"],
    status: { state: "shipped", version: "0.17.0", date: "2026-08-20" },
    comments: [],
    resolution_plan: null,
    difficulty: "Trivial",
    design_doc: null,
    outcome: {
      kind: "fixed",
      branch: "agent/gh-4401-backtick-string-with-an-escaped",
      pr: "https://github.com/BoundaryML/baml/pull/4415",
      turns: 6,
      seconds: 480,
      timed_out: false,
      gate: greenGate(["baml_syntax", "baml_tests"]),
      design_doc: null,
      reason: null,
    },
    created_at: "2026-08-10T07:20:00Z",
    updated_at: "2026-08-20T12:00:00Z",
  },
  {
    id: "ISSUE-01k3v8s2m9",
    title: "`baml test` exits 0 when a testset's PassRate is not met but no single test failed",
    description:
      "A PassRate(0.8) testset with 70% passing prints the shortfall but the process still exits 0, so CI stays green.",
    shepherd: null,
    subsystem: "Tooling",
    repros: [
      {
        files: { "baml_src/main.baml": "// testset with PassRate(0.8) and 10 tests, 7 pass" },
        command: "baml test; echo $?",
        setup: null,
        expectation: { check: "requires_inspection", instructions: "Exit code should be non-zero." },
      },
    ],
    version: "0.17.0",
    feedback_ids: ["FB-01jb77"],
    status: { state: "open" },
    comments: [],
    resolution_plan: "Fold the testset verdict into the process exit code.",
    difficulty: null,
    design_doc: null,
    outcome: null,
    created_at: "2026-08-30T01:10:00Z",
    updated_at: "2026-08-30T01:10:00Z",
  },
  {
    id: "GH-4377",
    title: "Agent ran out of budget: `claude_code.ClaudeCodeClient` ignores `timeout_ms` on macOS",
    description:
      "The process wait timeout is not honoured when the CLI is launched through the client on macOS; runs hang past the budget.",
    shepherd: "sxlijin",
    subsystem: "Runtime",
    repros: [
      {
        files: { "baml_src/main.baml": "// client with timeout_ms = 1000 and a prompt that takes longer" },
        command: "baml run -e main()",
        setup: null,
        expectation: { check: "requires_inspection", instructions: "Should stop after ~1s." },
      },
    ],
    version: "0.16.2",
    feedback_ids: ["FB-01j3aa"],
    status: { state: "open" },
    comments: [],
    resolution_plan: "Use a kill-on-drop child and a tokio timeout around wait().",
    difficulty: "Medium",
    design_doc: null,
    outcome: {
      kind: "agent_stopped",
      branch: "agent/gh-4377-agent-ran-out-of-budget",
      pr: null,
      turns: 58,
      seconds: 7200,
      timed_out: true,
      gate: null,
      design_doc: "## Suggested fix ...",
      reason: "killed at the time budget",
    },
    created_at: "2026-08-08T13:00:00Z",
    updated_at: "2026-08-29T09:30:00Z",
  },
  {
    id: "GH-4290",
    title: "Request: `baml describe` should print default parameter values",
    description: "Defaults are visible in source but not in `baml describe` output.",
    shepherd: "sxlijin",
    subsystem: "Tooling",
    repros: [],
    version: "0.16.0",
    feedback_ids: ["FB-01j2bb", "FB-01j2bc"],
    status: { state: "deferred", reason: "Waiting on the describe output redesign.", workaround: "Read the source." },
    comments: [{ author: "sxlijin", body: "Folding into the describe rework next month.", at: "2026-08-15T10:00:00Z" }],
    resolution_plan: null,
    difficulty: "Easy",
    design_doc: null,
    outcome: null,
    created_at: "2026-08-01T09:00:00Z",
    updated_at: "2026-08-15T10:00:00Z",
  },
  {
    id: "GH-4310",
    title: "Playground shows stale graph after renaming a function",
    description: "After a rename the control-flow graph keeps the old node label until reload.",
    shepherd: "aaronvg",
    subsystem: "Tooling",
    repros: [],
    version: "0.16.1",
    feedback_ids: ["FB-01j2zz"],
    status: { state: "rejected", reason: "Duplicate of GH-4302, fixed in 0.16.3." },
    comments: [],
    resolution_plan: null,
    difficulty: "Trivial",
    design_doc: null,
    outcome: null,
    created_at: "2026-08-03T15:00:00Z",
    updated_at: "2026-08-04T08:00:00Z",
  },
  {
    id: "GH-4599",
    title: "Interface default method body cannot call another default method of the same interface",
    description:
      "Calling `self.other()` from a default method body reports `E0311: method not found` although `other` has a default body.",
    shepherd: "antoniosarosi",
    subsystem: "Compiler",
    repros: [
      {
        files: {
          "baml_src/main.baml":
            "interface I {\n    fn a(self) -> int { 1 }\n    fn b(self) -> int { self.a() + 1 }\n}",
        },
        command: "baml check",
        setup: null,
        expectation: { check: "should_compile" },
      },
    ],
    version: "0.17.0",
    feedback_ids: ["FB-01jaq9"],
    status: { state: "open" },
    comments: [],
    resolution_plan: "Resolve `self` methods against the interface's own default set during lowering.",
    difficulty: "Medium",
    design_doc: null,
    outcome: {
      kind: "fixed",
      branch: "agent/gh-4599-interface-default-method-body",
      pr: null,
      turns: 4,
      seconds: 300,
      timed_out: false,
      gate: null,
      design_doc: null,
      reason: null,
      running: "design",
    },
    created_at: "2026-08-29T22:00:00Z",
    updated_at: "2026-08-30T03:40:00Z",
  },
];

export function findIssue(id: string): Issue | undefined {
  return ISSUES.find((i) => i.id === id);
}
