// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClassWithBlockDone struct {
	I_16_digits int64  `json:"i_16_digits"`
	S_20_words  string `json:"s_20_words"`
}

func (c *ClassWithBlockDone) Decode(holder cffi.CFFIValueClass) {
	typeName := holder.Name(nil)
	if string(typeName.Namespace()) != "types" {
		panic(fmt.Sprintf("expected types, got %s", string(typeName.Namespace())))
	}
	if string(typeName.Name()) != "ClassWithBlockDone" {
		panic(fmt.Sprintf("expected ClassWithBlockDone, got %s", string(typeName.Name())))
	}

	for i := range holder.FieldsLength() {
		var field cffi.CFFIMapEntry
		if holder.Fields(&field, i) {
			key := string(field.Key())
			valueHolder := field.Value(nil)
			switch key {

			case "i_16_digits":
				c.I_16_digits = *baml.Decode(valueHolder).(*int64)

			case "s_20_words":
				c.S_20_words = *baml.Decode(valueHolder).(*string)

			}
		}
	}

}

func (c ClassWithBlockDone) Encode(builder *flatbuffers.Builder) (cffi.CFFIValueUnion, flatbuffers.UOffsetT, error) {
	fields := map[string]any{}

	fields["i_16_digits"] = c.I_16_digits

	fields["s_20_words"] = c.S_20_words

	return baml.EncodeClass(builder, c.BamlEncodeName, fields, nil)
}

func (c ClassWithBlockDone) BamlTypeName() string {
	return "ClassWithBlockDone"
}

func (u ClassWithBlockDone) BamlEncodeName(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString("ClassWithBlockDone")
	namespaceOffset := builder.CreateString("types")
	cffi.CFFITypeNameStart(builder)
	cffi.CFFITypeNameAddName(builder, nameOffset)
	cffi.CFFITypeNameAddNamespace(builder, namespaceOffset)
	return cffi.CFFITypeNameEnd(builder)
}

type ClassWithoutDone struct {
	I_16_digits int64  `json:"i_16_digits"`
	S_20_words  string `json:"s_20_words"`
}

func (c *ClassWithoutDone) Decode(holder cffi.CFFIValueClass) {
	typeName := holder.Name(nil)
	if string(typeName.Namespace()) != "types" {
		panic(fmt.Sprintf("expected types, got %s", string(typeName.Namespace())))
	}
	if string(typeName.Name()) != "ClassWithoutDone" {
		panic(fmt.Sprintf("expected ClassWithoutDone, got %s", string(typeName.Name())))
	}

	for i := range holder.FieldsLength() {
		var field cffi.CFFIMapEntry
		if holder.Fields(&field, i) {
			key := string(field.Key())
			valueHolder := field.Value(nil)
			switch key {

			case "i_16_digits":
				c.I_16_digits = *baml.Decode(valueHolder).(*int64)

			case "s_20_words":
				c.S_20_words = *baml.Decode(valueHolder).(*string)

			}
		}
	}

}

func (c ClassWithoutDone) Encode(builder *flatbuffers.Builder) (cffi.CFFIValueUnion, flatbuffers.UOffsetT, error) {
	fields := map[string]any{}

	fields["i_16_digits"] = c.I_16_digits

	fields["s_20_words"] = c.S_20_words

	return baml.EncodeClass(builder, c.BamlEncodeName, fields, nil)
}

func (c ClassWithoutDone) BamlTypeName() string {
	return "ClassWithoutDone"
}

func (u ClassWithoutDone) BamlEncodeName(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString("ClassWithoutDone")
	namespaceOffset := builder.CreateString("types")
	cffi.CFFITypeNameStart(builder)
	cffi.CFFITypeNameAddName(builder, nameOffset)
	cffi.CFFITypeNameAddNamespace(builder, namespaceOffset)
	return cffi.CFFITypeNameEnd(builder)
}

type SemanticContainer struct {
	Sixteen_digit_number     int64              `json:"sixteen_digit_number"`
	String_with_twenty_words string             `json:"string_with_twenty_words"`
	Class_1                  ClassWithoutDone   `json:"class_1"`
	Class_2                  ClassWithBlockDone `json:"class_2"`
	Class_done_needed        ClassWithBlockDone `json:"class_done_needed"`
	Class_needed             ClassWithoutDone   `json:"class_needed"`
	Three_small_things       []SmallThing       `json:"three_small_things"`
	Final_string             string             `json:"final_string"`
}

func (c *SemanticContainer) Decode(holder cffi.CFFIValueClass) {
	typeName := holder.Name(nil)
	if string(typeName.Namespace()) != "types" {
		panic(fmt.Sprintf("expected types, got %s", string(typeName.Namespace())))
	}
	if string(typeName.Name()) != "SemanticContainer" {
		panic(fmt.Sprintf("expected SemanticContainer, got %s", string(typeName.Name())))
	}

	for i := range holder.FieldsLength() {
		var field cffi.CFFIMapEntry
		if holder.Fields(&field, i) {
			key := string(field.Key())
			valueHolder := field.Value(nil)
			switch key {

			case "sixteen_digit_number":
				c.Sixteen_digit_number = *baml.Decode(valueHolder).(*int64)

			case "string_with_twenty_words":
				c.String_with_twenty_words = *baml.Decode(valueHolder).(*string)

			case "class_1":
				c.Class_1 = *baml.Decode(valueHolder).(*ClassWithoutDone)

			case "class_2":
				c.Class_2 = *baml.Decode(valueHolder).(*ClassWithBlockDone)

			case "class_done_needed":
				c.Class_done_needed = *baml.Decode(valueHolder).(*ClassWithBlockDone)

			case "class_needed":
				c.Class_needed = *baml.Decode(valueHolder).(*ClassWithoutDone)

			case "three_small_things":
				c.Three_small_things = baml.DecodeList(valueHolder, func(inner *cffi.CFFIValueHolder) SmallThing {
					return *baml.Decode(inner).(*SmallThing)
				})

			case "final_string":
				c.Final_string = *baml.Decode(valueHolder).(*string)

			}
		}
	}

}

func (c SemanticContainer) Encode(builder *flatbuffers.Builder) (cffi.CFFIValueUnion, flatbuffers.UOffsetT, error) {
	fields := map[string]any{}

	fields["sixteen_digit_number"] = c.Sixteen_digit_number

	fields["string_with_twenty_words"] = c.String_with_twenty_words

	fields["class_1"] = c.Class_1

	fields["class_2"] = c.Class_2

	fields["class_done_needed"] = c.Class_done_needed

	fields["class_needed"] = c.Class_needed

	fields["three_small_things"] = c.Three_small_things

	fields["final_string"] = c.Final_string

	return baml.EncodeClass(builder, c.BamlEncodeName, fields, nil)
}

func (c SemanticContainer) BamlTypeName() string {
	return "SemanticContainer"
}

func (u SemanticContainer) BamlEncodeName(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString("SemanticContainer")
	namespaceOffset := builder.CreateString("types")
	cffi.CFFITypeNameStart(builder)
	cffi.CFFITypeNameAddName(builder, nameOffset)
	cffi.CFFITypeNameAddNamespace(builder, namespaceOffset)
	return cffi.CFFITypeNameEnd(builder)
}

type SmallThing struct {
	I_16_digits int64 `json:"i_16_digits"`
	I_8_digits  int64 `json:"i_8_digits"`
}

func (c *SmallThing) Decode(holder cffi.CFFIValueClass) {
	typeName := holder.Name(nil)
	if string(typeName.Namespace()) != "types" {
		panic(fmt.Sprintf("expected types, got %s", string(typeName.Namespace())))
	}
	if string(typeName.Name()) != "SmallThing" {
		panic(fmt.Sprintf("expected SmallThing, got %s", string(typeName.Name())))
	}

	for i := range holder.FieldsLength() {
		var field cffi.CFFIMapEntry
		if holder.Fields(&field, i) {
			key := string(field.Key())
			valueHolder := field.Value(nil)
			switch key {

			case "i_16_digits":
				c.I_16_digits = *baml.Decode(valueHolder).(*int64)

			case "i_8_digits":
				c.I_8_digits = *baml.Decode(valueHolder).(*int64)

			}
		}
	}

}

func (c SmallThing) Encode(builder *flatbuffers.Builder) (cffi.CFFIValueUnion, flatbuffers.UOffsetT, error) {
	fields := map[string]any{}

	fields["i_16_digits"] = c.I_16_digits

	fields["i_8_digits"] = c.I_8_digits

	return baml.EncodeClass(builder, c.BamlEncodeName, fields, nil)
}

func (c SmallThing) BamlTypeName() string {
	return "SmallThing"
}

func (u SmallThing) BamlEncodeName(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	nameOffset := builder.CreateString("SmallThing")
	namespaceOffset := builder.CreateString("types")
	cffi.CFFITypeNameStart(builder)
	cffi.CFFITypeNameAddName(builder, nameOffset)
	cffi.CFFITypeNameAddNamespace(builder, namespaceOffset)
	return cffi.CFFITypeNameEnd(builder)
}
