[package]
name = "baml_package_interface"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
baml_base = { workspace = true }
baml_compiler2_ast = { workspace = true }
baml_type = { workspace = true }
borsh = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
