// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated union types.

use super::*;
use baml::{
    BamlDecode, BamlEncode, BamlSerde,
    __internal::serde::{Deserialize, Serialize},
};

/// Generated from: (int | Recursive1[])
#[derive(Debug, Clone, BamlEncode, BamlDecode, BamlSerde, Serialize, Deserialize)]
#[baml(union)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Union2IntOrListRecursive1 {
    #[baml(name = "int")]
    Int(i64),

    #[baml(name = "List__Recursive1")]
    ListRecursive1(Vec<Recursive1>),
}

impl ::std::convert::AsRef<Union2IntOrListRecursive1> for Union2IntOrListRecursive1 {
    fn as_ref(&self) -> &Union2IntOrListRecursive1 {
        self
    }
}

impl ::std::default::Default for Union2IntOrListRecursive1 {
    fn default() -> Self {
        Self::Int(::std::default::Default::default())
    }
}

/// Generated from: ("service" | "resource")
#[derive(
    Debug, Clone, BamlEncode, BamlDecode, BamlSerde, Serialize, Deserialize, PartialEq, Eq, Hash,
)]
#[baml(union)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Union2KresourceOrKservice {
    #[baml(name = "string_service", literal_string = "service")]
    #[serde(with = "__baml_serde_union_literal_Union2KresourceOrKservice::Kservice")]
    Kservice,

    #[baml(name = "string_resource", literal_string = "resource")]
    #[serde(with = "__baml_serde_union_literal_Union2KresourceOrKservice::Kresource")]
    Kresource,
}

impl ::std::convert::AsRef<Union2KresourceOrKservice> for Union2KresourceOrKservice {
    fn as_ref(&self) -> &Union2KresourceOrKservice {
        self
    }
}

impl ::std::default::Default for Union2KresourceOrKservice {
    fn default() -> Self {
        Self::Kservice
    }
}

/// Generated from: (Recursive1 | int | string | null)
#[derive(Debug, Clone, BamlEncode, BamlDecode, BamlSerde, Serialize, Deserialize)]
#[baml(union)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Union3IntOrRecursive1OrString {
    #[baml(name = "Recursive1")]
    Recursive1(Recursive1),

    #[baml(name = "int")]
    Int(i64),

    #[baml(name = "string")]
    String(String),
}

impl ::std::convert::AsRef<Union3IntOrRecursive1OrString> for Union3IntOrRecursive1OrString {
    fn as_ref(&self) -> &Union3IntOrRecursive1OrString {
        self
    }
}

impl ::std::default::Default for Union3IntOrRecursive1OrString {
    fn default() -> Self {
        Self::Recursive1(::std::default::Default::default())
    }
}
