# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from baml_core.stream import AsyncStream
from baml_lib._impl.functions import BaseBAMLFunction
from typing import AsyncIterator, Callable, Protocol, runtime_checkable


IPromptTestOutput = str

@runtime_checkable
class IPromptTest(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        str
    """

    async def __call__(self, arg: str, /) -> str:
        ...

   

@runtime_checkable
class IPromptTestStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[str, str]
    """

    def __call__(self, arg: str, /) -> AsyncStream[str, str]:
        ...
class IBAMLPromptTest(BaseBAMLFunction[str, str]):
    def __init__(self) -> None:
        super().__init__(
            "PromptTest",
            IPromptTest,
            ["claude_chat", "claude_chat_with_chat_msgs", "openai_chat", "openai_chat_with_chat_msgs"],
        )

    async def __call__(self, *args, **kwargs) -> str:
        return await self.get_impl("claude_chat").run(*args, **kwargs)
    
    def stream(self, *args, **kwargs) -> AsyncStream[str, str]:
        res = self.get_impl("claude_chat").stream(*args, **kwargs)
        return res

BAMLPromptTest = IBAMLPromptTest()

__all__ = [ "BAMLPromptTest" ]
