// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cffi

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CFFIMediaContentBase64 struct {
	_tab flatbuffers.Table
}

func GetRootAsCFFIMediaContentBase64(buf []byte, offset flatbuffers.UOffsetT) *CFFIMediaContentBase64 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CFFIMediaContentBase64{}
	x.Init(buf, n+offset)
	return x
}

func FinishCFFIMediaContentBase64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCFFIMediaContentBase64(buf []byte, offset flatbuffers.UOffsetT) *CFFIMediaContentBase64 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CFFIMediaContentBase64{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCFFIMediaContentBase64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CFFIMediaContentBase64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CFFIMediaContentBase64) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CFFIMediaContentBase64) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CFFIMediaContentBase64Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CFFIMediaContentBase64AddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func CFFIMediaContentBase64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
