#!/usr/bin/env /bin/sh

set -eu

show_help() {
  cat <<EOF
Usage: build [options]

Options:
    --help      Display this help message and exit.
    --watch     Watch dependencies and rebuild on demand.
    --test      In addition to build, run tests
EOF
}

_help_mode=0
_watch_mode=0
_test_mode=0

while [ $# -gt 0 ]; do
    case "$1" in
        --help)
            _help_mode=1
            shift
            ;;
        --watch)
            _watch_mode=1
            shift
            ;;
        --test)
            _test_mode=1
            shift
            ;;
        --) # End of all options
            shift
            break
            ;;
        *) # No more options
            break
            ;;
    esac
done

if [ "$_help_mode" -eq 1 ]; then
    show_help
    exit 0
fi

# Display the status of flags
if [ "$_watch_mode" -eq 1 ]; then
    echo "Interactive mode is enabled."
else
    echo "Interactive mode is not enabled."
fi

if [ "$_test_mode" -eq 1 ]; then
    echo "Testing is enabled."
else
    echo "Testing is not enabled."
fi

cd "$1"
_repo_root="$(git rev-parse --show-toplevel)"
_path="$(pwd | sed "s|^${_repo_root}||")"
echo "Building in REPO${_path} (cwd: $(pwd))"

case "$_path" in

  /engine/baml-core-ffi | /engine/baml-core-ffi/*)
    if [ "$_watch_mode" -eq 1 ]; then
      npx nodemon \
        --verbose \
        --ext js,ts \
        --ignore index.js \
        --ignore index.d.ts \
        --exec 'yarn build; date'
    else
      yarn build
      date
    fi
    ;;

  # Subdirectories of engine must be matched before this line
  /engine | /engine/* )
    if [ "$_test_mode" -eq 1 ]; then
      command="cargo build && cargo test; date"
    else
      command="cargo build; date"
    fi

    if [ "$_watch_mode" -eq 1 ]; then
      npx nodemon \
        --verbose \
        --ext rs,hb,hbs,toml \
        --ignore 'target' \
        --exec "${command}"
    else
      ${command}
    fi
    ;;

  /clients/python | /clients/python/* )
    command="env -u CONDA_PREFIX poetry run maturin develop --manifest-path ${_repo_root}/clients/python-ffi/Cargo.toml"
    #command="${command} && poetry run mypy ."
    #command="${command} && poetry run ruff check"
    command="${command} && poetry run ruff format"
    command="${command} && poetry run -- python -m baml_core.jinja.render_prompt"
    if [ "$_test_mode" -eq 1 ]; then
      command="${command} && poetry run -- pytest baml_core"
    fi
    command="${command}; date"
    if [ "$_watch_mode" -eq 1 ]; then
      npx nodemon \
        --ext py,pyi,rs \
        --watch "${_repo_root}/engine/baml-lib/jinja" \
        --watch "${_repo_root}/clients/python-ffi" \
        --watch . \
        --exec "${command}"
    else
      eval "${command}"
      date
    fi
    ;;

  /clients/ts | /clients/ts/* )
    pnpm link "${_repo_root}/engine/baml-core-ffi"
    if [ "$_watch_mode" -eq 1 ]; then
      npx nodemon \
        --verbose \
        --ext js,ts \
        --ignore '**/dist' \
        --ignore '**/node_modules' \
        --exec 'pnpm build; date'
    else
      pnpm build
      date
    fi
    ;;

  /integ-tests | /integ-tests/* )
    if [ "$_watch_mode" -eq 1 ]; then
      npx nodemon \
        --verbose \
        --watch "${_repo_root}/engine/target/debug/baml" \
        --exec "${_repo_root}/engine/target/debug/baml build; date"
    else
      "${_repo_root}/engine/target/debug/baml" build
      date
    fi
    ;;

  /typescript | /typescript/* )
    # This also consume schanges to baml-schema-wasm
    if [ "$_watch_mode" -eq 1 ]; then
      # nodemon config in typescript/nodemon.json
      npx nodemon \
        --verbose \
        --ext js,ts,tsx,rs,hb,hbs,toml \
        --watch "${_repo_root}/engine/baml-fmt" \
        --watch "${_repo_root}/engine/jinja" \
        --watch "${_repo_root}/typescript" \
        --ignore '**/dist' \
        --ignore '**/node_modules' \
        --ignore '**/out' \
        --exec 'pnpm build; date'
    else
      pnpm build
      date
    fi
    ;;

  *)
    echo "Nothing to build in repo root"
    ;;

esac

