edition = "2024"
style_edition = "2024"

# Shorthand syntax
use_field_init_shorthand = true

# Unstable but useful (need nightly rustfmt)
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
reorder_impl_items = true
