use crate::dir_writer::LanguageFeatures;

#[derive(Default)]
pub(super) struct RubyLanguageFeatures {}

impl LanguageFeatures for RubyLanguageFeatures {
    const CONTENT_PREFIX: &'static str =
        // "typed: strict" is set on a per-file basis in Ruby
        r#"
###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
        "#;
}

pub(super) trait ToRuby {
    fn to_ruby(&self) -> String;
}
