// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};
use std::collections::HashMap;

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]
pub struct Example {
    pub r#type: String,

    pub a: Checked<i64>,

    pub b: String,
}

impl AsRef<Example> for Example {
    fn as_ref(&self) -> &Example {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]
pub struct Example2 {
    pub r#type: String,

    pub item: Example,

    pub element: String,

    pub element2: String,
}

impl AsRef<Example2> for Example2 {
    fn as_ref(&self) -> &Example2 {
        self
    }
}
