[package]
name = "internal-baml-jinja"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: disable imports, etc
minijinja = { version = "1.0.16", default-features = false, features = [
  "macros",
  "builtins",
  "debug",
  "preserve_order",
  "adjacent_loop_items",
  "unicode",
  "json",
  "unstable_machinery",
  "unstable_machinery_serde",
  "custom_syntax",
  "internal_debug",
  # We don't want to use these features:
  # multi_template
  # loader
  #
] }
anyhow.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
log = "0.4.14"
strsim = "0.11.1"

[dev-dependencies]
env_logger = "0.11.3"
