[package]
name = "baml"
version = "0.2.1"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[features]
default = [  ]
no-self-update = [  ]

[dependencies]
baml_release = { workspace = true }
anyhow = { workspace = true }
console = { workspace = true }
reqwest = { workspace = true, features = [ "blocking", "rustls" ] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "baml"
path = "src/main.rs"

[package.metadata.ci]
wasm_support = false
