[general]
dirs = [
  "src/python/templates",
  "src/ruby/templates",
  "src/typescript/templates",
]
# whitespace can be either preserve, suppress, or minimize
# suppress and minimize are both too aggressive for us
whitespace = "preserve"
