import type { Monaco } from '@monaco-editor/react';

/**
 * Registers a compact BAML language for Monaco: a Monarch tokenizer + a light
 * "paper" theme that matches the deck. Idempotent (safe to call on every mount).
 */
let registered = false;

export function registerBaml(monaco: Monaco) {
  if (registered) return;
  registered = true;

  monaco.languages.register({ id: 'baml' });

  monaco.languages.setLanguageConfiguration('baml', {
    autoClosingPairs: [
      { close: '}', open: '{' },
      { close: ']', open: '[' },
      { close: ')', open: '(' },
      { close: '"', open: '"' },
      { close: '`', open: '`' },
    ],
    brackets: [
      ['{', '}'],
      ['[', ']'],
      ['(', ')'],
    ],
    comments: { lineComment: '//' },
  });

  monaco.languages.setMonarchTokensProvider('baml', {
    constants: ['true', 'false', 'null'],
    defaultToken: '',
    identifier: /\$?[A-Za-z_][A-Za-z0-9_-]*(?:\$[A-Za-z_][A-Za-z0-9_-]*)*/,
    keywords: [
      'function',
      'class',
      'enum',
      'type',
      'test',
      'testset',
      'client',
      'retry_policy',
      'generator',
      'let',
      'if',
      'else',
      'for',
      'while',
      'in',
      'break',
      'continue',
      'return',
      'throw',
      'throws',
      'match',
      'catch',
      'catch_all',
      'spawn',
      'with',
      'self',
      'instanceof',
      'dynamic',
      'watch',
      'import',
      'provider',
      'options',
      'prompt',
      'template_string',
      'interface',
      'implements',
      'implement',
      'const',
      'defer',
      'await',
      'is',
      'as',
      'requires',
      'extends',
    ],
    namespaces: ['root', 'baml', 'env'],
    operators: [
      '=',
      '==',
      '!=',
      '<',
      '>',
      '<=',
      '>=',
      '+',
      '-',
      '*',
      '/',
      '%',
      '++',
      '--',
      '<<',
      '>>',
      '+=',
      '-=',
      '*=',
      '/=',
      '%=',
      '<<=',
      '>>=',
      '&&',
      '||',
      '&',
      '^',
      '~',
      '!',
      '->',
      '=>',
      '|',
      '...',
      '?',
      '??',
      '?.',
      '.',
      ':',
      ',',
      ';',
    ],
    start: 'root',
    tokenizer: {
      attributes: [
        [
          /@{1,2}\$?[A-Za-z_][A-Za-z0-9_-]*(?:\s*\.\s*\$?[A-Za-z_][A-Za-z0-9_-]*)*/,
          'annotation',
        ],
      ],
      backtickInterpolation: [
        { include: '@comments' },
        [/\}/, { next: '@pop', token: 'variable' }],
        [/\{/, { next: '@push', token: '@brackets' }],
        { include: '@common' },
      ],
      backtickString2: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/``/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString3: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/```/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString4: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/````/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString5: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/`````/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString6: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/``````/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString7: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/```````/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickString8: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/````````/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      backtickstring: [
        [/\\./, 'string.escape'],
        [/\$\{/, { next: '@backtickInterpolation', token: 'variable' }],
        [/`/, { next: '@pop', token: 'string' }],
        [/[^\\`$]+/, 'string'],
        [/[`$]/, 'string'],
      ],
      blockComment: [
        [/[^/*]+/, 'comment'],
        [/\*\//, { next: '@pop', token: 'comment' }],
        [/[/*]/, 'comment'],
      ],
      byteString: [
        [/\\x[0-9A-Fa-f]{2}/, 'string.escape'],
        [
          /\\x(?:[0-9A-Fa-f]{0,1}(?=["\\]|$)|[0-9A-Fa-f]?[^0-9A-Fa-f"\\])/,
          'invalid',
        ],
        [/\\[ntr0"\\]/, 'string.escape'],
        [/\\./, 'invalid'],
        [/"/, { next: '@pop', token: 'string' }],
        [/[^\\"]+/, 'string'],
      ],
      classBody: [
        { include: '@comments' },
        { include: '@attributes' },
        { include: '@declarations' },
        [
          /^(\s*)(implements|implement)(\s+)/,
          ['', 'keyword.declaration.implements', ''],
        ],
        [
          /(^\s*|(?<=\{)\s*)(@identifier)(\s*:)/,
          ['', 'variable.other.property', 'operator'],
        ],
        [
          /(^\s*|(?<=\{)\s*)(@identifier)(\s+)(?=[A-Za-z_$([]|["#`])/,
          ['', 'variable.other.property', ''],
        ],
        [/\{/, { next: '@push', token: '@brackets' }],
        [/\}/, { next: '@pop', token: '@brackets' }],
        { include: '@common' },
      ],
      classHeader: [
        { include: '@comments' },
        [/@identifier/, 'type.identifier'],
        [/</, { next: '@typeParameters', token: 'operator' }],
        [/\{/, { switchTo: '@classBody', token: '@brackets' }],
        { include: '@common' },
      ],
      comments: [
        [/\/\/.*$/, 'comment'],
        [/\/\*/, { next: '@blockComment', token: 'comment' }],
      ],
      common: [
        { include: '@comments' },
        { include: '@strings' },
        { include: '@attributes' },
        [
          /(\.)(\s*)(as)(\s*)(?=<)/,
          ['operator', '', 'keyword.operator.as', ''],
        ],
        [
          /(\?\.|[.$])(\s*)(@identifier)(\s*)(?=\()/,
          ['operator', '', 'entity.name.function.method', ''],
        ],
        [
          /(\?\.|[.$])(\s*)(@identifier)/,
          ['operator', '', 'variable.other.readwrite'],
        ],
        [
          /(@identifier)(\s*)(?=\s*(?:<[^(){};]*>\s*)?\()/,
          ['entity.name.function', ''],
        ],
        [
          /(@identifier)(\s*)(?=\s*(?:<[^{};]*>\s*)?\{)/,
          [
            {
              cases: {
                '@default': 'type.identifier',
                '@typeKeywords': 'type',
              },
            },
            '',
          ],
        ],
        [/(@identifier)(\s*:)/, ['variable.other.property', 'operator']],
        [/@?\d+(?:\.\d+[eE][-+]?\d+|\.\d+|[eE][-+]?\d+)/, 'number.float'],
        [/@?\d+n\b/, 'number.bigint'],
        [/@?\d+\b/, 'number'],
        [
          /@identifier/,
          {
            cases: {
              '@constants': 'constant.language',
              '@default': 'identifier',
              '@keywords': 'keyword',
              '@namespaces': 'support.other.namespace',
              '@typeKeywords': 'type',
            },
          },
        ],
        [/[A-Z][A-Za-z0-9_-]*/, 'type.identifier'],
        [/[{}()[\]<>]/, '@brackets'],
        [/[=!<>|&+\-*/%.,;:?]+/, 'operator'],
      ],
      configBody: [
        { include: '@comments' },
        [
          /(^\s*|(?<=[{,])\s*)(@identifier)(\s*:)/,
          ['', 'variable.other.property', 'operator'],
        ],
        [
          /(^\s*|(?<=[{,])\s*)(@identifier)(\s+)(?=[A-Za-z_$([{'"#`-]|\d)/,
          ['', 'variable.other.property', ''],
        ],
        [
          /(^\s*|(?<=[{,])\s*)("(?:\\.|[^"\\])*")(\s*:)/,
          ['', 'string', 'operator'],
        ],
        { include: '@strings' },
        [/\{/, { next: '@push', token: '@brackets' }],
        [/\}/, { next: '@pop', token: '@brackets' }],
        [/\[/, { next: '@push', token: '@brackets' }],
        [/\]/, { next: '@pop', token: '@brackets' }],
        { include: '@common' },
      ],
      configHeader: [
        { include: '@comments' },
        [/\{/, { switchTo: '@configBody', token: '@brackets' }],
        { include: '@common' },
      ],
      declarations: [
        [
          /^(\s*)(function)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.function',
            '',
            { next: '@functionHeader', token: 'entity.name.function' },
          ],
        ],
        [
          /^(\s*)(class)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.class',
            '',
            { next: '@classHeader', token: 'type.identifier' },
          ],
        ],
        [
          /^(\s*)(interface)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.interface',
            '',
            { next: '@classHeader', token: 'type.identifier' },
          ],
        ],
        [
          /^(\s*)(enum)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.enum',
            '',
            { next: '@enumHeader', token: 'type.identifier' },
          ],
        ],
        [
          /^(\s*)(type)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.type-alias',
            '',
            { next: '@typeAlias', token: 'type.identifier' },
          ],
        ],
        [
          /^(\s*)(template_string)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.template-string',
            '',
            { next: '@templateHeader', token: 'entity.name.function' },
          ],
        ],
        [
          /^(\s*)(client)(\s*)(<)(\s*)(@identifier)(\s*)(>)(\s*)(@identifier)/,
          [
            '',
            'keyword.declaration.client',
            '',
            'operator',
            '',
            'type',
            '',
            'operator',
            '',
            { next: '@configHeader', token: 'entity.name.client' },
          ],
        ],
        [
          /^(\s*)(client)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.client',
            '',
            { next: '@configHeader', token: 'entity.name.client' },
          ],
        ],
        [
          /^(\s*)(retry_policy)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.retry-policy',
            '',
            { next: '@configHeader', token: 'entity.name.retry-policy' },
          ],
        ],
        [
          /^(\s*)(generator)(\s+)(@identifier)/,
          [
            '',
            'keyword.declaration.generator',
            '',
            { next: '@configHeader', token: 'entity.name.generator' },
          ],
        ],
        [
          /^(\s*)(generator)\b/,
          [
            '',
            { next: '@configHeader', token: 'keyword.declaration.generator' },
          ],
        ],
        [
          /^(\s*)(testset|test)(\s*)/,
          ['', 'keyword.declaration.test', { next: '@testHeader', token: '' }],
        ],
        [
          /^(\s*)(implements|implement)(\s+)/,
          [
            '',
            'keyword.declaration.implements',
            { next: '@implementsHeader', token: '' },
          ],
        ],
      ],
      enumBody: [
        { include: '@comments' },
        { include: '@attributes' },
        [/(@identifier)/, ['variable.other.enummember']],
        [/,/, 'operator'],
        [/\}/, { next: '@pop', token: '@brackets' }],
      ],
      enumHeader: [
        { include: '@comments' },
        [/\{/, { switchTo: '@enumBody', token: '@brackets' }],
        { include: '@common' },
      ],
      functionBody: [
        { include: '@comments' },
        { include: '@attributes' },
        [/^(\s*)(client)(\s*:?)/, ['', 'keyword.other.llm.client', 'operator']],
        [/^(\s*)(prompt)(\s*:?)/, ['', 'keyword.other.llm.prompt', 'operator']],
        { include: '@matchPatterns' },
        { include: '@statements' },
        { include: '@declarations' },
        [/\{/, { next: '@push', token: '@brackets' }],
        [/\}/, { next: '@pop', token: '@brackets' }],
        { include: '@common' },
      ],
      functionHeader: [
        { include: '@comments' },
        [/</, { next: '@typeParameters', token: 'operator' }],
        [/\(/, { next: '@parameters', token: '@brackets' }],
        [/->|=>/, 'keyword.operator.arrow'],
        [/\bthrows\b/, 'keyword.operator.throws'],
        [/\{/, { switchTo: '@functionBody', token: '@brackets' }],
        { include: '@common' },
      ],
      implementsHeader: [
        { include: '@comments' },
        [/</, { next: '@typeParameters', token: 'operator' }],
        [/\bfor\b/, 'keyword.declaration.for'],
        [/\{/, { switchTo: '@classBody', token: '@brackets' }],
        { include: '@common' },
      ],
      matchPatterns: [
        [
          /\b(let|const)(\s+)(@identifier)(\s*)(?=[^}]*=>)/,
          ['keyword.declaration.binding', '', 'variable.other.binding', ''],
        ],
        [
          /(^\s*|\|\s*)(?!let\b|const\b)(@identifier)(\s*)(?=[^}]*=>)/,
          [
            '',
            {
              cases: {
                '@default': 'type.identifier',
                '@typeKeywords': 'type',
              },
            },
            '',
          ],
        ],
        [
          /(:\s*)(@identifier)(\s*)(?=[^}]*=>)/,
          [
            'operator',
            {
              cases: {
                '@default': 'type.identifier',
                '@typeKeywords': 'type',
              },
            },
            '',
          ],
        ],
        [
          /(\.\s*)(@identifier)(\s*)(?=[^}]*=>)/,
          ['operator', 'type.identifier', ''],
        ],
      ],
      parameters: [
        { include: '@comments' },
        [/\)/, { next: '@pop', token: '@brackets' }],
        [/\(/, { next: '@push', token: '@brackets' }],
        [/\bself\b/, 'variable.language.self'],
        [/(@identifier)(\s*:)/, ['variable.parameter', 'operator']],
        [/->|=>/, 'keyword.operator.arrow'],
        [/\bthrows\b/, 'keyword.operator.throws'],
        { include: '@common' },
      ],
      rawString1: [
        [/"#/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString2: [
        [/"##/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString3: [
        [/"###/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString4: [
        [/"####/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString5: [
        [/"#####/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString6: [
        [/"######/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString7: [
        [/"#######/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      rawString8: [
        [/"########/, { next: '@pop', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      root: [
        { include: '@declarations' },
        { include: '@statements' },
        { include: '@common' },
      ],
      statements: [
        [
          /\b(let|const)(\s+)(_)\b/,
          ['keyword.declaration.binding', '', 'variable.language.wildcard'],
        ],
        [
          /\b(let|const)(\s+)(@identifier)/,
          ['keyword.declaration.binding', '', 'variable.other.binding'],
        ],
        [/\b_\b/, 'variable.language.wildcard'],
        [/\bwatch\b/, 'keyword.control.watch'],
        [/\breturn\b/, 'keyword.control.flow.return'],
        [/\bbreak\b/, 'keyword.control.flow.break'],
        [/\bcontinue\b/, 'keyword.control.flow.continue'],
        [/\bdefer\b/, 'keyword.control.flow.defer'],
        [/\bthrow\b/, 'keyword.control.flow.throw'],
        [/\b(if|else)\b/, 'keyword.control.conditional'],
        [/\b(match)\b/, 'keyword.control.match'],
        [/\b(for|while)\b/, 'keyword.control.loop'],
        [/\b(catch|catch_all)\b/, 'keyword.control.exception.catch'],
        [/\b(spawn|await|is|as|in|with)\b/, 'keyword.operator'],
      ],
      string: [
        [/\\./, 'string.escape'],
        [/"/, { next: '@pop', token: 'string' }],
        [/[^\\"]+/, 'string'],
      ],
      strings: [
        [
          /\b(b)(")/,
          ['storage.type.string', { next: '@byteString', token: 'string' }],
        ],
        [/########"/, { next: '@rawString8', token: 'string' }],
        [/#######"/, { next: '@rawString7', token: 'string' }],
        [/######"/, { next: '@rawString6', token: 'string' }],
        [/#####"/, { next: '@rawString5', token: 'string' }],
        [/####"/, { next: '@rawString4', token: 'string' }],
        [/###"/, { next: '@rawString3', token: 'string' }],
        [/##"/, { next: '@rawString2', token: 'string' }],
        [/#"/, { next: '@rawString1', token: 'string' }],
        [/````````/, { next: '@backtickString8', token: 'string' }],
        [/```````/, { next: '@backtickString7', token: 'string' }],
        [/``````/, { next: '@backtickString6', token: 'string' }],
        [/`````/, { next: '@backtickString5', token: 'string' }],
        [/````/, { next: '@backtickString4', token: 'string' }],
        [/```/, { next: '@backtickString3', token: 'string' }],
        [/``/, { next: '@backtickString2', token: 'string' }],
        [/`/, { next: '@backtickstring', token: 'string' }],
        [/"/, { next: '@string', token: 'string' }],
      ],
      templateHeader: [
        { include: '@comments' },
        [/\(/, { next: '@parameters', token: '@brackets' }],
        [
          /########"/,
          { switchTo: '@templateHeaderRawString8', token: 'string' },
        ],
        [
          /#######"/,
          { switchTo: '@templateHeaderRawString7', token: 'string' },
        ],
        [/######"/, { switchTo: '@templateHeaderRawString6', token: 'string' }],
        [/#####"/, { switchTo: '@templateHeaderRawString5', token: 'string' }],
        [/####"/, { switchTo: '@templateHeaderRawString4', token: 'string' }],
        [/###"/, { switchTo: '@templateHeaderRawString3', token: 'string' }],
        [/##"/, { switchTo: '@templateHeaderRawString2', token: 'string' }],
        [/#"/, { switchTo: '@templateHeaderRawString1', token: 'string' }],
        [/"/, { switchTo: '@templateHeaderString', token: 'string' }],
        { include: '@common' },
      ],
      templateHeaderRawString1: [
        [/"#/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString2: [
        [/"##/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString3: [
        [/"###/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString4: [
        [/"####/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString5: [
        [/"#####/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString6: [
        [/"######/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString7: [
        [/"#######/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderRawString8: [
        [/"########/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateHeaderString: [
        [/\\./, 'string.escape'],
        [/"/, { switchTo: '@root', token: 'string' }],
        { include: '@templateStringContent' },
      ],
      templateStringContent: [
        [/\\./, 'string.escape'],
        [/[^"{\\]+/, 'string'],
        [/["{\\]/, 'string'],
      ],
      testHeader: [
        { include: '@comments' },
        [/\{/, { switchTo: '@functionBody', token: '@brackets' }],
        { include: '@common' },
      ],
      typeAlias: [
        { include: '@comments' },
        [/=/, 'keyword.operator.assignment'],
        [/[;\n]/, { next: '@pop', token: 'operator' }],
        { include: '@common' },
      ],
      typeParameters: [
        { include: '@comments' },
        [/>/, { next: '@pop', token: 'operator' }],
        [/\bextends\b/, 'keyword.operator.extends'],
        [/@identifier/, 'type.identifier'],
        [/[,&|]/, 'operator'],
      ],
    },
    typeKeywords: [
      'bigint',
      'int',
      'float',
      'string',
      'bool',
      'image',
      'audio',
      'json',
      'map',
      'never',
      'Self',
      'unknown',
    ],
  });

  monaco.editor.defineTheme('baml-paper', {
    base: 'vs',
    colors: {
      'editor.background': '#FFFDF7',
      'editor.foreground': '#24292E',
      'editor.lineHighlightBackground': '#F4EEE0',
      'editor.selectionBackground': '#E6D9FA',
      'editorCursor.foreground': '#6D28D9',
      'editorIndentGuide.background1': '#EFE8D8',
      'editorLineNumber.activeForeground': '#6F6A63',
      'editorLineNumber.foreground': '#B9B2A3',
    },
    inherit: true,
    rules: [
      // Keywords are blue, not GitHub red — red is reserved for diagnostics
      // (squiggles + inline error-lens), so nothing healthy reads as an error.
      { foreground: '0550AE', token: 'keyword' },
      { foreground: '953800', token: 'type' },
      { foreground: '953800', token: 'type.identifier' },
      { foreground: '8250DF', token: 'entity.name.function' },
      { foreground: '8250DF', token: 'entity.name.function.method' },
      { foreground: '953800', token: 'variable.other.property' },
      { foreground: '24292E', token: 'variable.other.readwrite' },
      { foreground: '0A3069', token: 'string' },
      { foreground: '6E7781', token: 'comment' },
      { foreground: '0550AE', token: 'number' },
      { foreground: '24292E', token: 'variable' },
      { foreground: '24292E', token: 'operator' },
      { foreground: '24292E', token: 'identifier' },
    ],
  });

  // Dark presets (see code-theme.tsx). Keywords stay blue-ish, red is still
  // reserved for diagnostics. Classic VS Code "Dark+" palette.
  monaco.editor.defineTheme('baml-dark', {
    base: 'vs-dark',
    colors: {
      'editor.background': '#1E1E1E',
      'editor.foreground': '#D4D4D4',
      'editor.lineHighlightBackground': '#2A2A2A',
      'editor.selectionBackground': '#3A3D5C',
      'editorCursor.foreground': '#A78BFA',
      'editorIndentGuide.background1': '#2A2A2A',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'editorLineNumber.foreground': '#5A5A5A',
    },
    inherit: true,
    rules: [
      { foreground: '569CD6', token: 'keyword' },
      { foreground: '4EC9B0', token: 'type' },
      { foreground: '4EC9B0', token: 'type.identifier' },
      { foreground: 'DCDCAA', token: 'entity.name.function' },
      { foreground: 'DCDCAA', token: 'entity.name.function.method' },
      { foreground: '9CDCFE', token: 'variable.other.property' },
      { foreground: 'D4D4D4', token: 'variable.other.readwrite' },
      { foreground: 'CE9178', token: 'string' },
      { foreground: '6A9955', token: 'comment' },
      { foreground: 'B5CEA8', token: 'number' },
      { foreground: 'D4D4D4', token: 'variable' },
      { foreground: 'D4D4D4', token: 'operator' },
      { foreground: 'D4D4D4', token: 'identifier' },
    ],
  });

  // Cooler, deeper dark (Tokyo Night-ish) for comparison.
  monaco.editor.defineTheme('baml-midnight', {
    base: 'vs-dark',
    colors: {
      'editor.background': '#1A1B26',
      'editor.foreground': '#C0CAF5',
      'editor.lineHighlightBackground': '#1F2233',
      'editor.selectionBackground': '#33467C',
      'editorCursor.foreground': '#C0CAF5',
      'editorIndentGuide.background1': '#1F2233',
      'editorLineNumber.activeForeground': '#737AA2',
      'editorLineNumber.foreground': '#3B4261',
    },
    inherit: true,
    rules: [
      { foreground: '7AA2F7', token: 'keyword' },
      { foreground: '2AC3DE', token: 'type' },
      { foreground: '2AC3DE', token: 'type.identifier' },
      { foreground: 'E0AF68', token: 'entity.name.function' },
      { foreground: 'E0AF68', token: 'entity.name.function.method' },
      { foreground: '7DCFFF', token: 'variable.other.property' },
      { foreground: 'C0CAF5', token: 'variable.other.readwrite' },
      { foreground: '9ECE6A', token: 'string' },
      { foreground: '565F89', token: 'comment' },
      { foreground: 'FF9E64', token: 'number' },
      { foreground: 'C0CAF5', token: 'variable' },
      { foreground: '89DDFF', token: 'operator' },
      { foreground: 'C0CAF5', token: 'identifier' },
    ],
  });
}
