[package]
name = "llm-response-parser"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lints.rust]
dead_code = "warn"
elided_named_lifetimes = "warn"
unused_imports = "warn"
unused_variables = "warn"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
