// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)
//! by the stream_type_to_rust conversion.

use crate::baml_client::types;
use crate::baml_client::types::*;
use std::collections::HashMap;

/// Streaming variant of MixedPrimitives.
#[derive(Debug, Clone, Default)]
pub struct MixedPrimitives {
    pub name: Option<String>,

    pub age: Option<i64>,

    pub height: Option<f64>,

    pub isActive: Option<bool>,

    pub metadata: (),

    pub tags: Vec<String>,

    pub scores: Vec<i64>,

    pub measurements: Vec<f64>,

    pub flags: Vec<bool>,
}

/// Streaming variant of PrimitiveArrays.
#[derive(Debug, Clone, Default)]
pub struct PrimitiveArrays {
    pub stringArray: Vec<String>,

    pub intArray: Vec<i64>,

    pub floatArray: Vec<f64>,

    pub boolArray: Vec<bool>,
}

/// Streaming variant of PrimitiveMaps.
#[derive(Debug, Clone, Default)]
pub struct PrimitiveMaps {
    pub stringMap: std::collections::HashMap<String, String>,

    pub intMap: std::collections::HashMap<String, i64>,

    pub floatMap: std::collections::HashMap<String, f64>,

    pub boolMap: std::collections::HashMap<String, bool>,
}

/// Streaming variant of PrimitiveTypes.
#[derive(Debug, Clone, Default)]
pub struct PrimitiveTypes {
    pub stringField: Option<String>,

    pub intField: Option<i64>,

    pub floatField: Option<f64>,

    pub boolField: Option<bool>,

    pub nullField: (),
}
