# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"
gem "sorbet-coerce"
gem "sorbet-runtime"
gem "sorbet-struct-comparable"

group :test do
  gem "minitest-reporters"
end