require "rake/testtask"

task :generate do
  sh "ruby", \
     "-I../../engine/language_client_ruby/lib", \
     "../../engine/language_client_ruby/bin/baml-cli.rb", \
     "generate", "--from", "../baml_src"
end

Rake::TestTask.new do |t|
  t.libs << "../../engine/language_client_ruby/lib"
  t.libs << "baml_client"
  t.test_files = FileList["test_*.rb"]
end