name: Lint

on:
  push:
    branches:
      - canary
    tags-ignore:
      - "**"
  pull_request:
    paths:
      - "engine/baml-core-ffi/**"
      - ".github/workflows/baml-core-ffi-typescript-lint.yml"
    branches:
      - canary
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    defaults:
      run:
        working-directory: engine/baml-core-ffi
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: engine/baml-core-ffi/yarn.lock
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn lint

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy
