name: Bump versions

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      CLI:
        description: "Rust CLI"
        required: false
        type: choice
        options:
          - none
          - prerelease
          - pre
          - patch
          - minor
          - major
        default: none
      CLIENT_PYTHON:
        description: "Python Client"
        required: false
        type: choice
        options:
          - none
          - prerelease
          - pre
          - patch
          - minor
          - major
        default: none
      VSCODE_EXT:
        description: "VSCode Extension"
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: none

jobs:
  bump_version:
    runs-on: ubuntu-latest

    if: github.event.inputs.CLI != 'none' || github.event.inputs.CLIENT_PYTHON != 'none' || github.event.inputs.VSCODE_EXT != 'none'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install bumpversion
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion

      - name: Bump version - vscode-ext
        id: vscode_ext
        if: github.event.inputs.VSCODE_EXT != 'none'
        run: |
          VERSION=$(bumpversion --allow-dirty ${{ github.event.inputs.VSCODE_EXT }} --list | grep new_version | cut -d '=' -f 2)
          echo "::notice file=typescript/vscode-ext/packages/package.json::Upgrading to version ${VERSION}"
          echo "COMMIT_MSG=${COMMIT_MSG} [BUMP:vscode_ext:${VERSION}]" >> $GITHUB_ENV
        working-directory: ./typescript/vscode-ext/packages

      - name: Bump version - cli
        id: cli
        if: github.event.inputs.CLI != 'none'
        run: |
          VERSION=$(bumpversion --allow-dirty ${{ github.event.inputs.CLI }} --list | grep new_version | cut -d '=' -f 2)
          echo "::notice file=engine/baml-cli/Cargo.toml::Upgrading to version ${VERSION}"
          echo "COMMIT_MSG=${COMMIT_MSG} [BUMP:cli:${VERSION}]" >> $GITHUB_ENV
        working-directory: ./engine

      - name: Bump version - client_python
        id: py_client
        if: github.event.inputs.CLIENT_PYTHON != 'none'
        run: |
          VERSION=$(bumpversion --allow-dirty ${{ github.event.inputs.CLIENT_PYTHON }} --list | grep new_version | cut -d '=' -f 2)
          echo "::notice file=clients/python/pyproject.toml::Upgrading to version ${VERSION}"
          echo "COMMIT_MSG=${COMMIT_MSG} [BUMP:py_client:${VERSION}]" >> $GITHUB_ENV
        working-directory: ./clients/python

      - id: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          TIMESTAMP=$(date +%s%3N)
          git checkout -b ${{ github.actor }}/bump-version/${TIMESTAMP}
          git commit -am "${COMMIT_MSG}"
          git push origin ${{ github.actor }}/bump-version/${TIMESTAMP}
      - id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "${COMMIT_MSG}" --body "Automated flow to bump version${COMMIT_MSG}"
