name: Integration Tests

on:
  push:
    branches: [ sam/integ-tests-ci ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        _:
          - runs-on: ubuntu-22.04
            ollama-install: |
              curl -fsSL https://ollama.com/install.sh | sh
          - runs-on: macos-14
            ollama-install: |
              brew install ollama
          # winget is not available on windows-2019 or windows-2022
          # https://github.com/actions/runner-images/issues/8584
          - runs-on: windows-2025
            ollama-install: |
              winget install --id=Ollama.Ollama -e --accept-package-agreements
    name: ${{ matrix._.runs-on }}
    runs-on: ${{ matrix._.runs-on }}
    # For when we have go integ tests
    # env:
    #   GOARCH: ${{ matrix._.goarch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.ollama/models
          key: ollama-${{ matrix._.runs-on }}
      - name: Install Ollama
        run: ${{ matrix._.ollama-install }}
      - uses: astral-sh/setup-uv@v6
      - name: Run simple smoke test
        run: |
          ollama serve &
          set -euxo pipefail
          sleep 5
          ollama run tinyllama "2+2?"
          ./tools/build integ-tests/python
          ./tools/build integ-tests/typescript
          ./tools/build integ-tests/ruby
