name: Release

on:
  push:
    branches:
      - canary
  workflow_dispatch:
    inputs:
      CLI:
        description: "Release Rust CLI (AUTO,0,1)"
        required: true
        default: "AUTO"
      CLIENT_PYTHON:
        description: "Release Python Client (AUTO,0,1)"
        required: true
        default: "AUTO"
      VSCODE_EXT:
        description: "Release VSCode Extension (AUTO,0,1)"
        required: true
        default: "AUTO"

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Get Changes
      #   id: get_changes
      #   run: |
      #     COMMIT_MSG=${{ github.event.head_commit.message  }}
      #     if [ "${{ github.event.inputs.CLI }}" == "AUTO" ]; then
      #       echo "cli_changed=${COMMIT_MSG//*'[NIGHTLY:cli]'*/1}" >> $GITHUB_ENV
      #     else
      #       echo "cli_changed=${{ github.event.inputs.CLI }}" >> $GITHUB_ENV
      #     fi
      #     if [ "${{ github.event.inputs.CLIENT_PYTHON }}" == "AUTO" ]; then
      #       echo "client_python_changed=${COMMIT_MSG//*'[NIGHTLY:client-python]'*/1}" >> $GITHUB_ENV
      #     else
      #       echo "client_python_changed=${{ github.event.inputs.CLIENT_PYTHON }}" >> $GITHUB_ENV
      #     fi
      #     if [ "${{ github.event.inputs.VSCODE_EXT }}" == "AUTO" ]; then
      #       echo "vscode_ext_changed=${COMMIT_MSG//*'[NIGHTLY:vscode_ext]'*/1}" >> $GITHUB_ENV
      #     else
      #       echo "vscode_ext_changed=${{ github.event.inputs.VSCODE_EXT }}" >> $GITHUB_ENV
      #     fi

      - name: VSCode Extension
        # if: steps.get_changes.outputs.vscode_ext_changed == '1'
        uses: ./.github/actions/vscode

        
      - name: Python Client
        # if: steps.get_changes.outputs.client_python_changed == '1'
        uses: ./.github/actions/client_python
        with:
          release: 0
      

      - name: Rust CLI
        # if: steps.get_changes.outputs.cli_changed == '1'
        uses: ./.github/actions/cli
