name: Download Bindings From Run

on:
  push:
    branches:
      - sam/npm-adhoc2
  workflow_dispatch:

jobs:
  fetch-artifacts:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-action-version: 'v6'

      - name: Download bindings artifacts
        uses: actions/download-artifact@v4
        with:
          repo: BoundaryML/baml
          run-id: 20328548071
          pattern: bindings-*
          path: engine/language_client_typescript/artifacts
          github-token: ${{ secrets.SAM_BAML_ZED_GITHUB_TOKEN }}

      - name: Publish to NPM
        # Uses OIDC authentication via trusted publishers
        run: pnpm --filter=@boundaryml/baml publish --access public --no-git-checks
